### ISSUE TITLE
[dev.icinga.com #13879] SUSE cannot install icinga2

### ISSUE THREAD

**Issue by icinga-migration** [voxpupuli/puppet-icinga2#193]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13879

**Created by bsheqa on 2017-01-04 16:15:52 +00:00**

Assignee: _bsheqa_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-05 12:37:11 +00:00 (in Redmine)_

---

We probably need to upgrade to 12 SP2

    i2sles12sp1puppet4:/etc/zypp/repos.d # zypper install icinga2
    Loading repository data...
    Reading installed packages...
    Resolving package dependencies...

    Problem: nothing provides libboost_chrono.so.1.54.0()(64bit) needed by icinga2-bin-2.6.0-1.x86_64
     Solution 1: do not install icinga2-2.6.0-1.x86_64
     Solution 2: break icinga2-bin-2.6.0-1.x86_64 by ignoring some of its dependencies

**Comment by icinga-migration** [comment]
**Updated by bsheqa on 2017-01-04 16:19:26 +00:00**


The problem is that the repo we use for testing (http://dvd-images.icinga.com) does not provide the package 'libboost\_chrono'

**Comment by icinga-migration** [comment]
**Updated by bsheqa on 2017-01-05 12:37:11 +00:00**


This issue appeared already on monitoring-portal: https://monitoring-portal.org/index.php?thread/39323-icinga2-v2-6-auf-sles-12-sp2/

There's also already an issue open: https://dev.icinga.com/issues/13671

**Comment by bobapple** [comment]
A hint has been added in the latest Icinga 2 docs.
