### ISSUE TITLE
[dev.icinga.com #14031] Workaround for PuppetDB

### ISSUE THREAD

**Issue by icinga-migration** [voxpupuli/puppet-icinga2#198]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/14031

**Created by dgoetz on 2017-01-16 12:55:55 +00:00**

Assignee: _lbetz_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-16 13:09:54 +00:00 (in Redmine)_

---

I was hit by an ugly bug of PuppetDB: https://tickets.puppetlabs.com/browse/PDB-170
It effects exported resources containing arrays of only one element which will be stored as string and so collected. At least version 2.3 (required by Puppet 3.7) is affected, I hope newer versions work as I am the first one hit by this.
In the case of this module it hits primarily endpoints array of zone objects.

**Comment by icinga-migration** [comment]
**Updated by lbetz on 2017-01-16 12:57:24 +00:00**

* **Assigned to** set to _lbetz_

**Comment by icinga-migration** [comment]
**Updated by lbetz on 2017-01-16 13:09:54 +00:00**

* **Done %** changed from _0_ to _10_

modify of define resource 'zone' for tests.

**Comment by dgoetz** [comment]
I now managed to get verification that this workaround works fine. Thanks! 👍

**Comment by kwisatz** [comment]
Isn't this a duplicate of #152, e.g. the Array/String thing?

**Comment by lbetz** [comment]
finished 100%
can be merged
