### ISSUE TITLE
Set default for manage_repo param to true (use packages.icinga.com)

### ISSUE THREAD

**Issue by dnsmichi** [voxpupuli/puppet-icinga2#202]
Imho it should be best practice to use the official packages from packages.icinga.com, especially when you are using RPM based deployments. Debian users may still opt out from that.

Therefore I'm kindly asking to set `manage_repo` to true by default. If you agree, I'll happily send you a PR.

**Comment by bobapple** [comment]
Discussed this offline. We don't want to manage the users repositories by default.
