### ISSUE TITLE
Error: Failed to apply catalog: Found 2 dependency cycles:

### ISSUE THREAD

**Issue by pulsejets** [voxpupuli/puppet-icinga2#211]
system  debian 8.7

My puppet code:

``` puppet
   class { '::icinga2':
               manage_repo =>  true,
                 features =>  [ 'mainlog', 'command'],
           }

          class { '::mysql::server':
              root_password =>  'XXX',
              remove_default_accounts =>  true,
                    }



           mysql::db { 'icinga2':
              user =>  'icinga2',
              password =>  'XXX',
              host =>  'localhost',
              grant =>  ['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'DROP', 'CREATE VIEW', 'CREATE', 'INDEX', 'EXECUTE'],
           }

           class{ '::icinga2::feature::idomysql':
              user =>  'icinga2',
              password =>  'XXX',
              database =>  'icinga2',
              import_schema =>  true,
              require =>  Mysql::Db['icinga2'],
           }
```

i Get :

```
Error: Failed to apply catalog: Found 2 dependency cycles:
(Exec[concat_/etc/icinga2/features-available/command.conf] => File[/etc/icinga2/features-available/command.conf] => Concat[/etc/icinga2/features-available/command.conf] => File[/etc/icinga2/features-available/command.conf])
(File[/etc/icinga2/constants.conf] => Class[Icinga2::Config] => Concat[/etc/icinga2/features-available/mainlog.conf] => File[/opt/puppetlabs/puppet/cache/concat/_etc_icinga2_features-available_mainlog.conf] => Class[Icinga2::Config] => File[/etc/icinga2/constants.conf])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
```

**Comment by lazyfrosch** [comment]
I can't really reproduce this with your code:

    $ puppet apply --noop --modulepath ./modules test.pp
    Notice: Compiled catalog for amalia.lazyfrosch.de in environment production in 1.20 seconds

    $ puppet --version
    4.8.1

    $ puppet module list --modulepath ./modules
    ./modules
    ├── darin-zypprepo (v1.0.2)
    ├── icinga-icinga2 (v1.0.1)
    ├── puppetlabs-apt (v2.3.0)
    ├── puppetlabs-chocolatey (v2.0.1)
    ├── puppetlabs-concat (v2.2.0)
    ├── puppetlabs-mysql (v3.10.0)
    └── puppetlabs-stdlib (v4.15.0)

Is there anything else in your Puppet code, like defaults for `File {}`

**Comment by pulsejets** [comment]
hi 

I think i have found the issue 

puppetlabs-apt (v2.2.1)  invalid
├── puppetlabs-concat (v1.2.5)  invalid
├── puppetlabs-firewall (v1.4.0)
├── puppetlabs-haproxy (v1.4.0)
├── puppetlabs-inifile (v1.5.0)
├── puppetlabs-java (v1.5.0)
├── puppetlabs-mongodb (v0.16.0)
├── puppetlabs-mysql (v3.9.0)


/kenneth
