### ISSUE TITLE
Error installing module from forge for non r10k users

### ISSUE THREAD

**Issue by liketed** [voxpupuli/puppet-icinga2#217]
user@DEV $ puppet module install icinga-icinga2 --version 1.0.2 --ignore-dependencies --modulepath=forge
Notice: Preparing to install into /etc/puppetlabs/code/environments/DEV/forge ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/DEV/forge
└── icinga-icinga2 (v1.0.2)
user@DEV $ git add forge/icinga2
user@DEV $ git status
error: object directory /Users/bsheqa/.r10k/git/https---github.com-Icinga-puppet-icinga2.git/objects does not exist; check .git/objects/info/alternates.
fatal: bad object HEAD
fatal: 'git status --porcelain' failed in submodule forge/icinga2/serverspec/environments/production/modules/icinga2

**Comment by bobapple** [comment]
It looks like `puppet module build` included my serverspec modules. I will have to find a way to avoid this for future releases. #213 should solve this

Thanks for reporting @liketed

**Comment by liketed** [comment]
This is still valid even though the module is now available on forge and #213 is merged.

**Comment by bobapple** [comment]
We didn't have a release since the merge. This fix will be available in v1.0.3

**Comment by liketed** [comment]
Ahhhh, that's right. Ok, thanks :)
