### ISSUE TITLE
Create vars.foo["bar"] objects

### ISSUE THREAD

**Issue by anirban0105** [voxpupuli/puppet-icinga2#229]
I am facing similar issue described in https://github.com/Icinga/puppet-icinga2-legacy/issues/325 for the icinga2 module.

I am trying to create the default configuration files from Icinga 2 using the puppet module but I can't find a way to create vars objects. It is not possible to migrate the following snippet into the current puppet module:

  vars.notification["mail"] = {
    /* The UserGroup `icingaadmins` is defined in `users.conf`. */
    groups = [ "icingaadmins" ]
  }

In the puppet manifest I have the following:
  icinga2::object::host { 'generic-host':
    max_check_attempts =>  5,
    check_interval     =>  '1m',
    retry_interval     =>  '50s',
    vars               =>  {
      notification       => {
        mail => '{ groups = [ "icingaadmins" ] }'
      },
    },
    check_command      =>  'hostalive',
    target             =>  '/etc/icinga2/conf.d/templates.conf',
    template           =>  true,
  }

And the output I am getting is:
template Host "generic-host"  {
  vars.notification["mail"] = "{ groups = [ "icingaadmins" ] }"
  check_command = "hostalive"
  max_check_attempts = 5
  check_interval = 1m
  retry_interval = 50s
}

Its adding the extra double quotes around { groups = [ "icingaadmins" ] }

**Comment by lbetz** [comment]
Hi,

what do you get, if you leave the quotes?

mail => '{ groups = [ "icingaadmins" ] }‘


> Am 08.02.2017 um 13:56 schrieb anirban0105 <notifications@github.com>:
> 
> mail => '{ groups = [ "icingaadmins" ] }'

**Comment by anirban0105** [comment]
Hi,

mail => { groups = [ "icingaadmins" ] } is not a valid puppet syntax.

However, I managed to get it working with the following:
    vars               =>  {
      notification       => {
        mail => {
          groups => [ 'icingaadmins' ]
        },
      },
    },
The output is below as expected:
  vars.notification["mail"] = {
    groups = [ "icingaadmins", ]
  }

Closing the issue.
