### ISSUE TITLE
Update docs of example4 with hint for Puppet 4

### ISSUE THREAD

**Issue by bobapple** [voxpupuli/puppet-icinga2#234]
Looks like Puppet Forge is testing the examples for validation. In our rake task we disable examples explicitly from testing.

With Puppet 3.x validation fails for example4:

```
root@icinga2-puppet3:~/modules/icinga2# for file in `find . -name "*.pp" -type f`; do puppet parser validate $file; done
Error: Could not parse for environment production: Syntax error at '*'; expected '}' at /root/modules/icinga2/examples/example4/profile/manifests/agent.pp:51
Error: Could not parse for environment production: Syntax error at '*'; expected '}' at /root/modules/icinga2/examples/example4/profile/manifests/slave.pp:67
```

**Comment by bobapple** [comment]
Looks like puppet forge is ignoring examples now, quality score is up to 4.7 again.
I think it's sufficient to add a note somewhere that this example is only for Puppet 4, if not already included.

**Comment by lbetz** [comment]
add a comment that the example is for puppet 4 only
