### ISSUE TITLE
Enhance docs on how to enable and use features

### ISSUE THREAD

**Issue by ghost** [voxpupuli/puppet-icinga2#235]
Hi,

I get a strange error in puppet and the newest icinga-icinga2 puppet module.

` 
 class { 'icinga2::feature::idomysql':
    user          => 'icinga2',
    password      => 'supersecret',
    database      => 'icinga2',
    import_schema => true,
    require       => [
                     Mysql::Db['icinga2'],
                     Class['::icinga2'],
                     ],
   }`
```
root@lvps8x-13x-25-209:~# puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Facter: error while resolving custom fact "uid_min": invalid byte sequence in US-ASCII
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: {"message":"Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::icinga2::feature::ido-mysql for em.x.de at /etc/puppetlabs/code/environments/production/modules/icinga2/manifests/init.pp:172:3 on node em.x.de","issue_kind":"RUNTIME_ERROR","stacktrace":["Warning: The 'stacktrace' property is deprecated and will be removed in a future version of Puppet. For security reasons, stacktraces are not returned with Puppet HTTP Error responses."]}
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

```
Why is it searching for the class ::icinga2::feature::ido-mysql and why it cannot find it.

**Comment by bobapple** [comment]
I am not able to reproduce this. Do you have some other puppet code somewhere in addition to what you pasted? Maybe you declared `::icinga2::feature::ido-mysql` somewhere else?

Also, you should not `require => Class['::icinga2']` when using a feature class.

**Comment by ghost** [comment]
Hi,

I have three puppet files

init.pp

```
class qmonitoring {
  include qmonitoring::icinga2q
}
```


```
# install Icinga 2

class qmonitoring::icinga2q (
                            $icinga2_db_address = 'localhost',
                            $icinga2_db_password = 'redacted',
                            ) {
  # create the requirements db users
  # include qmonitoring::db
  require qmonitoring::db

  # install Icinga 2
  class { '::icinga2':
    manage_repo => true,
    enable      => true,
    features    => [ 'api', 'checker', 'command', 'ido-mysql', 'mainlog',
                     'notification', 'statusdata', 'syslog' ],
  }

  mysql::db { 'icinga2':
    user     => 'icinga2',
    password => $qmonitoring::icinga2_ido_password,
    host     => $qmonitoring::icinga2_db_address,
    grant    => ['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'DROP', 'CREATE VIEW',
    'CREATE', 'INDEX', 'EXECUTE', 'ALTER' ],
  }

  class { 'icinga2::feature::idomysql':
    user          => 'icinga2',
    password      => 'supersecret',
    database      => 'icinga2',
    import_schema => true,
    require       => [
                     Mysql::Db['icinga2'],
                     Class['::icinga2'],
                     ],
   }
}
```

```
# installs MySQL and creates db for icinga2
#
# get data from Hiera if it is configured
class qmonitoring::db (
                        $mysql_root_password = 'blubb_fake_lubb',
                      ) {

  # install and start database
  class { '::mysql::server':
    root_password            => $mysql_root_password,
    remove_default_accounts  => true,
  }
}
```
Maybe the problem comes from the features line

features    => [ 'api', 'checker', 'command', 'ido-mysql', 'mainlog',
                     'notification', 'statusdata', 'syslog' ],

I don't understand the error message right now.

**Comment by bobapple** [comment]
You should remove the `ido-mysql` from your `features => [...]` array.

Probably we need to make the documentation more clear that you are supposed to either enable a feature with the `features => [...]` array **OR** by declaring the class, not both.

**Comment by ghost** [comment]
Hi,

great.  If I use the feature option it would create a mysql configuration with the default values?

**Comment by bobapple** [comment]
Without further configuration the ido-mysql feature will set the following defaults:
```
  $user                   = 'icinga',
  $password               = 'icinga',
  $database               = 'icinga',
```

It will also not import the schema by default. It's recommended to set a proper configuration by declaring the classs.
