### ISSUE TITLE
dependency cycles

### ISSUE THREAD

**Issue by matthiasritter** [voxpupuli/puppet-icinga2#240]
Hi,
I've just testet all releases from v0.7.0 to v1.1.0 and get the following error message:

Error: Failed to apply catalog: Found 2 dependency cycles:
(Exec[concat_/etc/icinga2/features-available/mainlog.conf] => File[/etc/icinga2/features-available/mainlog.conf] => Concat[/etc/icinga2/features-available/mainlog.conf] => File[/etc/icinga2/features-available/mainlog.conf])
(File[/etc/icinga2/constants.conf] => Class[Icinga2::Config] => Concat[/etc/icinga2/features-available/mainlog.conf] => File[/var/lib/puppet/concat/_etc_icinga2_features-available_mainlog.conf] => Class[Icinga2::Config] => File[/etc/icinga2/constants.conf])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz

In my puppet-service I only include the icinga2-module in this way:

class { '::icinga2':
    confd    => false,
    features => ['mainlog'],
  }

Am I doing something wrong here?
We're using:
- ruby 2.0.0p598
- puppet 3.8.7

Thank you
Matthias

**Comment by bobapple** [comment]
You most likely have an outdated `concat` module. We had similiar issues in #211 and #224 

See the [dependencies](https://github.com/Icinga/puppet-icinga2#dependencies) section of the docs for more information

**Comment by matthiasritter** [comment]
Oh you're right. Thanks for the hint!
