### ISSUE TITLE
enable_ha for notification feature

### ISSUE THREAD

**Issue by matthiasritter** [voxpupuli/puppet-icinga2#242]
Hi,
I'm missing the parameter "enable_ha = true" in the notification feature.

object NotificationComponent "notification" {
  enable_ha = true
}

It is needed, when operating 2 or more master-systems.
Thank you

**Comment by lbetz** [comment]
Notifications are load-balanced amongst all nodes in a zone. By default this functionality is enabled. If your nodes should send out notifications independently from any other nodes (this will cause duplicated notifications if not properly handled!), you can set enable_ha = false in the NotificationComponent feature.
