### ISSUE TITLE
applied service (icinga2) duplicated declaration

### ISSUE THREAD

**Issue by Sukiyakijango** [voxpupuli/puppet-icinga2#245]
hi there, thx for theis great module.
i have an issue with the applied service with string (for syntax) with the same descriptor/identifer... for example if i have ...
apply Service  for (proc_name => proc_config in host.vars.procs) to Host {
....
  check_command = "proc"
 .....} 
and
apply Service for (app_name => port in host.vars.tcp_ports) to Host {
...
  check_command = "tcp"
 ....
}
in the case proc_name == app_name i get an duplicated declaration error
this would be easily fixed by adding the service_name to the applied rules...
example:
apply Service "Check-proc-"  for (proc_name => proc_config in host.vars.procs) to Host {
and
apply Service "check-tcp-"  for (app_name => port in host.vars.tcp_ports) to Host {

i fixed this like follows (will issue a pull request tomorow)

changing the object.conf.erb

<% if @apply.is_a?(String) %>apply <%= @object_type -%>
<% if scope.lookupvar('icinga2::_constants').include?(@object_name) -%>
 <%= @object_name -%>
<% else -%>
 "<%= @object_name %>" <% end -%> for (<%= @apply %>) to <%= @apply_target -%> {
<% else -%>
<% if @apply %>apply<% else -%>
<% if @template %>template<% else %>object<% end -%>
<% end %> <%= @object_type -%>
<% if scope.lookupvar('icinga2::_constants').include?(@object_name) -%>
 <%= @object_name -%>
<% else -%>
 "<%= @object_name %>" <% end -%>
<% if @apply && @apply_target %>to <%= @apply_target -%><% end -%> {
<% end -%>
<% @import.each do |i| -%>
  import "<%= i %>"
<% end -%>
<% unless @import.empty? %><%= "\n" %><% end -%>
<% if @apply.is_a?(String) and @apply =~ /^([A-Za-z_]+)\s+in\s+.+$/ -%>
<%= scope.function_icinga2_attributes([@_attrs.merge({$1 => :undef}),2]) -%>
<% elsif @apply.is_a?(String) and @apply =~ /^([A-Za-z_]+)\s+=>\s+([A-Za-z_]+)\s+in\s+.+$/ %>
<%= scope.function_icinga2_attributes([@_attrs.merge({$1 => :undef, $2 => :undef}),2]) -%>
<% else -%>
<%= scope.function_icinga2_attributes([@_attrs,2]) -%>
<% end -%>
}

**Comment by bobapple** [comment]
We have a pull request for this over here: https://github.com/Icinga/puppet-icinga2/pull/228

However it still needs to be reviewed

**Comment by Sukiyakijango** [comment]
ah ok thx dint see that one
total diffrent approche to fix it  but wonderfull :)

**Comment by lbetz** [comment]
proc_name and app_name are taken for the service name as default. Services with the same name applied to one host doesn't make sense.

Why you wanna use the same service name?

**Comment by Sukiyakijango** [comment]
@ibetz in this case (as an example) proc_name and app_name both have the value "openssh", so it makes perfekt sence to check if the proc of oppenssh is there and if the tcp port is open...
but im perfectly happy with the solution of pull request #228 
this issue can be closed if an when #228  is accepted and merged
thx
