### ISSUE TITLE
attribute keys are missed for parsing

### ISSUE THREAD

**Issue by lbetz** [voxpupuli/puppet-icinga2#246]
The attribute keys are used to identify values that must not quoted thru the parsing mechanism. So we must not delete attribute with an undefined value.

Idea: move delete_undef_value from dedicated object definition to the main object resource and add a new parameter to the attributes function to get a list of unquoted words.

**Comment by Reamer** [comment]
Hi @lbetz,
If you remove delete_undef_value from dedicated object, we will get Warnings which I described in PR (https://github.com/Icinga/puppet-icinga2/pull/222). The icinga2::object is created in each dedicated object. I think "delete_undef_value" function is at last position before Puppetserver tries to save our icinga::object.
Just a thought maybe I am totally wrong.

**Comment by lbetz** [comment]
Not remove, move to the object define resource ::icinga2::object.

**Comment by Reamer** [comment]
I'll will take a look into puppetserver log with your patch.

**Comment by Reamer** [comment]
I checked it in puppetserver log with your patch and all Warnings are now present again. Thats because you removed delete_undef_value from dedicated object.

**Comment by lbetz** [comment]
OK, that's mean the problem is inside puppet and not between puppet and erb or ruby. Makes sense, puppet is implemented in ruby. Shit so we've to move delete_undef_values back to all objects and implement something to handover the attribute keys for parsing.

**Comment by lbetz** [comment]
Please try the current commit to branch bug/attribute-keys-are-missed-for-parsing-246.

**Comment by Reamer** [comment]
Tested with current master and Puppet 4 -> No warning
