### ISSUE TITLE
Module parsing '(' incorrectly

### ISSUE THREAD

**Issue by choonming** [voxpupuli/puppet-icinga2#253]
I have a vars hash in my service object :

```
   vars          => {
      mysql_query_hostname => '127.0.0.1',
      mysql_query_username => 'icinga',
      mysql_query_password => 'password',
      mysql_query_execute  => 'select count(user) from mysql.user',
    },
```

However, the module is parsing it incorrectly and appending " to the ( resulting in the following:
```
-  vars.mysql_query_execute = "select count(user) from mysql.user"
+  vars.mysql_query_execute = select count("user) from mysql.user"
```

Not to mention, when there is a nested () in the value, it'll parse it incorrectly as well
```
assign where match("db*.example.com", host.name) && !regex(db00("04|05|09).example.coml", host.name)
```

Can we not parse the vars attribute but only parse the assign/ignore attributes only? Currently using v1.1.0

**Comment by lbetz** [comment]
Yes, we don't consider SQL statements. I play with the idea to use a tag at the front of the string to disable the parsing.

The parser is just for simple parsing. Please use file resources to implement complex structures.

**Comment by choonming** [comment]
@lbetz IMHO, it is nice to have the parser to parse the config to ensure its done correctly but then again a simply parser in my opinion, could just simply enclose the key/value of the attributes with double quotes. Converting ( to (" is overly complicated and breaks so many things on so many levels.

We have to be realistic that in some configs the assign rules or apply rules can be complex. I do not fancy the idea of having to use additional file resource to achieve this when we already have a defined type for this purpose. This defeats the whole idea of puppet and not reinventing wheel.

Just my 2 cents.

**Comment by lbetz** [comment]
What's about my solution to tag the string like -: to disable the parser? Additional it could be possible to enable or disable the parser completely and enable it for dedicated values with +:?

**Comment by lbetz** [comment]
Related #254

**Comment by lbetz** [comment]
Try the related branch 
enhancement/use-a-tag-to-disable-parsing-for-a-single-attribute-value-254

Keep in mind that now you have to set your own quotes like: 
mysql_execute => '-:"select count (user) from mysql.user"',

**Comment by choonming** [comment]
@lbetz can I make a suggestion? Instead of turning off completely the initial double quotes, how about simply just parsing it to be enclosed with double quotes and do nothing else to the string when that tag or flag is used?

**Comment by lbetz** [comment]
No, that's to less. Same tag has to work for expressions in assign rules. Without quotes.

**Comment by bobapple** [comment]
See #254
