### ISSUE TITLE
use a tag to disable parsing for a single attribute value

### ISSUE THREAD

**Issue by lbetz** [voxpupuli/puppet-icinga2#254]
Use -: as tag. Maybe later we can add a parameter to the icinag2 main class to turn on and off parsing globally and add the tag +: to activate the parser for single attributes.

**Comment by walterheck** [comment]
Can this be released asap please? We have a severely broken icinga environment due to this problem.

**Comment by bobapple** [comment]
Hey @walterheck 
Expect a release during this week, at the latest beginning of the next week.
