### ISSUE TITLE
Object arguments ordering not persistent

### ISSUE THREAD

**Issue by LorenzBischof** [voxpupuli/puppet-icinga2#258]
The order of arguments in objects isn't persistent and changes on every puppet run. Would it be possible to sort these somehow so that they are always in the same order?
```
template Service "generic-service"  {
   display_name = "generic-service"
-  retry_interval = 30s
-  check_interval = 1m
+  retry_interval = 30s
   max_check_attempts = 5
+  check_interval = 1m
 }
```

**Comment by bobapple** [comment]
What version of Puppet and Ruby are you using?

**Comment by LorenzBischof** [comment]
```
Distro          Centos 7.3
Puppetversion	3.8.7
Rubyversion	2.0.0
```

**Comment by lbetz** [comment]
I used the same and my second run looks:

root@centos7 icinga2]# puppet apply examples/example_config.pp 
Notice: Compiled catalog for centos7.openvpn in environment production in 4.19 seconds
Notice: Finished catalog run in 0.60 seconds

**Comment by LorenzBischof** [comment]
Sorry I should have added that I am using exported resources.

**Comment by lbetz** [comment]
And you're running CentOS 7.3 on both machine, the exporter and the collector?

**Comment by LorenzBischof** [comment]
Yes, but it also happens on Centos 6.8. I guess this is probably a Puppet bug, just too bad it worked with the old module.

I just noticed that the resources that are showing the problem aren't even exported. They are checkcommand and template objects. I will try and diagnose the problem better and report back with more info.

**Comment by bobapple** [comment]
Could this be related to unsorted arrays/hashes in Ruby 1.8?

**Comment by LorenzBischof** [comment]
Good point, we are still using ruby 1.8.7 on our puppetmaster. I wonder if that's the problem

**Comment by bobapple** [comment]
That may cause the problem, we require Ruby >= 1.9 because of this issue

**Comment by LorenzBischof** [comment]
Ok, we are evaluating Puppet 4 anyway so this just adds a bit more pressure to upgrade. Thanks for helping
