### ISSUE TITLE
Undefined method keys for []:Array

### ISSUE THREAD

**Issue by teancom** [voxpupuli/puppet-icinga2#267]
After updating the icinga2 module to latest (from 0.6.0 previously), I get the following failure:

```
    Error 400 on SERVER: undefined method `keys' for []:Array at /etc/puppet/environments/production/modules/icinga2/manifests/config.pp:26
```

This is with puppet 3.8.7 and facter 2.4.6.

**Comment by Reamer** [comment]
maybe an stdlib problem. Have you the required version >= 4.10.0?

**Comment by teancom** [comment]
I have stdlib 4.12.0

**Comment by Reamer** [comment]
What ruby version do you use?

**Comment by teancom** [comment]
ruby-1.8.7.352-7.el6_2 on Centos6 (latest available for centos 6)

**Comment by teancom** [comment]
I just updated to stdlib 4.15.0 to double-check, no change.

**Comment by martinheinr** [comment]
Are you using Icinga 2.6.2 Release ? I had similar problems until I updated to the latest release

**Comment by teancom** [comment]
Yeah, icinga2 2.6.2 from http://packages.icinga.org/epel/

I'm going to try rolling back releases of puppet-icinga2 to see if I can figure out where it stopped working.

**Comment by teancom** [comment]
Rolling back to v1.1.1 fixed the problem.

**Comment by Caprico85** [comment]
Did you try restarting your puppetmaster to clear caches? See https://github.com/Icinga/puppet-icinga2/issues/261

**Comment by lbetz** [comment]
Restarting your puppet master or clearing the cache will fix the problem. And please keep in mind, we use sorted hashes and arrays. Both don't supported by ruby version less than 1.9.

**Comment by teancom** [comment]
I tried up revving to 1.2.0 again, restarted my puppet master, no change. Still the same error.

**Comment by LorenzBischof** [comment]
Could this be the same issue?: https://github.com/envato/rails_4_session_flash_backport/issues/19 Since Ruby 1.8.7 is not supported this will probably not be fixed...

**Comment by bobapple** [comment]
@teancom how do you run your puppetmaster? how did you perform the restart?

**Comment by teancom** [comment]
Behind apache with passenger, and I restarted apache.

**Comment by bobapple** [comment]
Can you paste the puppet code you are using? We are currently trying to reproduce this issue

**Comment by bobapple** [comment]
@teancom can you provide the puppet code you use so we can try to recreate the issue?

Together will all versions you use for Puppet, Ruby, OS, ...

**Comment by teancom** [comment]
Sorry, I didn't mean to ignore you. It's a fairly large module, that'll I've have to redact. I'll see about getting a minimum viable reproduction of the problem.

**Comment by bobapple** [comment]
I think your issue is the same as #268
Can you confirm?

**Comment by lazyfrosch** [comment]
Just using Ruby 1.8.7 is enough obviously.

Seems like icinga2_attributes is not compatible to Ruby 1.8.7

Tweaked Gemfile:

``` ruby
source 'https://rubygems.org'

gem 'puppet', ENV.key?('PUPPET_VERSION') ? ENV['PUPPET_VERSION'].to_s : '>= 3.8'

gem 'puppetlabs_spec_helper', '< 2.0'
gem 'puppet-lint', '>= 0.3.2'
gem 'facter', '>= 1.7.0'
gem 'facterdb', '>= 0.3.10'
gem 'rspec-puppet-facts', '>= 1.6.0'
#gem 'metadata-json-lint'

#gem 'parallel_tests', RUBY_VERSION < '2.0.0' ? '~> 2.9.0' : '>= 2.10.0'

# json > 2.0.1 is not compatible with Ruby 1.9
if RUBY_VERSION < '2.0.0'
  gem 'json', '< 2'
  gem 'json_pure', '< 2'
end

if RUBY_VERSION < '1.9.0'
  gem 'rake', '< 11'
end
```

Running test:

```
rake spec_prep
puppet apply --modulepath spec/fixtures/modules --noop -e "include ::icinga2" --verbose --trace
```

Leading to error:

```
Error: undefined method `keys' for []:Array at /home/markus/devel/icinga/puppet-icinga2/spec/fixtures/modules/icinga2/manifests/config.pp:26 on node amalia
...
/home/markus/devel/icinga/puppet-icinga2/lib/puppet_x/icinga2/utils.rb:203:in `attributes'
/home/markus/devel/icinga/puppet-icinga2/lib/puppet/parser/functions/icinga2_attributes.rb:25:in `real_function_icinga2_attributes'
/home/markus/.rvm/gems/ruby-1.8.7-p374@puppet/gems/puppet-3.8.7/lib/puppet/parser/functions.rb:164:in `send'
/home/markus/.rvm/gems/ruby-1.8.7-p374@puppet/gems/puppet-3.8.7/lib/puppet/parser/functions.rb:164:in `function_icinga2_attributes'
...
```

**Comment by lazyfrosch** [comment]
Only location where Ruby 1.8 should still be in place is RHEL 6 (RHEL 5 is EOL)

Since there are other problems in Ruby 1.8, like Hash key sorting etc. I would not support that version anymore.

Other Puppet module projects do the same, and I think we should follow them.

If you need to use RHEL6 as a user, please go for the newer Puppet packaging, as its the only supported version upstream.

Though I think PRs (if they are trivial) for this issue are welcome!

**Comment by bobapple** [comment]
I'm closing this issue since it is related to Ruby 1.8.7 which is not supported by this module. Please refer to the [dependencies](https://github.com/icinga/puppet-icinga2#dependencies) section of the documentation.
