### ISSUE TITLE
wrong number of arguments calling `attributes` (4 for 3)

### ISSUE THREAD

**Issue by druchoo** [voxpupuli/puppet-icinga2#269]
**OS**: CentOS Linux release 7.2.1511 (Core)
**Puppet**: 4.8.1
**Facter**: 3.5.0
**Ruby**: 2.0.0
**puppetlabs-concat**: 2.2.0
**puppetlabs-stdlib**: 4.12.0

I get the following error using `v1.2.0` or latest commit (`170f14a`). Error not encountered with `v1.1.1`.

> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, wrong number of arguments calling `attributes` (4 for 3) at /etc/puppetlabs/code/environments/feature_icinga_master/modules/icinga2/manifests/config.pp:26:28 on node icinga-master1-xxxxxxxx

Manifest:
```Puppet
class { '::icinga2':
  manage_package => true,
}
```

**Comment by lbetz** [comment]
Please clear your cache on your master.

**Comment by druchoo** [comment]
Restarting Puppet master resolved issue. Thanks for your help.
