### ISSUE TITLE
Replace deprecated stdlib functions

### ISSUE THREAD

**Issue by bobapple** [voxpupuli/puppet-icinga2#275]
The following functions we use from the `stdlib` module are deprecated and need to be replaced with `validate_legacy`

- `is_array`
- `is_bool`
- `is_string`
- `validate_array`
- `validate_bool`
- `validate_hash`
- `validate_re`
- `validate_string`

**Comment by lbetz** [comment]
In this case we have to update to stdlib 4.13.0 and above.

**Comment by bobapple** [comment]
I wouldn't update the stdlib requirement to 4.13 immediately, many people still run on old versions. Let's keep this issue as reminder.

**Comment by lbetz** [comment]
https://forge.puppet.com/puppetlabs/stdlib
shows: Note: This function is compatible only with Puppet 4.4.0 (PE 2016.1) and later.

So we'll lose puppet 3 compatibility.

**Comment by lbetz** [comment]
refers to:

#350
#362

**Comment by ekohl** [comment]
I'd be happy to write a patch. Is dropping Puppet 3 a problem?

**Comment by baurmatt** [comment]
It's (more or less) done with #350

**Comment by lbetz** [comment]
We start with dropping it after acceptence tests are implemented.
