### ISSUE TITLE
Add IDO PostreSQL integration tests

### ISSUE THREAD

**Issue by bobapple** [voxpupuli/puppet-icinga2#278]

**Comment by bobapple** [comment]
Implemented in: https://github.com/Icinga/puppet-icinga2/tree/ido-pgsql-testing-278

On `.deb` based systems it's currently not possible to install both packages `icinga2-ido-mysql` and `icinga2-ido-pgsql`. This branch will be merged when the limitation has been removed.

**Comment by lbetz** [comment]
refs #356
