### ISSUE TITLE
RSpec Puppetlabs modules incompatible to Puppet 3

### ISSUE THREAD

**Issue by lazyfrosch** [voxpupuli/puppet-icinga2#286]
Latest releases of some Puppetlabs modules are no longer compatible to Puppet 3, and therefor breaking our tests.

Includes at least:
* puppetlabs-apt
* puppetlabs-concat
* puppetlabs-stdlib

We should find a proper way to split fixtures between Puppet Versions (probably by using different fixtures when `PUPPET_VERSION` is Puppet < 4)

**Comment by lazyfrosch** [comment]
stdlib seems not *yet* affected...

**Comment by walterheck** [comment]
Isn't Puppet < 4 EOL? https://puppet.com/misc/puppet-enterprise-lifecycle

**Comment by bobapple** [comment]
@walterheck yes it is. However, there are still plenty of users out there who are using Puppet 3, because a migration (especially in bigger environments) takes ages. Therefore, this module is Puppet 3 compatible.

**Comment by lazyfrosch** [comment]
If we lived in a perfect world...
