### ISSUE TITLE
Apply: How to set "if(...) { .. }

### ISSUE THREAD

**Issue by linuxmail** [voxpupuli/puppet-icinga2#289]
hi,

how can I set something like:

```
...
apply Notification "host-default" to Host {
  import "notification-base-host"
  # Set interval
  if(host.vars.notification_interval){
	interval = host.vars.notification_interval
  }
  # Set period
  if(host.vars.alerting){
	period = host.vars.alerting
  }
...
```
I want to test: https://monitoring-portal.org/index.php?thread/33662-solved-notification-definition-in-icinga-2/&postID=217609#post217609

cu denny

**Comment by lbetz** [comment]
Problem is the if condition, same exists with other flow logic elements. If you wanna use such config snippets try the define resource: icinga2::config::fragment

With the content attribute you're complete free, but of course you have to write the whole object definition as text.

**Comment by linuxmail** [comment]
hi @lbetz 

thanks. I'm using for services already apply rules via files, so it is O.K.

Thanks for helping on a weekend :-)

cu denny

**Comment by lbetz** [comment]
You're welcome. So I close this issue.
