### ISSUE TITLE
Add owner-, groupship and permissions to file resources

### ISSUE THREAD

**Issue by lbetz** [voxpupuli/puppet-icinga2#291]
to protect for wrong permissions set by default resource for file.

**Comment by altona93** [comment]
Icinga does not start on Ubuntu when installed via Puppet due to the wrong permissions of /etc/icinga2. Fix should be easy.

either 
  file { $conf_dir:
    ensure  => directory,
    owner   => $user,
    group   => $group,
  }
or remove the file resource completely as the dir will be created by the package with correct permissions anyway.

**Comment by lbetz** [comment]
Management of $conf_dir is removed with #369.

**Comment by lbetz** [comment]
Management of cons_dir is back again, and now with ownership and group.
