### ISSUE TITLE
Support += operator

### ISSUE THREAD

**Issue by deric** [voxpupuli/puppet-icinga2#294]
I've noticed that configuration like
```
vars += config
```
is not supported in Puppet module yet. Is there some workaround or a plan to implement this feature?

Currently I'm have configuration:
```puppet
    apply   => 'disk_name => config in host.vars.hdd',
    vars     => 'vars + config',
```
and I'd like to merge `vars + config` with another Hash. I guess the easiest way is to use deep hash merging in Hiera, or am I missing something?

**Comment by lbetz** [comment]
Using

vars => 'vars + config'

is completely correct. That's the way of this module and icinga accept vars = vars + config. Also correct should be vars = vars + config + other_dictionary, but keep in mind + in icinga isn't a deep merge.

**Comment by deric** [comment]
Sure, `vars = vars + config` is valid Icinga 2 code. The question is how to transfer Puppet variables (hashes) into icinga? When I write
```
vars + config + other_dictionary
```
where do I define the `other_dictionary`? From the example above `vars` are defined on the host (I can't pass custom variable to `Host` object) and `config` is basically a subset of the `vars` hash. For let's say service specific configuration I could define:
```ruby
{
  'hdd' => { 'sda': '/dev/sda' },
  'other_dictionary' => {'some' => 'value'}
}
```
and the write:
```puppet
apply => 'disk_name => config in host.vars.hdd',
vars  => 'vars + config + vars.other_dictionary',
```
so I'd merging a hash with itself. Is there a better way?

**Comment by lbetz** [comment]
I'm not sure but maybe you mean

vars => 'vars + config + host.vars.otherdirectory'

to use a dictionary out of a host context? But you've to use an apply rule.
