### ISSUE TITLE
example4 -> master zone missing?

### ISSUE THREAD

**Issue by linuxmail** [voxpupuli/puppet-icinga2#296]
Hello,

is it possible, that the from [example4](https://github.com/Icinga/puppet-icinga2/blob/master/examples/example4/profile/manifests/master.pp) the "master" zone and endpoint is missing?

**Comment by lbetz** [comment]
No, the zone exists.

  # Feature: api
  class { '::icinga2::feature::api':
    accept_commands => true,
    accept_config   => true,
  }

has a default zone and endpoint definition. The endpoint is the constant NodeName (default is the fqdn) and the zone is ZoneName set to 'master' thru the main class declaration.

  class { '::icinga2':
    manage_repo    => true,
    purge_features => false,
    confd          => false,
    constants      => {
      'ZoneName' => 'master',
    }
  }

**Comment by linuxmail** [comment]
Hi,

thanks for the explanation. In my case the master zone wasn't created because of my mixed setup tests.

cu denny
