### ISSUE TITLE
No way to specify an unmanaged CA file in api feature

### ISSUE THREAD

**Issue by waldiTM** [voxpupuli/puppet-icinga2#297]
``icinga2::feature::api`` insists in managing file resources with specified content for all certificate related files. This makes it impossible to make the class get the cert and key the specified way, but retrieve the CA list, which is solely used for authentication of the remote, another way or even use the system global CA list.

**Comment by bobapple** [comment]
Does setting `pki => none` help you?
You can also set custom sources for all certificates.

**Comment by waldiTM** [comment]
On Tue, May 09, 2017 at 12:01:14AM -0700, Blerim Sheqa wrote:
> Does setting `pki => none` help you?
> You can also set custom sources for all certificates.

No, that does not help.  It still wants to manage file resources for it.

**Comment by linuxmail** [comment]
hi @waldiTM 

I had the same issue, because I had to add a CA to the existing one. So I disabled the pki in my hiera file with:

`icinga2::feature::api::pki: 'none'`

and the file isn't touched anymore. Maybe you overwrite it elsewhere ?

**Comment by lbetz** [comment]
Set 
icinga2::feature::api::pki: 'none'
and use file resource with a tag 'icinga2::config::file' to manage all your file like key, cert, and cacert.
Or you can handle your key, cert, and cacert via base64 encoded strings in parameters ssl_key, ssl_cert, and ssl_cacert.

Same behavior for your class icinga2::pki::ca to manage a CA, i.e. on your master.
