### ISSUE TITLE
Learning: clustering - where are the host and service files

### ISSUE THREAD

**Issue by TinajaLabs** [voxpupuli/puppet-icinga2#301]
**current version of puppet-icinga2, puppet-icingaweb2,** 
**icinga2: v2.6.3**
**Icingaweb2: 2.4.1**
**redhat 6.7**

I'm trying to create a 2 layer master/client configuration (no satellite for now) and I'm getting the zones files created, but I notice that for all 3 setups (master, satellite, client) the setting to create conf.d is always false.

```
confd => false
```

In all my previous icinga2 installs it was all about conf.d and I included hosts, groups, users, and a dozen categories of service*.conf files with perhaps a hundred apply where definitions.  All the service definitions were hand written but the apply where syntax is brilliant.

I read some notes where it seems that what was in conf.d is now in folders under ```zones.d/``` but all I see there is the README.

How do we create, and where should the conf files exist for hosts and services in a system where we can use icinga as the client agent.

Any tips appriciated, thanks,
Chris.

**Comment by lbetz** [comment]
Hi Chris,

that's right. The example are for layer 3 setups. When you wanna setup a layer two you can use conf.d. The zones.d directory is used for auto sync of config to other zones like a satellite zone or maybe a agent. If you'd like to do an auto sync create a directory in zones.d with the name or zone as directory name and all files inside will transfer to this zone.
But in your setup this isn't required and so you still can use conf.d.

**Comment by TinajaLabs** [comment]
Thank you, @lbetz
