### ISSUE TITLE
Use puppet-blacksmith for module versioning and publishing

### ISSUE THREAD

**Issue by walterheck** [voxpupuli/puppet-icinga2#303]
Would it make sense to start using puppet-blacksmith for bumping versions and publishing to the forge? https://github.com/voxpupuli/puppet-blacksmith

Makes life a little easier :)

**Comment by bobapple** [comment]
@walterheck thank you. Fortunately life's not so hard currently, since we're using TravisCI to push automatically to the forge on each tag. I'll consider blacksmith if things get harder :)
