### ISSUE TITLE
Enhancement: add custom includes to icinga2.conf

### ISSUE THREAD

**Issue by TinajaLabs** [voxpupuli/puppet-icinga2#307]
I have 2 dirs I've added to ```/etc/icinga2```:
```
/etc/icinga2/tracks-available 
/etc/icinga2/tracks-enabled
```
It uses the same pattern as the ```features-available```, ```features-enabled``` in which enabled features are links to specifically available features.  (I've seen similar pattern in apache configs)

I have all my many tracks' hosts defined in *.conf files of tracks-available but for the specific monitoring server, I only link to the ones that are to be monitored.

It would be ever so useful to be able to add the features-enabled directory as a custom include in ```icinga2.conf```.  I see already the ability to add a custom conf.d directory in ```icinga2.conf.erb``` template.

For now, I will add another link in my conf.d directory that points to my ```tracks-enabled``` link. It's a little messy (I don't like links to links), but it should work for now.

Thanks,
Chris.

**Comment by bobapple** [comment]
Hi @TinajaLabs 

I agree that it makes sense to be able to include custom directories. There are also other scenarios I can think of: custom notification scripts, mix of static with dynamic configuration etc.

We'll consider this feature request for a future release, I'm not sure if we can make it for v1.3. We also should discuss if we need both, `include` and `include_recursive`.

Thank you

**Comment by lbetz** [comment]
You can do the following for your case: 

file { '/etc/icinga2/tracks-available':
  ensure => directory,
  ...
}
-> file { '/etc/icinga2/tracks-enabled':
  ensure => directory,
  tag       => 'icinga2::config::file',
  ...
}

file { '/etc/icinga2/tracks-enabled/A':
  ensure => link,
  tag       => 'icinga2::config::file',
  target   => '/etc/icinga2/tracks-available/A',
  ...
}

class { '::icinga2':
  ...
  confd => '/etc/icinga2/tracks-enabled',
}
