### ISSUE TITLE
Upgrade from puppet-icinga2-legacy

### ISSUE THREAD

**Issue by oryagel** [voxpupuli/puppet-icinga2#309]
Hi,
We're still using the legacy module. We would like to start using this module instead. Can we just change the module and everything will work? Are there any compatibility issues?

Thanks

**Comment by walterheck** [comment]
It won't work magically, took us quite a bit of refactoring to get it all working properly. Hope you have a proper test environment to make this work first :)

**Comment by lbetz** [comment]
Hi,
I am sorry but the modules aren't compatible. We did a complete rewrite and now we do some things completely different like the api handling. Many Parameters moved from the main class to the feature classes and renamed.

**Comment by oryagel** [comment]
Thanks!
