### ISSUE TITLE
ordering-api-with-pki-after-package

### ISSUE THREAD

**Issue by BrianAI** [voxpupuli/puppet-icinga2#311]
## Expected Behavior
I can configure a module that installs the icinga2 client, configures the zones and generates the PKI key / gets it signed.

## Current Behavior
I need to run the puppet module twice due to the pki generation trying before the icinga2 binary exists.

See here:

```Notice: Compiled catalog for [redacted] in environment staging in 3.47 seconds
Notice: /Stage[main]/Pp_icinga2::Client/Package[nagios-plugins-all]/ensure: created
Error: Could not find command 'icinga2'
Error: /Stage[main]/Icinga2::Feature::Api/Exec[icinga2 pki create key]/returns: change from notrun to 0 failed: Could not find command 'icinga2'
Notice: /Stage[main]/Icinga2::Install/File[/etc/icinga2]/ensure: created
Notice: /Stage[main]/Icinga2::Install/Package[icinga2]/ensure: created
```

On the second run, this works perfectly fine.  i've tried ordering with require, or -> and it errors out. here is my manifest:

```class pp_icinga2::client (
  `$icinga_master = '[redacted]'
  ) {

  package { 'nagios-plugins-all':
    ensure   => 'latest',
  }

  class { '::icinga2':
    manage_repo => true,
    confd     => false,
    features  => ['checker','mainlog'],
  }

  class { '::icinga2::feature::api':
    pki             => 'icinga2',
    ca_host         => $icinga_master,
    ticket_salt     => '[redacted]',
    accept_config   => true,
    accept_commands => true,
    endpoints       => {
      'NodeName'     => {},
      $icinga_master => {}
    },
    zones           => {
      'ZoneName' => {
        'endpoints' => ['NodeName'],
        'parent'    => 'master',
      },
      'master'      => {
        'endpoints' => [$icinga_master],
      }
    },
  }
}
```

Thanks!! :)

**Comment by lbetz** [comment]
I don't know why but the ordering of your puppet run is wrong. The packages['icinga2'] resource has to be apply before creating the cert request with the command icinga2. What kind of os or distribution you used?

**Comment by BrianAI** [comment]
We use centOs 6/7, and puppet 3 ( latest version available) and I should note I've tried to force ordering (since I saw the same issue in the output up top) but that just causes a dependency loop :(

**Comment by lbetz** [comment]
Ok strange. I have to tested with puppet 3 again.

**Comment by lbetz** [comment]
It's an ordering problem with puppet 3. I hope I can fix it in the evening (UTC+2) today.

**Comment by BrianAI** [comment]
Great!  Thanks for checking it out :) look forward to it

**Comment by lbetz** [comment]
merge to master.
