### ISSUE TITLE
strings get parsed strangely for services

### ISSUE THREAD

**Issue by mjm1138** [voxpupuli/puppet-icinga2#317]
## Expected Behavior
Here's my puppet code:

```
  @@icinga2::object::service {"${::fqdn}_mysql_longqueries":
    target           => "/etc/icinga2/conf.d/services/${::fqdn}.conf",
    host_name        => $::fqdn,
    import           => ['generic-service'],
    check_command    => 'check_mysql_query',
    command_endpoint => $::fqdn,
    vars             => {
      'percona_check_user'     => hiera('percona_check_user'),
      'percona_check_password' => hiera('percona_check_password'),
      'mysql_check_query'      => 'select count(1) from information_schema.processlist where command<>\'sleep\' and time > 120',
      'mysql_query_warn'       => '0',
      'mysql_query_crit'       => '0',
    },
  }
```

## Current Behavior
Here's the code that gets generated on the server:

```
object Service "<redacted>net_mysql_longqueries"  {
  import "generic-service"

  host_name = "<redacted>.net"
  check_command = "check_mysql_query"
  command_endpoint = "<redacted>.net"
  vars.mysql_query_crit = 0
  vars.mysql_query_warn = 0
  vars.mysql_check_query = select count("*) from information_schema.processlist where command<>'sleep' and time > 120"
  vars.percona_check_user = "<redacted>"
  vars.percona_check_password = "<redacted>"
}
```
Note that it is inserting a double quote after the first paren in the query string rather than at the beginning of the string.  I am at a loss to explain it.  Does it have to do with "auto quoting"?  Any guidance would be welcome, thanks.

## Your Environment

* Module version (`puppet module list`): icinga-icinga2 (v1.2.1)
* Puppet version (`puppet -V`): 4.10.0
* Operating System and version: Ubuntu 14.04.5 LTS

**Comment by lbetz** [comment]
We wanted to implement just a simple parser but it grew over time. Problem is here the () expression. You can disable the parser with -: in the front of a value. That mean you've to do quoting by yourself like
vars.mysql_check_query => '-:select count(1) from information_schema.processlist where command<>\'sleep\' and time > 120'
I hope or
vars.mysql_check_query => '-:select count(1) from information_schema.processlist where command<>"sleep" and time > 120'
or
vars.mysql_check_query => "-:select count(1) from information_schema.processlist where command<>'sleep' and time > 120"

**Comment by lbetz** [comment]
Sorry to fast....
vars.mysql_check_query => '-:"select count(1) from information_schema.processlist where command<>\'sleep\' and time > 120"'
But I'm not sure how to quote correctly...

**Comment by mjm1138** [comment]
Ah, thank you, that solves it!  For reference, here's what I'm using:

```
'mysql_check_query'      => '-:"select count(*) from information_schema.processlist where command<>\'sleep\' and time > 120"',
```

Regards,
-Mike
