### ISSUE TITLE
RedHat not supported for puppet 3.x

### ISSUE THREAD

**Issue by BrianAI** [voxpupuli/puppet-icinga2#320]
## Expected Behavior
I should be able to install icinga2 client in redhat (against puppet 3.x)

## Current Behavior
I get the following error when trying to apply:

```
 error during compilation: Evaluation Error: Error while evaluating a Function Call, Your plattform RedHat is not supported, yet. at /home/jenkins-slave/workspace/puppet/servers/spec/fixtures/modules/icinga2/manifests/params.pp:193:7 on node lga-puppetbuild01.pulse.prod
```

## Possible Solution
I believe this is caused by a  case sensitivity:
```
RedHat is not supported, yet.
```

```
case $::osfamily {
        'redhat': {
          $user    = 'icinga'
          $group   = 'icinga'
          $lib_dir = $::architecture ? {
            'x86_64' => '/usr/lib64',
            default  => '/usr/lib',
          }
        } # RedHat

```

**Comment by lbetz** [comment]
Matches are case-insensitive. Did you test it?

**Comment by lazyfrosch** [comment]
What version of Puppet and Ruby is that?

**Comment by BrianAI** [comment]
My apologies, this was a fault of ours.  We were using test machines and didn't stub kernel fact.  Closing.

Again, sincerest apologies.
