### ISSUE TITLE
icinga2::feature::api defaults to literal "TicketSalt" string when using pki=icinga2

### ISSUE THREAD

**Issue by lesinigo** [voxpupuli/puppet-icinga2#324]
I had problems letting nodes get their certificates using `pki='icinga2'`, after some debugging I traced them down to the `icinga2_ticket_id()` code using the literal string "TicketSalt" to generate the ticket on the puppet server.

I was setting my ticket salt in my profile like this on all my master nodes:
```puppet
  class { '::icinga2':
    confd       => false,
    manage_repo => false,
    features    => [....],
    constants   => {
      'TicketSalt' => $ticketsalt,
      'ZoneName'   => 'master',
    },
  }
```
...and I left `icinga2::feature::api::ticket_salt` at the default value, which comments in the code say "_Defaults to icinga2 constant TicketSalt_".

The end result is that the "main" Icinga2 master, which has the CA and is signing certificates, is using the _value of the TicketSalt constant_ to internally calculate tickets, but on the other hand when Puppet code is running for a "secondary" master which must get a signed certificate, it is passing the literal `TicketSalt` string to `icinga2_ticket_id()`, ends up getting a different `ticket_id`, failing to request a signed certificate.

As a workaround, setting the ticket explicitly (through Hiera, in my case) fixed everything:
```yaml
  icinga2::feature::api::ticketsalt: 'my_secret_salt'
```

In addition to my actual issue, if I understood everything correctly, only the _certificate signing node_ should have the TicketSalt in Icinga2 on-disk configuration, while every other node just needs it once at runtime when requesting a signed certificate from the former. If this is correct, the current `icinga2::feature::api` implementation is not able to use the `TicketSalt` to request the certificate without also persisting it in `/etc/icinga2/features-available/api.conf` in the end node.

I'd suggest to clarify the documentation about the need to pass the actual ticket salt to `icinga2::feature::api` if one wants to leverage `pki='icinga2'` and, if I am correct in my reasoning above, to find a way to not persist the salt in the on-disk configuration if it's not needed.

**Comment by lbetz** [comment]
Sorry what's your point? Storing the ticket_salt value in api.conf on other nodes than the ca master is a bug of course. Do you have other points?

**Comment by lbetz** [comment]
#325

**Comment by lesinigo** [comment]
The current description of `icinga2::feature::api` parameters and assorted documentation, and the way the other features are managed in this module, seems pretty coherent and to me sounds like "use this puppet parameter to tune the corresponding one in `/etc/icinga2/features-*/api.conf`".

If that's the case, I would personally keep that parameter to save settings in conf file and use a different one to provide data for `icinga2_ticket_id()` when used within the context of `pki="icinga2"`.
If you agree with this I could put together a PR in the next days.

Keeping the current, single, parameter for both scenarios (CA-node --> persist to on-disk configuration, non-CA-node --> use at runtime for `icinga2_ticket_id() ) would IMHO generate some confusion to users.

**Comment by lbetz** [comment]
We should use a dedicated parameter, I think.

**Comment by lbetz** [comment]
#325
