### ISSUE TITLE
puppet 5

### ISSUE THREAD

**Issue by ghost** [voxpupuli/puppet-icinga2#327]
Any plans to support Puppet 5?

**Comment by lazyfrosch** [comment]
Do you have tested it? Should work.

**Comment by ghost** [comment]
No I haven't tested it. I was just wondering because the specification at
puppet forge didn't include Puppet 5

**Comment by lazyfrosch** [comment]
@noobcontrol a lot of modules don't have that yet, see #330 for our first tests

**Comment by ghost** [comment]
Seems to work with Puppet 5.
