### ISSUE TITLE
Safe tag is not safe enough

### ISSUE THREAD

**Issue by kaprizki** [voxpupuli/puppet-icinga2#335]
## Expected Behavior

Create exported resource on a client:
```
    @@icinga2::object::host { $instance_id:
      import        => ['generic-host'],
      display_name  => $display_name,
      vars          => {
        'os'  => $::kernel
      },
      address       => $facts['networking']['ip'],
      address6      => '::1',
      target        => "/etc/icinga2/zones.d/${instance_id}/${instance_id}.conf']",
      notify        => Service['icinga2']
    }
````
Collect resource on the master:

```
Icinga2::Object::Host <<| |>>
```
Run puppet on client, then master. Expect file /etc/icinga2/zones.d/i-08cb83418219625ea/i-08cb83418219625ea.conf created with node definition.

## Current Behavior

run on the master fails with the error:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Invalid tag '_etc_icinga2_zones.d_i-08cb83418219625ea_i-08cb83418219625ea.conf']' at /etc/puppetlabs/code/environments/COK_556/modules/concat/manifests/init.pp:84 at /etc/puppetlabs/code/environments/COK_556/modules/icinga2/manifests/object.pp:135 on node i-03c2fb7f218b3758c
Warning: Not using cache on failed catalog
```

## Possible Solution

When safe tag is created the `.` needs to be replaced with `_` since `.` is not a valid symbol in tags. So line below needs to be adjusted.

file /etc/puppetlabs/code/environments/COK_556/modules/concat/manifests/init.pp:84
$safe_name            = regsubst($name, '[/:~\n\s\+\*\(\)@]', '_', 'G')

## Steps to Reproduce (for bugs)

1. Explained in the expected behavior. 

## Context

Trying to build icinga distributed configuration using this module.

## Your Environment

* Module version (`puppet module list`):
* Puppet version (`puppet -V`):
* Operating System and version:

**Comment by lbetz** [comment]
First you doesn't need to send a notify to the icinga2 service. This is handled by the module automatically.

Snippet from https://docs.puppet.com/puppet/5.0/lang_reserved.html#tags:
Tag names should match the following regular expression:
\A[a-z0-9_][a-z0-9_:\.\-]*\Z

And you're using two unallowable signs ' and ] at the end of the String.
-> target => "/etc/icinga2/zones.d/${instance_id}/${instance_id}.conf']",

These signs aren't validated for file paths, too.
