### ISSUE TITLE
Example and documentation for syncing hiera data to icinga objects

### ISSUE THREAD

**Issue by yaron-idan** [voxpupuli/puppet-icinga2#342]
## Expected Behavior
We have been using the puppet-icinga2-legacy module for a while now, and are in the process of upgrading to this module. We've been using the `icinga2::objects` class to sync between hiera and our icinga2 server, and it's been working great for us so far. Here's a link to the feature I'm referring to - https://github.com/Icinga/puppet-icinga2-legacy#hiera
## Current Behavior
Currently, it seems this module doesn't contain this module, and we've been wondering why.
## Possible Solution
Adding the `icinga2::objects` class into this module, or any other class with similar functionality that will allow hiera data to be synced with icinga2.
## Context
This breaks our current flow for creating icinga2 objects, which allowed us to empower every dev member in our team to easily monitor his/hers services.

**Comment by lbetz** [comment]
We do less is more in this module. When you wanna have the same behavior do it on your on at your profile layer. Use the create_resource function for puppet 3 or the iteration in puppet 4.

**Comment by yaron-idan** [comment]
What about reusing the objects class that was present in the legacy module? Should it work out of the box if I point it at the object classes of the new module or was it removed for a specific reason and isn't compatible with the current module?
Thanks.

**Comment by yaron-idan** [comment]
When using iterations like suggested in this issue I've encountered some strange behavior -
The following hiera document -
```
{
   "icinga2::object::dependency":{
      "internet_to_host":{
        "assign":["host.name != \"Yahoo\" && host.name != \"icinga2-win1\""],
        "parent_host_name":"Yahoo",
        "disable_checks":true,
        "disable_notifications":true,
        "apply_target": "Host",
        "apply": true
      }
}
```
Is being transformed into the following icinga object - 
```
# This file is managed by Puppet. DO NOT EDIT.

apply Dependency "internet_to_host" to Host {
  parent_host_name = "Yahoo"
  disable_checks = true
  disable_notifications = true
  assign where host.name != ""Yahoo"" && host.name != ""icinga2-win1""
}
```
I figured something is wrong with the way we are escaping the string, but eventually I found out the extra quotes are being added by the icinga2::object::<resource> class. 
When I remove the quotes entirely, the file is created as expected, with a double quote around each string in the assign clause.
This behavior is unexpected and is not consistent with the way we modeled our data when using the legacy module.
Why was this change introduced?

**Comment by lbetz** [comment]
That’s not strange, it’s the expected behavior.

Use:
["host.name != Yahoo && host.name != icinga2-win1"]
The parser decides what elements to be quoted.


> Am 16.08.2017 um 17:23 schrieb Yaron Idan <notifications@github.com>:
> 
> ["host.name != \"Yahoo\" && host.name != \"icinga2-win1\""]

**Comment by lbetz** [comment]
have a look at the documentation to Object Config, Parsing Configuration.

**Comment by yaron-idan** [comment]
True, I've missed that part of the docs, thanks for the reference.
I'm building a new version of the missing objects class to fit our use case, would you be interested in adding it to this module or are you keen on keep doing more with less?
I find it's nice to have a way of syncing hiera and icinga, and since the old module supported this I don't see why the new one shouldn't.

**Comment by lbetz** [comment]
Inspired by you I wrote a blog post. It's in german sorry for that but the code say it all, I think.

https://blog.netways.de/2017/08/18/icinga-2-monitoring-automatisiert-mit-puppet-teil-5-konfiguration-ii/

I will write an example and a short documentation.

**Comment by bobapple** [comment]
I agree with @lbetz, adding an example and docs is sufficient. Thanks for the effort @yaron-idan
