### ISSUE TITLE
/etc/apt/sources.list.d entry for sources, too

### ISSUE THREAD

**Issue by ghost** [voxpupuli/puppet-icinga2#343]
Hi,

it would be cool to have the option to install the 

/etc/apt/sources.list.d 

file with the URL for the source as well.

At the moment it's not possible to get the Icinga 2 source with

apt-get source icinga2

because there is not apt sources file and/or entry.

**Comment by ghost** [comment]
Or just add the source URL by default as well. Shouldn't be harmful.

**Comment by lbetz** [comment]
If you like to manage the source manage the repos on your own. The source tree isn't needed by this module.
