### ISSUE TITLE
icinga2 service won't start when enable_ssl = false

### ISSUE THREAD

**Issue by yaron-idan** [voxpupuli/puppet-icinga2#344]
## Expected Behavior
Configuring the ido feature should allow the icinga2 service to start successfully.

## Current Behavior
When configuring the ido feature with this module, the icinga2 service fails to start with this error log (produced with the `service icinga2 status` command - 
```
● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/lib/systemd/system/icinga2.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-07-31 11:17:14 IDT; 15s ago
  Process: 9162 ExecReload=/usr/lib/icinga2/safe-reload /usr/lib/icinga2/icinga2 (code=exited, status=1/FAILURE)
  Process: 9869 ExecStart=/usr/sbin/icinga2 daemon -e ${ICINGA2_ERROR_LOG} (code=exited, status=1/FAILURE)
  Process: 9784 ExecStartPre=/usr/lib/icinga2/prepare-dirs /usr/lib/icinga2/icinga2 (code=exited, status=0/SUCCESS)
 Main PID: 9869 (code=exited, status=1/FAILURE)

Jul 31 11:17:14 Icinga2-master icinga2[9869]: /etc/icinga2/features-enabled/ido-mysql.conf(13):   enable_ha = true
Jul 31 11:17:14 Icinga2-master icinga2[9869]: /etc/icinga2/features-enabled/ido-mysql.conf(14):   failover_timeout = 60s
Jul 31 11:17:14 Icinga2-master icinga2[9869]: /etc/icinga2/features-enabled/ido-mysql.conf(15):   enable_ssl = false
Jul 31 11:17:14 Icinga2-master icinga2[9869]:                                                     ^^^^^^^^^^^^^^^^^^
Jul 31 11:17:14 Icinga2-master icinga2[9869]: /etc/icinga2/features-enabled/ido-mysql.conf(16): }
Jul 31 11:17:14 Icinga2-master icinga2[9869]: /etc/icinga2/features-enabled/ido-mysql.conf(17):
Jul 31 11:17:14 Icinga2-master icinga2[9869]: [2017-07-31 11:17:14 +0300] critical/config: 1 error
Jul 31 11:17:14 Icinga2-master systemd[1]: icinga2.service: Main process exited, code=exited, status=1/FAILURE
Jul 31 11:17:14 Icinga2-master systemd[1]: icinga2.service: Unit entered failed state.
Jul 31 11:17:14 Icinga2-master systemd[1]: icinga2.service: Failed with result 'exit-code'.
```

## Possible Solution
Removing enable_ssl from the default configuration seems to solve the issue

## Steps to Reproduce (for bugs)
1. running on a fresh Ubuntu 16.04, configured as a puppet agent (v2016.4.2)
2. Applying the following class - https://gist.github.com/yaron-idan/de67d1aeb8fcc86d803c8a7864777460

## Context
This issue is blocking icinga2 from starting when configured with this puppet module
## Your Environment
* Module version : v1.3.0 
* Puppet version (`puppet -V`):4.7.0
* Operating System and version: Ubuntu 16.04.2 LTS

**Comment by lbetz** [comment]
Works the example init_idomysql.pp from the directory examples?

**Comment by lazyfrosch** [comment]
This is likely an old Icinga 2 version, which does not support the parameter...

**Comment by yaron-idan** [comment]
That's true, my class did not use `manage repo => true`, which probably resulted in installing an older version. Thanks for the help, it works now.
