### ISSUE TITLE
Puppet 3 Support/Data type

### ISSUE THREAD

**Issue by baurmatt** [voxpupuli/puppet-icinga2#345]
This is a question regarding the Puppet 3 support. I'm currently implementing our new Icinga setups and realized that i have to improve the performance of the icinga2::object* classes dramatically to get a compile time within a acceptable time frame. After doing some testing i realized that I could get a 30%-50% improvement by switching to native data types instead of the validate_* functions.

What is you plan for this module regarding Puppet 3 support? Are you willing to drop it (or at least move it to a separate branch?

I like the idea of Vox Pupuli how to handle this: https://voxpupuli.org/blog/2016/12/22/putting-down-puppet-3/

**Comment by baurmatt** [comment]
Tests also show that the defined() function is really slow and shouldn't be used in classes which could get included into the catalog hundreds/thousands of times.

**Comment by bobapple** [comment]
Refer to : 
* https://github.com/Icinga/puppet-icingaweb2/issues/164
* https://github.com/Icinga/puppet-icinga2/pull/362
