### ISSUE TITLE
undefined method `keys' for []:Array at /config.pp:26

### ISSUE THREAD

**Issue by josy1024** [voxpupuli/puppet-icinga2#348]
try to basic setup puppet-icinga2 and get an syntax error:
undefined method `keys' for []:Array at /etc/puppet/modules/icinga2/manifests/config.pp:26 

```
  class { '::icinga2':
    manage_repo => true,
  }

config.pp:
 if $::kernel != 'windows' {
    $template_constants  = icinga2_attributes($constants)
    **$template_mainconfig = template('icinga2/icinga2.conf.erb')**
  } else {
    $template_constants  = regsubst(icinga2_attributes($constants), '\n', "\r\n", 'EMG')
    $template_mainconfig = regsubst(template('icinga2/icinga2.conf.erb'), '\n', "\r\n", 'EMG')
  }
```

## Expected Behavior
should run and do setup without errors

## Current Behavior
currently not doing anything cause of syntax error.

## Possible Solution
changed depecies to met requirements for centos7 and puppet 3.8.7

## Steps to Reproduce (for bugs)
new setup new client within old puppet 3.8.7 environment

## Your Environment
* Puppet version (`puppet -V`): 3.8.7
* Operating System and version: centos7 release 7.3.1611
* Module version (`puppet module list`):

/etc/puppet/modules
├── apple (???)
├── cloudscripts (???)
├── cprice404-inifile (v0.0.3)
├── dnscache (???)
├── example42-monitor (v2.0.1)
├── example42-puppi (v2.1.0)
├── guglerfirewall (???)
├── guglerftpserver (???)
├── guglermonitoring (???)
├── guglerpuppet (???)
├── guglerssh (???)
├── guglerunix (???)
├── guglervpn (???)
├── icinga-icinga2 (v1.2.1)
├── ldapserver (???)
├── mcollectivedisable (???)
├── mysql-proxy (???)
├── network (???)
├── nginx (???)
├── ossec (???)
├── php_harden (???)
├── publicip (???)
├── puppetlabs-concat (v2.2.1)
├── puppetlabs-mysql (v3.11.0)
├── puppetlabs-puppetdb (v1.1.2)
├── puppetlabs-stdlib (v4.17.0)
├── puppetmanaged-puppet (v0.5.0-1)
├── pzs (???)
├── typo3 (???)
├── wget (???)
└── windows (???)

**Comment by lbetz** [comment]
please checkout #267
