### ISSUE TITLE
Update documentation about += operator

### ISSUE THREAD

**Issue by baurmatt** [voxpupuli/puppet-icinga2#352]
## Expected Behavior
Generate a configuration like this with Puppet:

```
apply Service for (http_vhost => config in host.vars.http_vhosts) to Host {
  import "generic-service"

  check_command = "http"

  vars += config
}
```

The `vars += config` part is the part i'm missing.

## Current Behavior
As stated in https://github.com/Icinga/puppet-icinga2/blob/master/README.md#what-isnt-supported this is currently not possible as the icinga2_attributes/Puppet::Icinga2::Utils.attributes function doesn't support it.

## Possible Solution
Fix icinga2_attributes/Puppet::Icinga2::Utils.attributes

I suggest a solution like this:

```puppet
icinga2::object::service { 'foo-service':
  ...
  vars => {
    '+=' => 'config'
  },
  ...
}
```

Do you already have talked about this internally? Was where already some playing around with this feature/idea?

## Your Environment

* Module version (`puppet module list`): Forked master with enhancements
* Puppet version (`puppet -V`): 4.10.1
* Operating System and version: Ubuntu 16.04

**Comment by baurmatt** [comment]
From documentation of icinga2::object::service (https://github.com/Icinga/puppet-icinga2/blob/master/manifests/object/service.pp#L152)
```
#   ::icinga2::object::service { 'linux_disks':
#     import           => ['generic-service'],
#     apply            =>  'disk_name =>config in host.vars.disks',
#     check_command    => 'disk',
#     command_endpoint => 'host.name',
#     vars             => 'vars + config',
#     assign           => ['host.vars.os == Linux'],
#     ignore           => ['host.vars.noagent'],
#     target           => '/etc/icinga2/zones.d/global-templates/services.conf',
#   }
```

Does this actually work? This would generate a configuration like this:

```
...
vars = vars + config
...
```

Is this the same as?

```
...
vars += config
...
```

**Comment by lbetz** [comment]
Correct. vars += config is the short syntax for vars = vars + config. Both is correct Icinga syntax. The module supports only the long version.

**Comment by baurmatt** [comment]
Ha, alright this was easier then i thought. Thanks! :) Could this please be documented? Perhaps somewhere around https://github.com/Icinga/puppet-icinga2/blob/master/README.md#parsing-configuration? Because the following sounds like its just not possible:

> Assignments other than simple attribution are not currently possible either, e.g. building something like
>``` vars += config ```
>
