### ISSUE TITLE
Ruby error in lib/puppet/parser/functions/icinga2_attributes.rb

### ISSUE THREAD

**Issue by ghost** [voxpupuli/puppet-icinga2#359]
## Current Behavior
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to parse template icinga2/object.conf.erb:
  Filepath: /etc/puppet/environments/infra_dev_vm/modules/icinga2/lib/puppet/parser/functions/icinga2_attributes.rb
  Line: 5
  Detail: Must provide at least one argument.
 at /etc/puppet/environments/infra_dev_vm/modules/icinga2/manifests/object.pp:131 on node icinga2-master.local.gfk.de
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

## Steps to Reproduce
* download, place module in modules/, call class {‘icinga2’ }
```
 class { '::icinga2':
    manage_repo  => true,
    plugins      => [ 'plugins', 'plugins-contrib' ],
    constants => {
      'ZoneName' => 'master',
    },
  }
```

## Context
* Right now I use Version 1.1.1 of icinga2 puppetmodule
* I wanted to test the latest stable version 1.3.0

## Your Environment

* Module version:
 puppetlabs-concat (v2.1.0)
 puppetlabs-stdlib (v4.11.0)
 icinga-icinga2 (v1.3.0)
* Puppet version: 3.8.7
* Operating System and version: CentOS 7

**Comment by lazyfrosch** [comment]
Hey @qaunz,
this sounds like an ordering problem we've seen before #232 

When you define a resource, before actually including `icinga2` this can break.

Not sure where our include is missing.

**Comment by lbetz** [comment]
Sounds like a caching problem. We changed the number of arguments for this function. If you update to a new Version, all puppet master must be restarted.

**Comment by ghost** [comment]
Problem does not occur anymore after restart. So @lbetz seems to be right. Thank you and closing.
