### ISSUE TITLE
adapt for new mail notification script as of icinga >=v2.7.0

### ISSUE THREAD

**Issue by mika** [voxpupuli/puppet-icinga2#361]
With icinga v2.7.0 notifications per mail are broken if the changes as documented at https://github.com/Icinga/icinga2/commit/bd7d7ef84560f250aa6bccb8393a945d61783fd1 + https://www.icinga.com/2017/08/23/advisory-for-icinga-2-v2-7-update-and-mail-notification-scripts/ aren't applied.

**Comment by bobapple** [comment]
The mentioned changes are problematic when updating Icinga 2. I don't see how we could catch this with the Puppet module, can you give some more details about the changes you request?

**Comment by lbetz** [comment]
We only manage icinga2 objects not the content of an object. You have to mange the content on your own.

**Comment by mika** [comment]
Well, the provided example config is broken with >2.7.0 AFAICS: https://github.com/Icinga/puppet-icinga2/blob/f9165ba556a3c2d9713fb17c0932b0cc81aa3927/examples/example_config.pp#L223

**Comment by lbetz** [comment]
But it is just an example....
