### ISSUE TITLE
Updated to support puppetlabs/chocolatey 3.0.0?

### ISSUE THREAD

**Issue by cristianbalan-mf** [voxpupuli/puppet-icinga2#363]
https://forge.puppet.com/puppetlabs/chocolatey/changelog#2017-06-02-supported-release-300
Should probably work with no changes needed but it would be great to fix the dependency doc then.

**Comment by lbetz** [comment]
We will implement this in our next major release when puppet3 support will be dropped.

**Comment by cristianbalan-mf** [comment]
Thanks @lbetz . Is there a deadline for that?

**Comment by lbetz** [comment]
Not yet. We're working on a roadmap.

**Comment by lbetz** [comment]
chocolatey 3.0.0 requires puppet >= 4.7.0

**Comment by cristianbalan** [comment]
Is puppet-icinga2 still supporting Puppet 3?

**Comment by cristianbalan-mf** [comment]
Is puppet-icinga2 still supporting Puppet 3? Many modules dropped already their support to it including puppetlabs/concat and puppetlabs/apt which you depend on.

**Comment by lbetz** [comment]
We will release v1.3.1 still have puppet3 support in a few days. With the coming v2.0.0 we'll remove this support.

**Comment by lbetz** [comment]
refs #476
