### ISSUE TITLE
Ruby Error in lib/puppet_x/icinga2/utils.rb. Its an Array not a Hash! 

### ISSUE THREAD

**Issue by ghost** [voxpupuli/puppet-icinga2#364]
On a fresh puppet run with icinga2 using Puppet 3.8 I get

```
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: undefined method `keys' for []:Array at /etc/puppet/environments/infra_dev_vm/modules/icinga2/manifests/config.pp:27 on node icinga2-master.local
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

The class is defined as follows

```
  class { '::icinga2':
    manage_repo  => true,
    confd        => 'local.d',
    features     => ['checker','mainlog','notification','statusdata','compatlog','command','perfdata',],
    plugins      => [ 'plugins', 'plugins-contrib' ],
    constants 	 => {
      'ZoneName' => 'master',
    },
  }
```

## Expected Behavior

It works :) 

## Current Behavior

It seems that somehow the Hash of $constants and $::icinga::constants are being mixed and merged within lib/puppet_x/icinga2/utils.rb. At the end, $constants are not a Hash anymore. Suddenly they are an Array..

## Possible Solution

Lets look at icinga2_attributes function...

```
require File.join(File.dirname(__FILE__), '../../..', 'puppet_x/icinga2/utils.rb')

module Puppet::Parser::Functions
  newfunction(:icinga2_attributes, :type => :rvalue) do |args|
    raise Puppet::ParseError, 'Must provide at least one argument.' if args.length > 4

    if args[1]
      indent = args[1]
    else
      indent = 0
    end

    if args[2]
      globals = args[2].concat(lookupvar('::icinga2::params::globals'))
    else
      globals = lookupvar('::icinga2::params::globals')
    end

    if args[3]
      constants = args[3].merge(lookupvar('::icinga2::_constants'))
    else
      constants = lookupvar('::icinga2::_constants')
    end

    Puppet::Icinga2::Utils.attributes(args[0], globals, constants, indent)
  end
end
``` 

See last line where contstants and globals are being filled in Utils Wrapper. Within this file, it fails somewhere around here.

```
        # globals (params.pp) and all keys of attrs hash itselfs must not quoted
        $constants = globals.concat(consts.keys) << "name"

        # select all attributes and constants if there value is a hash
        $hash_attrs = attrs.merge(consts).select { |x,y| y.is_a?(Hash) }.keys
``` 

Breakdown of the error:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to parse template icinga2/object.conf.erb:
  Filepath: /etc/puppet/environments/infra_dev_vm/modules/icinga2/lib/puppet/parser/functions/../../../puppet_x/icinga2/utils.rb
  Line: 203
  Detail: undefined method `keys' for []:Array
 at /etc/puppet/environments/infra_dev_vm/modules/icinga2/manifests/object.pp:131 on node icinga2-master.local.gfk.de
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

## Steps to Reproduce (for bugs)

Use icinga2 with puppet 3.8

## Your Environment

* Module version:
 puppetlabs-concat (v2.1.0)
 puppetlabs-stdlib (v4.11.0)
 icinga-icinga2 (v1.3.0)
* Puppet version: 3.8.7
* Ruby version: 2.0.0
* Operating System and version: CentOS 7

**Comment by lbetz** [comment]
What kind of a ruby version is used on your master? See #267

**Comment by ghost** [comment]
My master uses ruby version 1.8.7. But the ruby plugins are running on the client, so there should be no dependencies with the master's version, or?

**Comment by lbetz** [comment]
But functions are running on the master only.

**Comment by rudexi** [comment]
@qaunz Thanks for troubleshooting it saved me a lot of time.

Since the functions are running on the master, the `Hash.select` of ruby 1.8 returns an Array, while in ruby >1.9, it returns a Hash.

I believe the icinga2 module won't support 1.8 (too much effort to do).

If  you're in the same situation as me and want to patch it regardless, you can use the following trick described here:
https://bibwild.wordpress.com/2012/04/12/ruby-hash-select-1-8-7-and-1-9-3-simultaneously-compatible/

Here is the change in details:
```
+++ b/modules/icinga2/lib/puppet_x/icinga2/utils.rb
@@ -209 +209 @@ module Puppet                                                    
-        $hash_attrs = attrs.merge(consts).select { |x,y| y.is_a?(Hash) }.keys      
+        $hash_attrs = Hash[attrs.merge(consts).select { |x,y| y.is_a?(Hash) }].keys
```
