### ISSUE TITLE
Icinga2 binary not found on Debian and FreeBSD

### ISSUE THREAD

**Issue by cfoehrdes** [voxpupuli/puppet-icinga2#371]
Currently the icinga2 binary is not found on Debian jessie. Caused by the changes merged with PR #369 which sets `$bin_dir = '/sbin'` for all Linux distributions but the binary is located in `/usr/sbin`.

This results in errors like:

```
Error: Could not find command 'icinga2'
Error: /Stage[main]/Icinga2::Feature::Api/Exec[icinga2 pki create key]/returns: change from 'notrun' to ['0'] failed: Could not find command 'icinga2'
```

**Comment by lbetz** [comment]
Thx. Has to be done for Suse and FreeBSD, too.

**Comment by cfoehrdes** [comment]
Are you on it? If you want I can submit a PR

**Comment by lbetz** [comment]
yes, I'm working on it. But I donno the path of icinga2 on freebsd?

**Comment by cfoehrdes** [comment]
Sorry, no idea what it is on BSD

**Comment by lbetz** [comment]
done. pr ##372
