### ISSUE TITLE
apt-key keeps getting refreshed on Debian

### ISSUE THREAD

**Issue by hboetes** [voxpupuli/puppet-icinga2#373]
On Debian 9 strech when I run puppet I notice that the icinga repo key is getting updated:

```
Notice: /Stage[main]/Icinga2::Repo/Apt::Source[icinga-stable-release]/Apt::Key[Add key: F51A91A5EE001AA5D77D53C4C6E319C334410682 from Apt::Source icinga-stable-release]/Apt_key[Add key: F51A91A5EE001AA5D77D53C4C6E319C334410682 from Apt::Source icinga-stable-release]/ensure: created
```

But it's already installed!

```
pub   dsa1024 2013-11-16 [SC]
      F51A 91A5 EE00 1AA5 D77D  53C4 C6E3 19C3 3441 0682
uid           [ unknown] Icinga Open Source Monitoring (Build server) <info@icinga.org>
sub   elg2048 2013-11-16 [E]
```

Just to double check I removed the key and then ran puppet agent -t again, twice. But still the key is reinstalled even though it's already there.

This doesn't happen on ubuntu xenial systems nor on OpenBSD systems.

**Comment by baurmatt** [comment]
Sounds like a bug in http://github.com/puppetlabs/puppetlabs-apt. Which version do you use?

**Comment by hboetes** [comment]
You're right, I had to git pull to get this fix:
https://github.com/puppetlabs/puppetlabs-apt/pull/665/files
