### ISSUE TITLE
Objects created but not removed

### ISSUE THREAD

**Issue by yaron-idan** [voxpupuli/puppet-icinga2#375]
## Expected Behavior
When removing an object resource, the object should be removed from icinga2
## Current Behavior
When removing an object resource, it stays in icinga2 unless it's explicitly instructed to `ensure => absent` for this resource.
## Possible Solution
The legacy module used to support this behavior, I wonder if there is a way to add this as an optional behavior in this module as well (or perhaps just supply a reference to the way the old module did that)
## Steps to Reproduce (for bugs)

1. create an object (the example host object from the documentation works just fine)
2. Make sure puppet creates the icinga2 host
3. Remove the object from the configuration
4. The host stays in icinga2

## Context
This breaks our current flow of using puppetcode to reflect the current desired state of icinga, and forces us to add an `ensure => present/absent` to all of our configurations.
## Your Environment
* Module version : v1.3.0
* Puppet version (puppet -V):4.7.0
* Operating System and version: Ubuntu 16.04.2 LTS

**Comment by lbetz** [comment]
All objects are stored in files, exactly in concat resources. When you remove a object resource from your code it is also removed from the concat resource if there is at least one object to this concat resource. In this case puppet has the problem to know that this object/concat resource isn't managed anymore because the resource is also gone.

**Comment by lbetz** [comment]
Using a directory resource for your config with purge => true, recurse => true should solve this problem.

**Comment by yaron-idan** [comment]
This solved my problem indeed. Thanks for the quick reply!

**Comment by lbetz** [comment]
You're welcome.
