### ISSUE TITLE
document manage_package with manage_repo

### ISSUE THREAD

**Issue by baurmatt** [voxpupuli/puppet-icinga2#381]
The docs state that the following code should be used if you want to specify the package version as the icinga2 module doesn't allow it.

```puppet
package { 'icinga2':
  ensure => latest,
  notify => Class['icinga2'],
}

class { '::icinga2':
  manage_package => false,
}
```

## Expected Behavior
Using the above code and adding `manage_repo => true` for the icinga class one would expect that Puppet installs the package from the icinga2 repository.

## Current Behavior
[This](https://github.com/syseleven/puppet-icinga2/blob/master/manifests/repo.pp#L21) line disables the repository management silently if `manage_packages = false` even though `manage_repo = true`
```puppet
  if $::icinga2::manage_repo and $::icinga2::manage_package {
```

## Possible Solution
1. First solution:
```diff
-  if $::icinga2::manage_repo and $::icinga2::manage_package {
+  if $::icinga2::manage_repo {
```

Which also breaks the example above. But this could be fixed by #334 and:

```diff
 package { 'icinga2':
   ensure => latest,
-  notify => Class['icinga2'],
+  before => Class['icinga2::install'],
+  notify => Class['icinga2::service'],
 }
```

2. Second solution:
Reconsider #376

## Steps to Reproduce (for bugs)
```puppet
package { 'icinga2':
  ensure => latest,
  notify => Class['icinga2'],
}

class { '::icinga2':
  manage_package => false,
  manage_repo       => true,
}
```

Check for which repository the package is installed.

## Context
As this module will not have a way to specify the package version (#376) we need to do this in our wrapper/profile. But obviously we still want to use the repository management of this module.

## Your Environment

* Module version (`puppet module list`): For or less current master
* Puppet version (`puppet -V`): 4.10.1
* Operating System and version: Ubuntu 16.04.02

**Comment by lbetz** [comment]
This behavior is described:

[*manage_repo*]
 When set to true this module will install the packages.icinga.com repository. With this official repo you can get the latest version of Icinga. When set to false the operating systems default will be used. As the Icinga Project does not offer a Chocolatey repository, you will get a warning if you enable this parameter on Windows. Defaults to false. NOTE: will be ignored if manage_package is set to false.

**Comment by lbetz** [comment]
But we'll correct the example and add the management of a repository before installing the package.

**Comment by lbetz** [comment]
if you use manage_package=>false and you manage the package in front of the icing class you also have to manage a repo within an icing package before. It's not possible to use icinga2 with manage_repo because of dependency cycles.
