### ISSUE TITLE
Icinga 2 Puppet and NodeName and Zonename settings in constants.conf

### ISSUE THREAD

**Issue by ghost** [voxpupuli/puppet-icinga2#383]
Hi,

I cannot find a way to set

NodeName and ZoneName

explicitely with the Icinga 2 Puppet module. Is it not possible with this module or did I overlook it?

It always sets the name the hostname -f command reports and that reported FQDN is in that case not right.

**Comment by baurmatt** [comment]
This should work:

```puppet
class { '::icinga2':
  constants => {
    'NodeName' => 'foobar',
    'ZoneName' => 'foobar',
  },
}
```

**Comment by ghost** [comment]
Thank you. I'll try it out.
