### ISSUE TITLE
Update docs how to pass package version

### ISSUE THREAD

**Issue by rgevaert** [voxpupuli/puppet-icinga2#388]
Hi,

The module currently only installs the icinga2 packages.  It would be good if there was a way to pass the package version.  Default could stay 'installed'.

https://github.com/Icinga/puppet-icinga2/blob/master/manifests/install.pp#L30

What is your idea about this?  I could provide a PR...

**Comment by lazyfrosch** [comment]
See #244

**Comment by lbetz** [comment]
You can use some code like this:

package { 'icinga2':
  ensure => latest,
}
~>
class { '::icinga2':
  manage_package => false,
}

Notice: manage_package will disable the management of the repository too. You have to manage your favorite repository on your own.

**Comment by lbetz** [comment]
We should add this to our documentation.

**Comment by lbetz** [comment]
Sorry this also documented at the top of the documentation under usage. So I close this ticket.

**Comment by baurmatt** [comment]
This seems to be an often (#244 / #376) requested feature. Please consider implementing it.
