### ISSUE TITLE
missing /etc/pki directory

### ISSUE THREAD

**Issue by hboetes** [voxpupuli/puppet-icinga2#393]
On my system `/etc/pki` is not available, therefore this patch. I'm not entirely sure this is the best possible fix.

```
diff --git a/puppetlabs/code/modules/icinga2/manifests/repo.pp b/puppetlabs/code/modules/icinga2/manifests/repo.pp
index acfbfa3..315fd74 100644
--- a/puppetlabs/code/modules/icinga2/manifests/repo.pp
+++ b/puppetlabs/code/modules/icinga2/manifests/repo.pp
@@ -75,6 +75,10 @@ class icinga2::repo {
       }
       'suse': {

+        file { '/etc/pki/':
+          ensure => directory,
+        }
+        ->
         file { '/etc/pki/GPG-KEY-icinga':
           ensure => present,
           source => 'http://packages.icinga.com/icinga.key',

```

**Comment by lbetz** [comment]
Hm, interesting. But we can't manage resource from outside of our module. That means /etc/pki doesn't belong to the Icinga application.

As workaround handle the directory before the icinga2 module, i.e.

file { '/etc/pki':
  ensure => directory,
}
-> class { 'icinga2':
  manage_repo => true,
}

**Comment by baurmatt** [comment]
I've implemented a workaround for this problem a couple of years ago into [puppet-logstash](https://github.com/elastic/puppet-logstash):

https://github.com/elastic/puppet-logstash/blob/18c285fa8feb1c84643d7bd1b5cc83a101fdc52e/manifests/repo.pp#L66-L73
```
      # Workaround until zypprepo allows the adding of the keys
      # https://github.com/deadpoint/puppet-zypprepo/issues/4
      exec { 'logstash_suse_import_gpg':
        command => "wget -q -O /tmp/RPM-GPG-KEY-elasticsearch ${gpg_key_url}; \
                    rpm --import /tmp/RPM-GPG-KEY-elasticsearch; \
                    rm /tmp/RPM-GPG-KEY-elasticsearch",
        unless  => "test $(rpm -qa gpg-pubkey | grep -i \"${gpg_key_id}\" | wc -l) -eq 1 ",
      }
```

This completely removes the need to download the GPG key fo /etc/pki.

**Comment by lbetz** [comment]
related to #397
