### ISSUE TITLE
Replace gpgkey handling for suse

### ISSUE THREAD

**Issue by lbetz** [voxpupuli/puppet-icinga2#397]
The gpgkey is managed by a file resource to download the key. After that we use an exec to import the key. So it's impossible to download the key thru a proxy because the proxy config of zypper is bypassed.

The puppet/zypper (version 2.0.0 and higher) module has a property gpgkey... use it.

**Comment by lbetz** [comment]
Doesn't work, maybe https://github.com/voxpupuli/puppet-zypprepo/issues/10. So we haven't a chance to offer an alternative method as the module uses now. 

For SuSE use manage_repo => false and manage the repository on your own, i.e. with gpgcheck => false....

**Comment by baurmatt** [comment]
How about something like this:

```puppet
# Workaround until zypprepo allows the adding of the keys
# https://github.com/deadpoint/puppet-zypprepo/issues/4
exec { 'logstash_suse_import_gpg':
  command => "wget -q -O /tmp/RPM-GPG-KEY-elasticsearch ${gpg_key_url}; \
  rpm --import /tmp/RPM-GPG-KEY-elasticsearch; \
  rm /tmp/RPM-GPG-KEY-elasticsearch",
  unless  => "test $(rpm -qa gpg-pubkey | grep -i \"${gpg_key_id}\" | wc -l) -eq 1 ",
}
```

This works perfectly fine for the logstash module and removes the need of /etc/pki/

**Comment by hboetes** [comment]
Looks ok, but please don't use **/tmp** since anyone can create a symlink to anywhere.

**Comment by lbetz** [comment]
May someone wanna test branch 'bug/Replace-gpgkey-handling-for-suse-397' (note requires puppet 4.10 and higher).

Adding the following to hiera

icinga2::repo:
  proxy: https://host.example.org:3128

will use the proxy to download the gpg key and add it to a new line to the repo file.
