### ISSUE TITLE
How we should handle certificates in icinga2 2.8.0

### ISSUE THREAD

**Issue by lbetz** [voxpupuli/puppet-icinga2#398]
The location for the certificates stuff is moved from /etc/icinga2/pki to /var/lib/icinga2/certs.

**Comment by dnsmichi** [comment]
The migration path was added with automation in mind, keeping different versions around. Right now you should not need to do anything, if you keep the *_path variables in the ApiListener object intact and the certificates in pki/. Icinga 2 copies the requires certificates to /var/lib/icinga2/certs on its own during startup.

Long term migration should be using the new paths and dropping the deprecated config options.

https://www.icinga.com/docs/icinga2/snapshot/doc/16-upgrading-icinga-2/#migration-path

**Comment by lbetz** [comment]
Check. I worried about managing a CA but this path is untouched and the cert paths for the cli commands in pki/ca.pp and feature/api.pp are absolut to the pki dir.

**Comment by dnsmichi** [comment]
#421 is related.

**Comment by linuxmail** [comment]
hi,

I switching my instances to the new CA / proxy setup, but I'm asking, what should I use for the DMZ clients, behind the satellites. 

Should I use:

```
class { '::icinga2::feature::api':
  pki => 'none',
}
```
and execute the node wizard with the satellite as parent ?

or 
```
class { '::icinga2::feature::api':
  pki             => 'icinga2',
  ca_host         => 'icinga2-satellite.example.com',
  ticket_salt     => '5a3d695b8aef8f18452fc494593056a4',
...
}
```

cu denny

**Comment by linuxmail** [comment]
hi,
found it. Was easier than I thought :-) It is the second example without the "ticket_salt". It makes so much fun :-) I had always trouble with using the CA from Puppet, because the Master is managed by a different Puppet, than our datacenters :-)

Thanks a lot !

**Comment by lbetz** [comment]
#421 removed these parameters for v2.x because we support Icinga 2 >= v2.8.0 only.
