### ISSUE TITLE
Add feature elasticsearch

### ISSUE THREAD

**Issue by lbetz** [voxpupuli/puppet-icinga2#399]
comming in icinga2 2.8.0

**Comment by dnsmichi** [comment]
https://www.icinga.com/docs/icinga2/snapshot/doc/14-features/#elasticsearch-writer
https://www.icinga.com/docs/icinga2/snapshot/doc/09-object-types/#elasticsearchwriter

The tricky part will be using the same TLS methods as the influxdb feature.

**Comment by dnsmichi** [comment]
I'm testing a patch for this atm.

**Comment by lbetz** [comment]
refers #418
