### ISSUE TITLE
puppet4

### ISSUE THREAD

**Issue by lbetz** [voxpupuli/puppet-icinga2#402]
With version 2.0.0 we will kick puppet3 support. What version should be the lowest we support?

**Comment by dnsmichi** [comment]
I'd say the same as puppet-icingaweb2 v2, >= 4.7.0

**Comment by lbetz** [comment]
And the reasons?

**Comment by dnsmichi** [comment]
Mainly keeping it the same with other puppet-* modules which are likely used in combination with this one.
I don't mind if you bump it to 4.10 being the latest and greatest. I do have a special use case for this module inside the Vagrant boxes, my opinion here counts less.

**Comment by lbetz** [comment]
I posted this question in forecast that you answers....:) My idea was version 4.9 and higher to use hiera 5 and replace params.pp with module data.

**Comment by dnsmichi** [comment]
Ok then ;)

- from a feature point of view, use the version which fits best for development and speed.
- upgrading 4.x is "easier" from a maintenance POV, since there's this AIO package, no OS specific dependencies and forecasts on upgrade anymore.
- same goes for 5.x, if you can make exceptions here too. 5.3 is current, might be worthwhile to not support 5.0 if it got missing features.

I cannot find a lifecycle information for Puppet 4 opensource, only for PE. Dunno when EOL will then be announced, this might happen in silence such as Puppet 3.

**Comment by rick-pri** [comment]
> I posted this question in forecast that you answers....:) My idea was version 4.9 and higher to use hiera 5 and replace params.pp with module data.

I like this idea.  However, you're going to need to update the examples I think; and I think that they really need some work.

I've spent the last 5 working days trying to understand the examples and to implement a working system in FreeBSD; I've only just managed to get a client and a master set up with a CA...and I'm getting a warning about the CA being self signed...which I'm hoping is just a warning and not breaking anything.

> I cannot find a lifecycle information for Puppet 4 opensource,

I think that you'd have to work out what the end of life of the last platform which supported puppet agent 4 was and use that date where the newer platforms supported puppet agent 5 only.  It's a really unclear lifecycle policy.

**Comment by baurmatt** [comment]
> I think that you'd have to work out what the end of life of the last platform which supported puppet agent 4 was and use that date where the newer platforms supported puppet agent 5 only. It's a really unclear lifecycle policy.

I think you're referring to [this](https://puppet.com/products/capabilities/platform-support-lifecycle) document, right? I pretty sure that this document doesn't describe the EOL of a specific Puppet version, but more the support of Puppet in general for the platform. Because, if it would describe the EOL of a specific Puppet version, they need to support Puppet probably until 2025....

**Comment by dnsmichi** [comment]
Observation from standard Puppet modules in icinga/icinga-vagrant#56 - they use >= 4.7.0 through out.

**Comment by lesinigo** [comment]
also: Puppet itself has removed online documentation for [opensource versions](https://puppet.com/docs/puppet/) lower than 4.6 and [enterprise versions](https://puppet.com/docs/pe/) lower than 2016.4.x (which [goes from Puppet 4.7 up to Puppet 4.10](https://puppet.com/docs/pe/2016.4/overview_version_table.html)).

Puppet >= 4.7 is also what some widely used modules are currently requiring, such as [puppetlabs/concat](https://forge.puppet.com/puppetlabs/concat/compatibility), [puppetlabs/postgresql](https://forge.puppet.com/puppetlabs/postgresql/compatibility), [puppetlabs/mysql](https://forge.puppet.com/puppetlabs/mysql/compatibility) and many others.

As @dnsmichi already said upgrading 4.x to another 4.y is rather easy, but there can be Enterprise users that have a slower upgrade cycle at least between different releases.

I don't see any reason not to upgrade any opensource 4.x to the latest 4.10.x and I also recommend any enterprise 2016.4.x to upgrade to the latest 2016.4.9, so if it was me I would target only puppet >= 4.10. But if you want to target people who don't upgrade at all I'd go with >= 4.7.
IMHO there really is no point in going lower than that for a new, not-yet-released, module version.

Also going Hiera5 (and thus adjusting the minimum requirements) would be a good thing for the module, especially looking at the future and Puppet 5 / 6 support and the most common usage scenarios with the 2.0.x generation of this module.

**Comment by lbetz** [comment]
We're going to support puppet v4.9 and higher with puppet-icinga2 v2.0.0

**Comment by dnsmichi** [comment]
Awesome, thank you 👍
