### ISSUE TITLE
Tag v1.3.4

### ISSUE THREAD

**Issue by ThoTischner** [voxpupuli/puppet-icinga2#407]
Hey,

can you please release the Tag v1.3.4
Our new installed clients will not start because of:
https://github.com/Icinga/puppet-icinga2/commit/4a67dfb38b7b5f66e935b28d1ff1c1722e1b59af
missing in the generated config.

Thanks =)

**Comment by bplunkert** [comment]
👍

**Comment by ThoTischner** [comment]
Thanks
