### ISSUE TITLE
icinga2 binary is wrong on rhel5

### ISSUE THREAD

**Issue by bjakubiak** [voxpupuli/puppet-icinga2#409]
Module looks for icinga2 in /sbin directory, while icinga2-bin package puts it into /usr/sbin/ directory.

Up to 1.3.0 module used system PATH to locate icinga2 binary. Then it was changed to /sbin for all the linuxes in #369. The change was followed by fixes for some linux distributions: Debian: #371, RHEL 6: #390,   FreeBSD: #396.
Now it doesn't work on RHEL5.
It works on RHEL7 just because the system has symbolic link /sbin -> /usr/sbin in place.

I think the fix is to set the path to /usr/sbin for all distributions by default.

**Comment by lbetz** [comment]
RHEL 5 isn't support by this module.

**Comment by dnsmichi** [comment]
Neither is it by Icinga 2 anymore. RHEL5 is EOL for a while now.
