### ISSUE TITLE
Icinga resource doesn't create ca directory and required files

### ISSUE THREAD

**Issue by ghost** [voxpupuli/puppet-icinga2#415]
Puppet version: 5.1.4-1stretch
Icinga 2.8
Module version 1.3.4

```
  class { '::icinga2':
    manage_repo => true,
    enable      => true,
    constants   => {
      'NodeName' => $trusted['certname'],
      'ZoneName' => 'master',
    },
    features    => [
      'api',
      'checker',
      'command',
      'mainlog',
      'notification',
      'statusdata',
      'syslog',
    ],
  }
```

I am playing around with the Icinga 2 puppet module and wanted to create a master Icinga 2 node.

The problem is it creates only the

/var/lib/icinga2/certs

with the files

_ca.crt  imaster.someurl.de.crt  imaster.someurl.de.key_

but no

/var/lib/icinga2/ca

Shouldn't the CA files be in that directory and shouldn't the module create it if it's missing? Additionally the ca.key seems to be missing for some reason.

**Comment by lbetz** [comment]
When you wanna have a CA, you have to declare the class icinga::pki::ca. This class manage /var/lib/icinga2/ca and will create a certificate for itself. But this requires pki => 'none' in icinga2::feature::api. Please consult the documentation.

**Comment by ghost** [comment]
Thanks for the clarification.
