### ISSUE TITLE
Remove deprecated ApiListener options key_path, ca_path and cert_path

### ISSUE THREAD

**Issue by baurmatt** [voxpupuli/puppet-icinga2#421]
## Expected Behavior
Icinga2 shouldn't throw deprecation warnings on reload

## Current Behavior
```bash
# icinga2 daemon -C
...
warning/ApiListener: Attribute 'key_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'ca_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'cert_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Please read the upgrading documentation for v2.8: https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/
...
```

## Possible Solution
Remove deprecated settings from icinga2::feature::api -> https://github.com/Icinga/puppet-icinga2/blob/master/manifests/feature/api.pp#L354-L356

## Steps to Reproduce (for bugs)
Pseudo Puppet Code:
```puppet
class { 'icinga2': }
class { '::icinga2::feature::api':
  ensure          => 'present',
}
```

```bash
icinga2 daemon -C
```

## Your Environment

* Module version (`puppet module list`): Our own fork of this module, more or less current master
* Puppet version (`puppet -V`): 5.3.3
* Operating System and version: Ubuntu 16.04
* Icinga2: 2.8.0

**Comment by baurmatt** [comment]
Any objection from the core developers? I'm not quite sure if this will break support for older Icinga2 versions.

**Comment by dnsmichi** [comment]
This breaks everything < 2.8 where these attributes are required. This change needs a bump in the least supported version in this module, e.g. future major version v2.0.0.

**Comment by lbetz** [comment]
We will do this in the future when Icinga < v2.7 isn't support anymore.

**Comment by deric** [comment]
Wouldn't it be easier to introduce a fact with a Icinga2 version number? On Linux you can get a semantic version with something like this:
```
icinga2 --version | head -n 1 | awk '{print $10}' | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'
2.8.1
```
and then decide the configuration based on release version.

**Comment by baurmatt** [comment]
On the first run this fact would be empty.

**Comment by deric** [comment]
@baurmatt Right, when the version is set to `undef` we can't take any action. I think it's better when the configuration applies on the second Puppet run, than waiting for 2.7 to become deprecated.
