### ISSUE TITLE
Rework examples and docs

### ISSUE THREAD

**Issue by lbetz** [voxpupuli/puppet-icinga2#423]

**Comment by kwisatz** [comment]
@lbetz it'd be nice if the Changelogs could also feature required configuration changes.
I've been trying to upgrade from 1.0.2 to 1.3.4 (I know, quite a leap of faith) and I ran into the following issue:

```
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Failed to parse template icinga2/object.conf.erb:
  Filepath: /etc/puppet/environments/staging/modules/icinga2/lib/puppet/parser/functions/icinga2_attributes.rb
  Line: 5
  Detail: Must provide at least one argument.
 at /etc/puppet/environments/staging/modules/icinga2/manifests/object.pp:129:18 on node subdomain.host.tld
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

As far as I can tell, this has something to do with constants, but I haven't had the chance to fully look into it yet.

**Comment by lbetz** [comment]
Sorry, we missed that. Because the only thing you have to do is flush the cache on the master machines, i.e. do a restart.

**Comment by lbetz** [comment]
Docs reworked, done with puppet strings.
