### ISSUE TITLE
Applying services to hostgroups

### ISSUE THREAD

**Issue by remy1991** [voxpupuli/puppet-icinga2#427]
Is there a way to assign services to hostgroups and not just hosts?
I went through icinga2 objects types and through this puppet module code as well but couldnt find anything substantial.

**Comment by lbetz** [comment]
Assign a service to a hstgroup is the old way. Icinga 1/Nagios work this way. For Icinga 2 that's not necessary. You assign to attribute or custom attributes.
Or maybe you also wanna do it by hostgroups, use an apply rule like
apply where "foo" in host.groups

**Comment by remy1991** [comment]
Yep. We are in process of migrating from icinga1 to icinga2. Because of this transition and keeping the puppet code similar, was looking for something like that. Makes things easier anyway. Thanks for the help.
