### ISSUE TITLE
overriding thresholds of individual disks

### ISSUE THREAD

**Issue by pgassmann** [voxpupuli/puppet-icinga2#428]
The example vars do not work as expected. What is the correct way to raise the thresholds for single disks?

https://github.com/Icinga/puppet-icinga2/blob/6412e421cbfac31b696fa1bca81d6f6f9af1d899/examples/example4/hieradata/nodes/example.domain.org.yaml#L2-L7

Adding these host vars results in following object for the host:
```
#cat /etc/icinga2/conf.d/host.rz.example.com.conf
# This file is managed by Puppet. DO NOT EDIT.

object Host "host.rz.example.com"  {
 [..]
  vars.os = "linux"
  vars.disks["disk /opt/IBM"] = {
    disk_cfree = "8%"
    disk_wfree = "10%"
  }
```

Setting the disk_cfree value directly raises the threshold for all disks
```
object Host "host.rz.example.com"  {
 [..]
  vars.os = "linux"
  vars.disk_cfree = "8%"
  vars.disk_wfree = "10%"
```

The check_disk config:
```
cat /etc/icinga2/conf.d/check_disk_monitor.rz.example.com.conf
# This file is managed by Puppet. DO NOT EDIT.

apply Service "check_disk_monitor.rz.example.com" to Host {
  display_name = "disk"
  check_command = "disk"
  check_interval = 1m
  retry_interval = 30s
  max_check_attempts = 5
  command_endpoint = host.name
  vars.disk_all = true
  assign where host.vars.puppetversion
}
```

**Comment by dnsmichi** [comment]
```
  vars.disks["disk /opt/IBM"] = {
    disk_cfree = "8%"
    disk_wfree = "10%"
  }
```

excepts you to use the apply for rules, not a single apply rule. Your example with the apply rule expects the flattened custom attributes for single services.

The correct usage example is here:
https://github.com/Icinga/puppet-icinga2/blob/6412e421cbfac31b696fa1bca81d6f6f9af1d899/examples/example4/profile/manifests/master.pp#L68

**Comment by lbetz** [comment]
Take a look at the eamples.

https://github.com/Icinga/puppet-icinga2/blob/master/examples/example_config.pp

[...]
::icinga2::object::service { 'disk':
  target        => '/etc/icinga2/example.d/services.conf',
  apply         => 'fs => config in host.vars.disks',
  import        => [ 'generic-service' ],
  check_command => 'disk',
  vars          => 'vars + config',
}
[...]

**Comment by pgassmann** [comment]
Thanks for the support.

So **with our current setup it is not possible to define exceptions per disk** because it is one shared check?
To enable that, we would need to refactor the config so that all disks are defined explicitly on the host and then we would have separate checks for each disk and could define separate thresholds.

To automatically monitor all filesystems one could use `$facts['mountpoints']`.
This does not look trivial to filter the disks and define the desired hash.
```
::icinga2::object::host { 'NodeName':
  [...]
  vars           => {
    disks              => {
      disk             => {},
      'disk /'         => {
        disk_partition => '/',
      },
      'disk /opt/IBM'  => {},
  },
}
```
and then change the check_disk service like that:
https://github.com/Icinga/puppet-icinga2/blob/6412e421cbfac31b696fa1bca81d6f6f9af1d899/examples/example4/profile/manifests/master.pp#L68-L77

**Comment by dnsmichi** [comment]
You need to understand the concept of the underlaying apply rules. If you want to make exceptions to the one and only apply rule, you need 2 or more which deal with different patterns. If you can control it on the host level, set specific service thresholds inside the nested dictionary for the service apply for rule. More on that in the Icinga 2 documentation.

Apart from that, I suggest to ask these questions on configuration details on the community channels such as lists.icinga.org or monitoring-portal.org where a broader audience reads and discusses.

**Comment by lbetz** [comment]
Yes, that isn't trivial.
