### ISSUE TITLE
Directory not automatically created on first runthrough

### ISSUE THREAD

**Issue by zilchms** [voxpupuli/puppet-icinga2#431]
On the first runthrough of puppet agent -t on the client, the directory /etc/icinga2/features-available doesnt get created in time for dependent icinga files, which leads to a non succeeding runthrough.

## Expected Behavior
All directories that are dependencies for icinga files and have to be created in time, should do so.

## Current Behavior
Dependency is not created in time. Leading to a not successful runthrough.

## Possible Solution
Adding the following code seems to avoid the issue:
```
  file{'/etc/icinga2':
    ensure => 'directory',
  }

  file{'/etc/icinga2/features-available':
    ensure => 'directory',
    require => File['/etc/icinga2'],
    before => Class['::Icinga2::Config']
  }

  file{'/etc/icinga2/repository.d':
    ensure => 'directory',
    require => File['/etc/icinga2'],
  }
```
I am not sure if the creation of '/etc/icinga2/repository.d' is completely necessary, in my setup it is, since I have not come around to disabling repository.d in the icinga2.conf on an automated basis.

I am not sure, if the bug is currently existent on the newest version of the icinga2 module (1.3.5). In the commits since 1.3.0 I did not find anything related to this. I will do some testing to see, if this bug is in the newer versions, too, if I find the time to do so.

## Steps to Reproduce (for bugs)

1. Install the module for puppet on the master
2. Configure all data, if need, in Hiera
3. Run puppet agent -t on the puppet client node

## Context
For an automatic setup a success on the first run would be nice. It is not really necessary however since the issue seems to occur only on the first runthrough, but not on the second, which seems to be only a little problem with dependencies in creating the needed directories.

## Your Environment

* Module version (`puppet module list`): 1.3.0
* Puppet version (`puppet -V`): 3.8.5
* Operating System and version: SLES 12.3

**Comment by lbetz** [comment]
Both directories are manage by the icinga2 package. We won't manage feature-availabe in puppet, repository.d is  necessary because it's removed in 2.8 and is now manage by puppet for compatibility.
