### ISSUE TITLE
don't quote null 

### ISSUE THREAD

**Issue by rgevaert** [voxpupuli/puppet-icinga2#433]
I noticed that null is always quoted.  Which is something you would normally not want. Right?

I appreciate the way to make it possible to not automatically quote the full string, but shouldn't we add null to the excluded list?

https://github.com/Icinga/puppet-icinga2/blob/master/lib/puppet_x/icinga2/utils.rb#L89

**Comment by rgevaert** [comment]
Thanks Lennart!

**Comment by lbetz** [comment]
you're welcome. That was simple. But I donno whenever we'll release 1.3.6.
