### ISSUE TITLE
Windows : owner and group

### ISSUE THREAD

**Issue by MelanieGault** [voxpupuli/puppet-icinga2#437]
Hello,

Is there any reason why owner and group are not parametrised for windows ? (object.pp and config/fragment.pp)
https://github.com/Icinga/puppet-icinga2/blob/16a317b4d056993f0c450ef49e6809eaa4500240/manifests/object.pp#L84

I have some windows server (I'm not a windows administrator but I have to do some stuff on windows...) and they are installed in a french version.
"Administrators" is "Administrateurs" and "NETWORK SERVICE" is "Service réseau" (with the accent)

I try to create english groups and manage permission to do as if they existed, but with the accent It's a big mess.
So I wonder why we can have parametrized values for linux and not for windows.

Thanks.
Melanie

**Comment by lbetz** [comment]
refs #511
