### ISSUE TITLE
replace deprecated validation functions 

### ISSUE THREAD

**Issue by lbetz** [voxpupuli/puppet-icinga2#439]

**Comment by mphilipps** [comment]
hi,
I would like to use puppet-icinga2, but due to our puppet server running with strict=error I am unable to use it.  
Apparently you are planning to replace them  for v1.4.0,  but how is that different from the pull request #350 that is sheduled for v2.0? I assume v2.0 is a way off in the future?

**Comment by lbetz** [comment]
duplicate issue and assigned to wrong version
