### ISSUE TITLE
Missing of if else functionality in serviceconfiguration as icinga2 would normally allow

### ISSUE THREAD

**Issue by zilchms** [voxpupuli/puppet-icinga2#444]
Feel free to correct me if I am wrong, but I havent found any Issues on this matter up to now.
Normally icinga2 allows for configurations such as this:

```
apply Service "Ping" to Host {
 import generic service

 if (host.vars.customvar){
   check_period = "24x7"
 } else {
   check_period = "9to5"
 }

 assign where host.address
}
```
No matter how I look at it, I cant seem to find a way to work this if else structure into an acceptable puppet configuration, in a way that the results looks as the one mentioned above

## Expected Behavior

In my opinion, it should be possible to at least replicate icinga2 configuration files to a degree which does not shorten the configuration possibilities icinga2 already provides
## Possible Solution

I think a free text field variable, which allows for multiline string inputs, might do the trick for this kind of configuration for services. In some old Forum I have found that this idea is highly debatable as it messes with the structure of puppet evaluating things not in order (but maybe I got that part wrong). As mentioned above, if there is already a thread to this that I have overlooked, I am very happy for some guidance or a heads-up.

## Your Environment

* Module version (`puppet module list`): 1.3.6
* Puppet version (`puppet -V`): 3.8.5
* Operating System and version: SLES 12

**Comment by lbetz** [comment]
This such of code has to be written outside any icinga2 object class like service, have a look at icinga2::config::fragment at https://github.com/Icinga/puppet-icinga2/blob/master/manifests/config/fragment.pp.

**Comment by zilchms** [comment]
The icinga2::config::fragment surely is helpful. In my current setup all Services are located in one file services.conf looking like this:
```
service ping4 {
  import generic-service
. . .
}

service ping6 {
  import generic-service
. . .
}

. . .
```

Now i would like to add to every service the checkperiod as stated in the first comment.
If i understand this correctly then i still have to add one fragment for each service, right? Or is there a way to simply write one fragment and simply apply it to every service in the file?
Since i am planning on adding several more services the second option would allow for easier handling.

Edit: If i understand the order operator right, i can only specify which line the fragment gets added to. Am i right there?

**Comment by lbetz** [comment]
To both - yes. The fragments based on concat fragments and it's not permiited to use one fragement in more than one concat resource.

**Comment by zilchms** [comment]
Okay. I can work with that on my setup.

The inital problem still persists though. In my opinion it should be possible to build "standard" icinga2 config files with the puppet module. The way it is handled now is more complicated than it needs to be.
If I recall correctly it is possible to parse multi-line strings in puppet. In that case why not add another string parameter to the service.pp, something like additionalcontent (or something shorter) which per default is empty.
This would allow something as follows:
```
::icinga2::object::service {
    'testservice':
        import => 'template',
        check_command => 'test',
        additionalcontent => "if(test){\n    check_period = \"test\"\n}"
}
```
which would translate to some config file for icinga2 similar to this:
```
service testservice {
    import "template"
    check_command = "test"
    if(test){
        check_period = "test"
    }
}
```
If I am mistaken, please correct me on that one. Please excuse me for mistakes in the usage of multiline strings, I didnt have the occasion to use them often.

**Comment by lbetz** [comment]
Next will be, 'but I need a different order.'

service testservice {
    import "template"
    if(test){
        check_period = "test"
    }
  check_command = "test"
}

That's a never ending story. We discussed that at the start of the project.

**Comment by lbetz** [comment]
We wanted simple classes and all all complex things shall configure by config::fragment.

**Comment by zilchms** [comment]
Ok i see where you are going with this.
