### ISSUE TITLE
ensure absent on object doesn't remove the full file

### ISSUE THREAD

**Issue by rgevaert** [voxpupuli/puppet-icinga2#447]
Hi,

I just found out that you can remove all the files created by icinga2::object.  (like icinga2::object::notification) 

The fragment is removed, but the file still exists with the header. This is because of

https://github.com/Icinga/puppet-icinga2/blob/0e21436a051f6e42dd6406fe5c540333daa75521/manifests/object.pp#L134

I ran into this because I was removing the parent directory but the object still was create. 

E.g. you get errors like this

Error: /Stage[main]/Monitoring::Icinga2/Icinga2::Object::Notification[slack-ugi]/Icinga2::Object[icinga2::object::Notification::slack-ugi]/Concat[/etc/icinga2/conf.d/slack-notifications/dict.conf]/File[/etc/icinga2/conf.d/slack-notifications/dict.conf]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory @ dir_s_mkdir - /etc/icinga2/conf.d/slack-notifications/dict.conf20180613-8171-1x2i3ci.lock

when you do (assuming slack_hook is undef)
```
  $slack_object_notification_ensure = $slack_hook ? {
    undef   => absent,
    default => present,
  }

  file { '/etc/icinga2/conf.d/slack-notifications':
    ensure  => absent,
    recurse => true,
    purge   => true,
    force   => true,
  }
  icinga2::object::notification { 'slack-ugi-hosts':
    ensure       => $slack_object_notification_ensure,
    target       => '/etc/icinga2/conf.d/slack-notifications/dict.conf',
    apply        => true,
    apply_target => 'Host',
    import       => ['slack-notifications-user-configuration-hosts', 'slack-ugi',],
    assign       => [ 'host.vars.slack_notifications == enabled && ugi_hosts in host.groups' ],
  }
```
What about doing ensure => $ensure
https://github.com/Icinga/puppet-icinga2/blob/0e21436a051f6e42dd6406fe5c540333daa75521/manifests/object.pp#L134

Also I think   if $ensure != 'absent'  test for the fragment is not needed if you apply ensure => $ensure for the concat definition.

**Comment by lbetz** [comment]
Hi,

ensure is for the object. The concat resource is created for the first define resource of object thru compilation. That mean if you set ensure to absent for one of your objects it could be the first. Then you get a concat with ensure to absent and a lot of fragments with your object definitions.

No that doesn't work, I think.

But of course the problem is known.

Bye Lennart
