### ISSUE TITLE
Windows service permissions and update-windows check

### ISSUE THREAD

**Issue by MelanieGault** [voxpupuli/puppet-icinga2#449]
Hello

I try to have "update-windows" check working on windows 2008 and 2012.
Out of the box, It says that I don't have permissions (as noted in https://www.icinga.com/docs/icinga2/latest/doc/10-icinga-template-library/#update-windows) .

After some checks, I see that the service must be running with 'local user account' not 'network services'. (https://monitoring-portal.org/woltlab/index.php?thread/40784-how-to-enable-activate-check-update-exe/) 

I can't find any way to archived that with the module.

I try to have 'manage_service' to false to change the runas user, but... https://puppet.com/docs/puppet/5.5/resources_service.html#windows says that 
```On Microsoft Windows, Puppet can start, stop, enable, disable, list, query and configure services. It expects that all services will run via Windows’ built-in Service Control Manager (SCM) system. It does not support configuring service dependencies, account to run as, or desktop interaction.```

so.... do you have any hint on archiving this simple check on windows server ?

Thanks
Melanie

**Comment by lbetz** [comment]
Hi Melanie,

that's all right. The following should work on windows plattforms:

manage the icinga2 package before the class icinga2 (manage_package => false) notify to

an exec resource with a command like 'sc.exe config icinga2 obj= "NT AUTHORITY\NetworkService" password= dummy' (of course with a local user) notify to class icinga2

Keep in mind I didn't test that....

let us now if it works or not.

Thx Lennart

**Comment by MelanieGault** [comment]
Hello,

Thanks !
I have something working, but not idempotent for now...

```
  exec { 'icinga2-windows-servicerunas':
    command => 'c:/windows/system32/sc.exe config icinga2 obj= LocalSystem password= ""',
    unless  => 'c:/Windows/system32/wbem/wmic.exe service where \'name = "icinga2"\'  get startname | findstr NetworkService',
    notify  => Service['icinga2'],
  }
```
I found this information :
```
FINDSTR will set %ERRORLEVEL% as follows:

0 (False) a match is found in at least one line of at least one file.
1 (True) if a match is not found in any line of any file, (or if the file is not found at all).
2 Wrong syntax 
An invalid switch will only print an error message in error stream.
```

But it does not seems to be a return code as expected... (I'm a linux sysadmin and I never did any windows scripting...)
So I need some more improovement to be clean !

Regards,
Mélanie

**Comment by MelanieGault** [comment]
Hello,

Thanks !
I have something working, but not idempotent for now...

```
  exec { 'icinga2-windows-servicerunas':
    command => 'c:/windows/system32/sc.exe config icinga2 obj= LocalSystem password= ""',
    unless  => 'c:/Windows/system32/wbem/wmic.exe service where \'name = "icinga2"\'  get startname | findstr NetworkService',
    notify  => Service['icinga2'],
  }
```
I found this information :
```
FINDSTR will set %ERRORLEVEL% as follows:

0 (False) a match is found in at least one line of at least one file.
1 (True) if a match is not found in any line of any file, (or if the file is not found at all).
2 Wrong syntax 
An invalid switch will only print an error message in error stream.
```

But it does not seems to be a return code as expected... (I'm a linux sysadmin and I never did any windows scripting...)
So I need some more improovement to be clean !

Regards,
Mélanie

**Comment by lbetz** [comment]
Did you try puppetlabs-dcs? Exactly the resource dcs_service?
