### ISSUE TITLE
Deprecated features in 2.9: statusdata & compatlog

### ISSUE THREAD

**Issue by dnsmichi** [voxpupuli/puppet-icinga2#481]
Just a short note, that the features `statusdata` and `compatlog` have been deprecated with 2.9, and will be removed in 2.11.

Depending on when you plan for 2.0 for this module, you might want to decide the base supported version and features then.

**Comment by lbetz** [comment]
The release of 2.0 is planed before OSMC. We wanna support 2.8 and higher of Icinga 2 so these feature are needed. The user has to enable the features if he wants to use one of these. 

But we should documentate that.

**Comment by dnsmichi** [comment]
Okidoki, just wanted to let you know :-)
