### ISSUE TITLE
Change location of the CA and the cert

### ISSUE THREAD

**Issue by lbetz** [voxpupuli/puppet-icinga2#484]
icinga2::pki::ca change to /var/lib/icinga2/ca and /var/lib/icinga2/certs

**Comment by SimonHoenscheid** [comment]
Whats about setting the path depending on Icinga2 version?

**Comment by lbetz** [comment]
When you install icinga2 the first time (with ensure => installed) how you determine what version was installed?

**Comment by dnsmichi** [comment]
v2.0 will support 2.8+ as I've learned in #481, so I don't think that such a change is necessary :)

**Comment by SimonHoenscheid** [comment]
Thx @dnsmichi
