### ISSUE TITLE
InfluxWriter: Optional parameters are forced by module

### ISSUE THREAD

**Issue by htj** [voxpupuli/puppet-icinga2#491]
Hi

I'm exporting icinga data to an influx instance with the influxdbwriter feature.

The puppet module has some rather strong assumptions on what options need to be set.

## Expected Behavior

When `enable_ssl` is set, .e.g:
```
class { '::icinga2::feature::influxdb':
    host                 => 'HOST,
    port                 => 8443,
    database             => 'icinga2',
    enable_ssl           => true, # true means using certificates
    ssl_cacert_path      => "/etc/ssl/certs/DigiCert_Assured_ID_Root_CA.pem",
    enable_send_metadata => true,
  }
```

I'd expect the variables `ssl_enable` and `ssl_ca_cert` to pop up in configuration file.

BUT NOT the variables `ssl_cert` and `ssl_key`. The are optional, and having them in the configuration breaks our setup.

## Current Behavior

As soon as `enable_ssl` is set, the following parameters are filled in by the puppet module:
```
  ssl_enable = true
  ssl_ca_cert = "..."
  ssl_cert = "/etc/icinga2/pki/influxdb/monitor.nordu.net.crt"
  ssl_key = "/etc/icinga2/pki/influxdb/monitor.nordu.net.key"
```

This doesn't work in our setup.

If I remove ssl_cert and ssl_key stuff works.

## Possible Solution

Don't autofill the variables.

The whole "try to guess what should be in variables" seems like a bad idea to me.

## Steps to Reproduce (for bugs)

Define `enable_ssl` in the `class { '::icinga2::feature::influxdb':`

**Comment by lbetz** [comment]
Ok, key and certificate arn't needed if no client auth is required.

So these parameters has to be optional. And remove pki as parameter.

**Comment by linuxmail** [comment]
hi,

just a question ... I have also this problem. I have in my Hiera config:

```
icinga2::feature::influxdb::enable_ssl: true
```

Thats all and cert / key / ca is set, which is not required. Puppet module is the latest version.  Did I something wrong ?

**Comment by lbetz** [comment]
Hi Denny,

I'm not sure if I understand you, should the problem be fixed?

Bye
Lennart

**Comment by linuxmail** [comment]
hi Lennart

yeah . I thought, it is fixed, but I have to chattr +i the file, to avoid overwritung with the SSL params.

**Comment by lbetz** [comment]
No I am confused. Did you mean the cert and key is also written if the parameters wasn't set?

**Comment by lbetz** [comment]
Ah I see, please check out branch 'linuxmail'.

**Comment by lbetz** [comment]
No, sorry, I don't understand the problem. I think, I need more details. Which file do you set to read only?

**Comment by linuxmail** [comment]
Hi Lennart,

I have added to my Hiera `icinga2::feature::influxdb::enable_ssl: true`, which enabled the TLS communication. The problem is now,  that we don't require the params `ssl_ca_cert`, `ssl_cert` and `ssl_key` in `/etc/icinga2/features-available/influxdb.conf`

```
...
Notice: /Stage[main]/Icinga2::Feature::Influxdb/Icinga2::Object[icinga2::object::InfluxdbWriter::influxdb]/Concat[/etc/icinga2/features-available/influxdb.conf]/File[/etc/icinga2/features-available/influxdb.conf]/content: 
--- /etc/icinga2/features-available/influxdb.conf	2021-09-04 00:20:09.906747720 +0200
+++ /tmp/puppet-file20210912-30833-1ldn9hx	2021-09-12 12:23:31.452046858 +0200
@@ -35,4 +35,7 @@
   flush_interval = 10s
   flush_threshold = 1024
   ssl_enable = true
+  ssl_ca_cert = "/etc/icinga2/pki/influxdb/ca.crt"
+  ssl_cert = "/etc/icinga2/pki/influxdb/mon-01.example.com.crt"
+  ssl_key = "/etc/icinga2/pki/influxdb/mon-01.example.com.key"
 }
```

If these params are enabled .. the connection to our InfluxDB doesn't work anymore, because our wildcard cert was changed. It is not necessary, to have all three params, just `ssl_enable = true`  is enough. 

So I set for now `/etc/icinga2/features-available/influxdb.conf` to read only to avoid the overwrite. The Module version from Icinga2-Icinga  is: ***3.1.3***.

So the question is .. how to avoid ssl_ca_cert / ssl_cert / ssl_key params. So I searched for something related here ... and I've found this bug ... closed and from 2018 ... :-) 

cu denny

**Comment by lbetz** [comment]
Hi Denny,

my puppet manifest:

class { '::icinga::repos':
  manage_epel => true,
}
class { '::icinga::server':
  global_zones         => [ 'global-templates', 'linux-commands', 'windows-commands' ],
  logging_type         => 'syslog',
  logging_level        => 'warning',
}
class { '::icinga2::feature::influxdb':
  ensure     => present,
  host       => '127.0.0.1',
  database   => 'icinga2',
  username   => 'icinga2',
  password   => 'icinga2',
  enable_ssl => true,  
}

and this is the result in influxdb.conf:
library "perfdata"

object InfluxdbWriter "influxdb" {
  host = "127.0.0.1"
  database = "icinga2"
  username = "icinga2"
  password = "icinga2"
  host_template = {
    measurement = "$host.check_command$"
    tags = {
      hostname = "$host.name$"
    }
  }
  service_template = {
    measurement = "$service.check_command$"
    tags = {
      hostname = "$host.name$"
      service = "$service.name$"
    }
  }
  ssl_enable = true
}

That looks like expected to me.

**Comment by linuxmail** [comment]
Hi, 

hmm ok, maybe an older Icinga Modul in the environment definition has a higher presence, than the version from PuppetForge. I will check later.

**Comment by linuxmail** [comment]
Hi Lennart,

I have really say sorry for the noise from me.  I had an older Icinga2 module in the environment.conf, which has a higher priority, than the PuppetForge one. I removed it and than .. the SSL vars are not added anymore.   The ticket can closed (again)

Thanks !

**Comment by lbetz** [comment]
ok.
