### ISSUE TITLE
API change to icinga2 CA as default 

### ISSUE THREAD

**Issue by lbetz** [voxpupuli/puppet-icinga2#495]
The class icinga2::feature::api uses the Puppet Cert as default. We change it to icinga2.

**Comment by baurmatt** [comment]
Is there a specific reason why this was done? Puppet certs was IMHO easier to set up.

**Comment by dnsmichi** [comment]
Re-using the Puppet CA for a different application implies a security problem in some scenarios with opening the matter of trust to Puppet _and_ Icinga. Agreed on the easiness, but security matters these days and we should follow best practices imho.

**Comment by lbetz** [comment]
Michi is right of course. With the certificate from puppet you're able to get a catalog, maybe with passwords.

**Comment by baurmatt** [comment]
Thanks for explaining your decision, that's everything i wanted ;)
