### ISSUE TITLE
Some comments when using on Windows

### ISSUE THREAD

**Issue by netzwerkgoettin** [voxpupuli/puppet-icinga2#499]
Hi,

as discussed with @lbetz - here's my issue.

I'm about to manage Linux hosts without any problems; but on Windows, I ran into several issues. It might be interesting that the host is not a newly installed icinga2 instance - it was previously configured to get monitored by the old icinga2 master, and via puppet it then gets its configuration for the new monitoring master. Here's what I noticed:

* `icinga.conf` is reported as broken because of `include_recursive "conf.d"` and `include_recursive "repository.d"`; for `repository.d` the docs explain a default `false` for `repositoryd`, but I had to put that explicitly in my config to take effect. I also set `confd` to `false` now, but in other environments I think this will be a serious problem. (Previously I ran icinga2-2.10.1 on this host without any problems; this problem arised with the automatic installation of icinga2-2.10.2.)
![screenshot 2018-11-22 at 09 42 18](https://user-images.githubusercontent.com/11242139/48899872-18c31580-ee51-11e8-8a01-8fcae1dcfbd1.jpg)

* I get many errors on each puppet run because there is no group `NETWORK SERVICE` on my (German) Windows system; that's an issue which was already reported at https://github.com/Icinga/puppet-icinga2/issues/437 I think, and it seems to get a blocker. In fact, `icinga2` is able to run on the client even when there are these errors reported, but in Foreman the host seems broken with lots of error reports. At this point it might help to change the severity from emerg to anything-not-so-important. 
![screenshot 2018-11-22 at 12 28 27](https://user-images.githubusercontent.com/11242139/48900264-3644af00-ee52-11e8-8613-4dfbeefde2a6.jpg)

* A complete and correct `features-available/api.conf` is generated on puppet run; but it's not activated via `features-enabled`, so it'll take no effect (I made it manually, everything's fine). Maybe in a row with non existing `NETWORK SERVICES`.

* After a puppet run the `icinga2` daemon is not running on the Windows host; probably due to the errors before. When I start (via `\.icinga2.exe daemon` or click on `Start`) it's up and running.

* Started as `\.icinga2.exe daemon` it's mostly not possible to stop daemon via CTRL+C, I have to use Task Manager; sometimes it consumes lots of cpu when trying to kill it.

So when I can help you debugging with some testing or more information - just let me know. It would be pretty cool to get everything up and running 👍 

Cheers,
  Marianne

## Expected Behavior
It should work on Windows.

## Current Behavior
It doesn't.

## Your Environment
* Module version (`puppet module list`):
````
├── ghoneycutt-common (v1.7.0)
├── ghoneycutt-ssh (v3.58.0)
├── icinga-icinga2 (v1.3.6)
├── puppetlabs-apt (v2.4.0)
├── puppetlabs-chocolatey (v3.1.0)
├── puppetlabs-concat (v4.2.1)
├── puppetlabs-firewall (v1.12.0)
├── puppetlabs-inifile (v2.1.0)
├── puppetlabs-motd (v2.1.1)
├── puppetlabs-ntp (v7.2.0)
├── puppetlabs-powershell (v2.2.0)
├── puppetlabs-registry (v2.0.2)
├── puppetlabs-stdlib (v4.25.1)
├── puppetlabs-transition (v0.1.1)
├── puppetlabs-translate (v1.1.0)
└── saz-resolv_conf (v4.0.0)
````

* Puppet version (`puppet -V`): 5.5.6
* Operating System and version: Windows Server 2012 R2 German

**Comment by lbetz** [comment]
refs #511
