### ISSUE TITLE
Evaluation Error: Error while evaluating a Function Call, Class[Icinga2::Globals]:

### ISSUE THREAD

**Issue by paladox** [voxpupuli/puppet-icinga2#504]
Hi, upgrading to the latest commit under the 2.x branch, I'm getting:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Class[Icinga2]:
  expects a value for parameter 'features'
  expects a value for parameter 'plugins' at /etc/puppet/environments/production/modules/monitoring/manifests/init.pp:15:5 on node misc1.miraheze.org
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Class[Icinga2::Globals]:
  expects a value for parameter 'package_name'
  expects a value for parameter 'service_name'
  expects a value for parameter 'user'
  expects a value for parameter 'group'
  expects a value for parameter 'ido_mysql_package_name'
  expects a value for parameter 'ido_mysql_schema'
  expects a value for parameter 'ido_pgsql_package_name'
  expects a value for parameter 'ido_pgsql_schema'
  expects a value for parameter 'icinga2_bin'
  expects a value for parameter 'conf_dir'
  expects a value for parameter 'lib_dir'
  expects a value for parameter 'log_dir'
  expects a value for parameter 'run_dir'
  expects a value for parameter 'spool_dir'
  expects a value for parameter 'cache_dir'
  expects a value for parameter 'cert_dir'
  expects a value for parameter 'ca_dir'
  expects a value for parameter 'reserved'
  expects a value for parameter 'service_reload' at /etc/puppet/environments/production/modules/icinga2/manifests/init.pp:153:3 on node misc1.miraheze.org
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

## Expected Behavior
The values to be prefilled with defaults.

## Current Behavior
It's fataling with the error in the description.

## Possible Solution
Fill in the defaults.

## Your Environment

* Module version (`puppet module list`):
* Puppet version (`puppet -V`): 4.8
* Operating System and version: 9

**Comment by lbetz** [comment]
For branch v2.x puppet 4.10 or higher is required. Data in modules as feature is needed:
https://puppet.com/docs/puppet/4.10/hiera_migrate_modules.html

  "requirements": [
    { "name": "puppet", "version_requirement": ">= 4.10.0 < 6.0.0" }
  ],

But this info is missed in the documentatition yet.

**Comment by fredjupp** [comment]
Hello!
I see the same error message, but only on windows systems. On RHEL, it works fine.
I never defined constants myself and i older version, they can be found in the params.pp which does not exist any more in v2.1.0
Can you explain this to me

**Comment by fredjupp** [comment]
I found a fix myself. The data/Windows-kernel.yaml does not match the case, which is returned by the facter -p kernel command. This returns windows as lower case, whereas the yaml file is written with a capital W.
So, i linked the Windows-kernel.yaml to windows-kernel.yaml and it worked.
So, please include this fix to an upcoming release, I can also push my branch, if i have the permission.
A good idea would be to make the yaml filename independant of the case, in which the fact is returned.

**Comment by lbetz** [comment]
thx @fredjupp, I opened #556
