### ISSUE TITLE
Puppet 6 Support

### ISSUE THREAD

**Issue by rychannel** [voxpupuli/puppet-icinga2#505]
Has anyone tried this on Puppet 6 or PE 2019 yet?

**Comment by rdagum** [comment]
I'm not able to install icinga2 with P6. We had to upgrade to P6 because of other modules and now we are stuck unable to deploy icinga.

**Comment by lbetz** [comment]
Did you checkout branch v2.x?

**Comment by gasperno** [comment]
Puppet version: 6.1.0
Icinga Version: r2.10.2-1

I tried with v2.x this morning.  I have the following resources configured for icinga master role.
```
    class { 'icinga2::pki::ca': }
    class { 'icinga2::feature::api':
        pki     => 'none',
    }
```
Actual Behavior: 

```
object ApiListener "api" {
  crl_path = ""
  accept_commands = ""
  accept_config = ""
  ticket_salt = TicketSalt
  tls_protocolmin = ""
  cipher_list = ""
  bind_host = ""
  bind_port = ""
  access_control_allow_origin = ""
  access_control_allow_credentials = ""
  access_control_allow_headers = ""
  access_control_allow_methods = ""
}
```

Expected Behavior: I call this expected because I get the following with puppet5 so I expect something similar with puppet6.

```
 object ApiListener "api"  {
      cert_path = "/etc/icinga2/pki/mc1.ascentis-test.com.crt"
      key_path = "/etc/icinga2/pki/mc1.ascentis-test.com.key"
      ca_path = "/etc/icinga2/pki/ca.crt"
      accept_commands = false
      accept_config = false
      ticket_salt = TicketSalt
}
```

This causes icinga2 validation to fail so icinga2 does not start.

**Comment by lbetz** [comment]
puppet apply example/init_master.pp

I get with puppet 6.1.0 and puppet-icinga2 1.3.7:

object ApiListener "api"  {
  cert_path = "/etc/icinga2/pki/master.localdomain.crt"
  key_path = "/etc/icinga2/pki/master.localdomain.key"
  ca_path = "/etc/icinga2/pki/ca.crt"
  accept_commands = false
  accept_config = false
  ticket_salt = TicketSalt
}

with branch v2.x:

object ApiListener "api"  {
  ticket_salt = TicketSalt
}

So the results of both looks correct.

**Comment by gasperno** [comment]
I had to update dependency version and 2.x worked as expected with puppet 6. Thanks @lbetz

**Comment by rychannel** [comment]
The issue I see is that when optional parameters aren’t specified, the code specified blank strings in the config files for the parameters. This causes things to break as Icinga doesn’t like having parameters set to blank. Not sure if this is an issue with the puppet version or bad code.   
  

  
  

  
  
>

**Comment by lbetz** [comment]
I'm using the v1.3.7 and the upcoming v1.4.0 also with puppet6.

**Comment by lbetz** [comment]
Regarding the blank string problem: all icinga attributes are stored in a hash in puppet and are delivered via every object define resource to class object itself. And important all undef values are deleted by using the function delete_undef_values out from the stdlib module.

e.g. manifests/object/user.pp:
  # create object
  icinga2::object { "icinga2::object::User::${title}":
    ensure      => $ensure,
    object_name => $user_name,
    object_type => 'User',
    template    => $template,
    import      => $import,
    attrs       => delete_undef_values($attrs),
    attrs_list  => keys($attrs),
    target      => $target,
    order       => $order,
  }

**Comment by benningm** [comment]
You need to update your stdlib module to at least 5.1.0 because it fixes the function for puppet6:

https://github.com/puppetlabs/puppetlabs-stdlib/commit/792bcd478abd1076691047a9e4ea54c3535fe7b8

**Comment by lbetz** [comment]
thx

**Comment by benningm** [comment]
It may be gentle to add a check like:

```puppet
$stdlib_metadata = load_module_metadata('stdlib')                               
$stdlib_version = $stdlib_metadata['version']                                   
                                                                                
if(                                                                             
  versioncmp($puppetversion, '6' ) >= 0                                         
  and                                                                           
  versioncmp($stdlib_version, '5.1.0') < 0                                      
) {                                                                             
  notify { 'You may be affected by this bug: https://github.com/Icinga/puppet-icinga2/issues/505': }                                                             
}                                                                               
```

**Comment by gasperno** [comment]
@lbetz I noticed that v2.x branch is deleted. Any timelines on when v2.0 will be pushed to Puppet forge?

**Comment by lbetz** [comment]
@gasperno v2.x moved to the master branch.
