### ISSUE TITLE
Allow dots in data structures of object attributes 

### ISSUE THREAD

**Issue by dagobert** [voxpupuli/puppet-icinga2#509]
I have setup a host object as follows. The problem is that `bond1.50 is translated wrongly to the icinga2 configuration file.

```
  icinga2::object::host { 'myhost':
    target => '/etc/icinga2/conf.d/host__myhost.conf',
    import => [ 'generic-host', ],
    display_name         => 'myhost',
    address         => '10.1.0.1',
    groups               => [ 'routers', ],
    vars => {
      ip_addresses     => {
        'bond1.50' => '10.1.0.1',
      },
      general_services => [ 'ssh', ],
    },
  }
```
It is double quoted twice.

```
object Host "myhost"  {
  import "generic-host"

  address = "10.1.0.1"
  groups = [ "routers",  ]
  display_name = "myhost"
  vars.ip_addresses[""bond1.50""] = "10.1.0.1"
  vars.general_services = [ "ssh", ]
}
```

## Expected Behavior
The correct behaviour should be only double quoted once.

## Possible Solution
I have tried to use the `'-:"abc"` method but it did not work as I also already expected.
Not using single quotes in the puppet configuration also does not work since there is a dot in the key name.

## Your Environment

* Module version (`puppet module list`):
├── dwerder-graphite (v7.3.0)
├── example42-dhcpd (v2.0.16)
├── example42-firewall (v2.1.3)
├── example42-iptables (v2.1.15)
├── example42-logrotate (v2.0.19)
├── example42-monit (v2.0.18)
├── example42-monitor (v2.0.4)
├── example42-mysql (v2.1.8)
├── example42-network (v3.5.0)
├── example42-nrpe (v2.0.18)
├── example42-ntp (v2.0.16)
├── example42-openssh (v2.0.11)
├── example42-postfix (v2.0.22)
├── example42-puppi (v2.2.6)
├── example42-rsyslog (v2.0.15)
├── example42-snmpd (v2.0.16)
├── example42-sudo (v2.0.19)
├── example42-timezone (v2.0.16)
├── example42-tinydata (v0.3.1)
├── example42-tp (v2.3.1)
├── icinga-icinga2 (v1.3.7)
├── icinga-icingaweb2 (v2.2.0)
├── mybase (???)
├── puppetlabs-apt (v6.2.1)
├── puppetlabs-concat (v4.2.1)
├── puppetlabs-stdlib (v4.25.1)
├── puppetlabs-translate (v1.2.0)
└── puppetlabs-vcsrepo (v2.4.0)

* Puppet version (`puppet -V`): 5.5.8

* Operating System and version: Debian 9

**Comment by lbetz** [comment]
That's not a bug. At the moment just a string of a-zA-Z0-9_ is permitted as attribute or custom attribute names.

-: only works for values of attributes or custom attributes not for itself.

**Comment by lbetz** [comment]
Sorry, my answer was too fast. You describe an error outside of any attribute or custom attribute. 

Please checkout the related branch and test your config.

**Comment by dagobert** [comment]
I would be happy to test the fix. I have installed the module using `puppet module install`. Can you tell me which `--version` I have to specify to install the fix / branch?

**Comment by lbetz** [comment]
The branch is only available on github.

cd modules
git clone https://github.com/Icinga/puppet-icinga2.git icinga2
cd icinga2
git checkout bug/Allow-dots-in-data-structures-of-object-attributes-509

what's all
