### ISSUE TITLE
API configuration on Windows systems

### ISSUE THREAD

**Issue by netzwerkgoettin** [voxpupuli/puppet-icinga2#510]
Hi Lennart,

according to #499 there's another thing I noticed: I wrote a small class `icinga2_Client` like this:

````
class icinga2_Client {
  notify { "ICINGA2: Maintaining icinga2 client installation on this host...": }
  class { '::icinga2':
    manage_repo => true,
    ensure      => 'running',
    features    => [ 'checker', 'mainlog', ],
    confd       => false,
    repositoryd => false,
    constants   => {
      'ZoneName' => $facts['clientcert'],
      'NodeName' => $facts['clientcert'],
    },
  }

  class { '::icinga2::feature::api':
    pki             => 'puppet',
    accept_config   => true,
    accept_commands => true,
    endpoints => {
      'NodeName'            => {},
      '<$myhostname>' => {},
    },

  // ... more to come here...
````

It creates a syntactically correct `features-available/api.conf` but it **does not** enable it – I have to manually put it into `features-enabled`. I also tried to put it into `features` like this just for trial and error:
````
 features    => [ 'checker', 'mainlog', 'api' ],
````

But then it complains about `duplicate` and `already defined`.

Just for completeness :-)

Cheers,
  Marianne

**Comment by lbetz** [comment]
Moin,

what do you mean with 'put into features'? Did you move it or put it additional to features? For the last case then it's clear that you got a 'duplicate declaration'.

Is '<$myhostname>' the real code?

Bye
Lennart

**Comment by netzwerkgoettin** [comment]
Hi,

I put it additional to features and deleted the entry when it didn't work. And <$myhostname> is of course **not** real code but by hostname goes here which I can't publish here.

Cheers, Marianne

**Comment by lbetz** [comment]
How does the icinga2 config files look like? What daos 'icinga2 daemon -C' says?

**Comment by lbetz** [comment]
refs #511
