### ISSUE TITLE
Create vars.foo["bar"] objects in Hiera

### ISSUE THREAD

**Issue by omerlh** [voxpupuli/puppet-icinga2#520]
## Expected Behavior
I'm trying to create an apply rule based on host vars. I tried to achieve something similar to the [documentation](https://icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#using-apply-for-rules). This is the relevant hiera vars section:
```json
{
  "vars": {
     "object": {
         "blah": "value"
     }
  }
}
```
This should end up as `object["blah"] = value`.

## Current Behavior
Puppet does not ignore quotes when translating hiera JSON to icings DSL:

```
information/cli: Icinga application loader (version: r2.10.2-1)
information/cli: Loading configuration file(s).
critical/config: Error: syntax error, unexpected T_IDENTIFIER
Location: in /etc/icinga2/conf.d/objects/host/<>.conf: 12:15-12:20
 /etc/icinga2/conf.d/objects/host/host.conf(10):   vars.warning_notification = [ "<>", ]
/etc/icinga2/conf.d/objects/host/host.conf(11):   vars.critical_notification = [ "<>", ]
/etc/icinga2/conf.d/objects/host/host.conf(12):   vars.snyk[""<>""] = "<>"
                                                                                                   ^^^^^^
```

## Steps to Reproduce (for bugs)

1. Create the following config in hiera
2. Run puppet apply

## Context
I'm trying to write an apply rule that will create a check based on these vars.

## Your Environment

* Module version (`puppet module list`): 1.3.6
* Puppet version (`puppet -V`): 5.0.0
* Operating System and version: Ubuntu 16.06

**Comment by lbetz** [comment]
Please past your code or your hiera files.

**Comment by omerlh** [comment]
I updated my comment - the first snippet is the relevant part of hiera. Does this helps?

**Comment by lbetz** [comment]
Did you check the current version 1.4.0 of the module? That should solve the problem with double double quotes.

But what to hell this "<>" thing means? Do you know where it comes from?

**Comment by omerlh** [comment]
My bad redacting :) I'll upgrade module version and report if it will fix the issue

**Comment by omerlh** [comment]
Thanks! I can confirm that upgrading the version solve the issue, closing.

**Comment by lbetz** [comment]
thx for feedback.
