### ISSUE TITLE
Failed to apply catalog: One or more resource dependency cycles

### ISSUE THREAD

**Issue by jmuecke** [voxpupuli/puppet-icinga2#536]
## Expected Behavior
When the icinga2 module is loaded icinga2 should be installed.

## Current Behavior
Applying my configuration returns: 
```
(File[/etc/icinga2/constants.conf] => Class[Icinga2::Config] => Concat[/etc/icinga2/features-available/checker.conf] => File[/opt/puppetlabs/puppet/cache/concat/_etc_icinga2_features-available_checker.conf] => Class[Icinga2::Config] => File[/etc/icinga2/constants.conf])\nTry the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
Error: Failed to apply catalog: One or more resource dependency cycles detected in graph
```
## Steps to Reproduce (for bugs)
Load the icinga2-module:
```
classes:
        - icinga2
icinga2:
  manage_repo: true
```

## Context
I can't install nor manage icinga2. It doesnt seem to be linked to: https://github.com/Icinga/puppet-icinga2/issues/224 as I have a fresh concat module. See below.

## Your Environment

* Module version (`puppet module list`):
```
├── icinga-icinga2 (v2.0.1)
├── puppetlabs-apt (v6.3.0)
├── puppetlabs-concat (v5.3.0)
├── puppetlabs-stdlib (v5.2.0)
└── puppetlabs-translate (v1.2.0)
```
* Puppet version (`puppet -V`): 5.5.10
* Operating System and version: Ubuntu 18.04

**Comment by lbetz** [comment]
Did an apply on examples/init_repo.pp and got no dependency cycle. Please, check this on your environment if there is a difference to classifying by hiera.

**Comment by jmuecke** [comment]
You're right it is still an issue with an old concat. Which was hidden in our configuration. Thank you!
