### ISSUE TITLE
Puppet runs now fail on Debian Jessie due to removed backports repo

### ISSUE THREAD

**Issue by martinseener** [voxpupuli/puppet-icinga2#540]
## Expected Behavior
I expect puppet to run through without throwing an error on apt::backports due to a missing repository

## Current Behavior
Since the jessie-backports repo is no longer existing (and i haven't found an archive for it either) the module now fails - also apt-get runs since the repo is 404. 

## Possible Solution
I have no real solution but the question is more like: What we can do for Jessie users who can't directly upgrade to stretch but want to use this module. The issue seems to be the libmonitoring-icinga-perl package from backports.

My current workaround was forking the module and removing the `include apt::backports` line and the require line in the `repo.pp`. Now i was able to remove the backports.list (which we don't need anywhere else) and puppet works again.
I know this is only a temporary solution as we want to use the official repo and also want to be able to use Icinga correctly.

## Your Environment
* Module version (`puppet module list`): maybe not important but v2.0.2
* Puppet version (`puppet -V`): irrelevant
* Operating System and version: Debian Jessie 8.11

**Comment by dnsmichi** [comment]
There was an announcement in the last days that backports was removed from mirrors and now is in the archive. 

https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html
https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository

**Comment by lbetz** [comment]
How you can handle that is fully described in the documentation under 'Icinga 2 Installation'. The param 'manage_repo' is off by default so you're able to manage your own repositories.

**Comment by martinseener** [comment]
Oops, i think i missed that one. Thanks for clarification!

**Comment by lbetz** [comment]
You're welcome and sorry for taking so long.
