### ISSUE TITLE
Icinga2 custom config dir (not /etc/...)

### ISSUE THREAD

**Issue by mamiral** [voxpupuli/puppet-icinga2#543]
Hi,
i have my custom built icinga2 rpm (for reasons beyond my paygrade), which gets installed into /home/myuser/myusers-monitoring-system. All configs, certs and everything is under this directory (basically i'm setting CMAKE_INSTALL_SYSCONFDIR when building). Is there a way to tell the puppet-icinga2 module that sysconfdir is not /etc but in /home/myuser/...?

And thanks for this puppet module!

br
mm

**Comment by mamiral** [comment]
Ok, nvm, i think I've found it in the globals.pp. Just need to figure out where to set the $conf_dir variable.

**Comment by lbetz** [comment]
Correct, we split this. Not everyone should do that... and we won't support that.

**Comment by mamiral** [comment]
Is there a way i can add into data/ directory? So, i could have my .yaml for our linux distro. Think this would be the best way. Can't find where it's selected which .yaml to use for global cofig.

tnx

**Comment by lbetz** [comment]
Depends on your hierarchy. All key has to be like

icinga2::globals::conf_dir: /etc/icinga2

see data/*.yaml of the module itself.

**Comment by mamiral** [comment]
Hi,
yes, I'm editing data/Linux-kernel.yaml according to my setup. Think it's the most easy way to do it.
Think we can close this one.

Thanks for the help and for the module also!

br
mm

**Comment by lbetz** [comment]
Thx for using the module and for yout feedback.
