### ISSUE TITLE
REOPEN: does not handle database host correctly

### ISSUE THREAD

**Issue by yfried** [voxpupuli/puppet-icinga2#572]
I'm hitting the same issue as in #255. 
Also, [the workaround described](https://github.com/Icinga/puppet-icinga2/issues/255#issuecomment-286647989) doesn't work for me, as mysql client fails to connect:
```
Error: 'mysql -h '-:"database"' -P '3306' -u 'icinga2' 'icinga2core' < '/usr/share/icinga2-ido-mysql/schema/mysql.sql'' returned 1 instead of one of [0]
Error: /Stage[main]/Icinga2::Feature::Idomysql/Exec[idomysql-import-schema]/returns: change from 'notrun' to ['0'] failed: 'mysql -h '-:"database"' -P '3306' -u 'icinga2' 'icinga2core' < '/usr/share/icinga2-ido-mysql/schema/mysql.sql'' returned 1 instead of one of [0]
```

## Your Environment

* Module version (`puppet module list`):

icinga-icinga2 (v1.3.6)
icinga-icingaweb2 (v2.2.0)

* Puppet version (`puppet -V`):

Puppet v5.5.1

* Operating System and version:

Ubuntu 16.04.4 LTS

**Comment by lbetz** [comment]
Ok, I see the problem... -: takes care if the string is used as parameter of an Icinga object but not if we use it to connect a database.

The quick fix was to use the IP not use -: notation.

**Comment by lbetz** [comment]
You use puppet v5.5.1, please update to the current puppet-icinga2 version.

**Comment by lbetz** [comment]
You must not use any of the object attributes to assign as a string to an attribute. All this is parsed as unquoted. If you'd use the fqdn it'll work fine with the current version of this module.
