### ISSUE TITLE
Add new attribute last_failover to feature idomysql and idopgsql

### ISSUE THREAD

**Issue by lbetz** [voxpupuli/puppet-icinga2#577]
The IdoMysqlConnection and IdoPgsqlConnection objects provide a new attribute named last_failover which shows the last failover timestamp. This value also is available in the ido CheckCommand output.

**Comment by dnsmichi** [comment]
That's a runtime attribute populated from the core itself, you can not modify this from within the configuration in Puppet. 

Maybe you're confusing this with `failover_timeout`?

**Comment by lbetz** [comment]
No. Described in
https://icinga.com/docs/icinga2/v2.11.0-rc1/doc/16-upgrading-icinga-2/#flapping-configuration
under HA Failover.

**Comment by lbetz** [comment]
Ok, my fault it's an API attribute.
