### ISSUE TITLE
Same zone defined and exported on multiple nodes error

### ISSUE THREAD

**Issue by mamiral** [voxpupuli/puppet-icinga2#589]
Hello, I guess this is more of a puppet problem, but maybe (as a feature) a class could be added which collects zones and adds all endpoints into one respective zone config object... If such thing is even possible in puppet.

What I'm trying to do:
I have predefined zones such as 'data manager' zone, 'maintenance' etc. I try to define and export respective zone when a node in zone is added (in foreman). Ofc this means that if there are two machines in the same zone, that zone will be defined and exported twice, each zone with only one endpoint.

(puppet) Error: A duplicate resource was found while collecting exported resources

Is it possible to collect zones on the master machine and add all the endpoints to it. For now I can get around it by just defining zone title as $::fqdn. Is this the only way?

Thanks! 
And thanks for your work!

**Comment by lbetz** [comment]
Ah, sorry for the long time....

I don't use zones as exported resources, only endpoint are exported and collected by a tag. So of course all zones have to declare at any node.

**Comment by mamiral** [comment]
Hi,
yes, i have also stopped using exported zones, had a troubles with satellites.
