### ISSUE TITLE
Host var value is replaced with icinga2 variable value

### ISSUE THREAD

**Issue by rwaffen** [voxpupuli/puppet-icinga2#591]
I pass a fact to a host var, but getting a icinga2 internal variable returned.

```
infra::profile::icinga::export_host::vars:
  machine_type: "%{facts.virtual}"
```

```
class infra::profile::icinga::export_host (
...
  Hash $vars               = {},
){
...
    @@icinga2::object::host { $host_name:
      import          => $host_template,
      host_name       => $host_name,
      address         => $address,
      zone            => $parent_zone,
      vars            => $vars,
      check_command   => $check_command,
      enable_flapping => $enable_flapping,
      target          => "/etc/icinga2/zones.d/${parent_zone}/${host_name}.conf",
    }
...
```

For Solaris Zones the fact "virtual" returns "zone". But in icingaweb2 i see the value for machine_type ist replaced with "Master". Which is the name of the zone the host is living in.

## Expected Behavior
the value for machine_type should be "zone".

## Current Behavior
the value for machine_type is replaced with the icinga2 zone name when machine_type has the value "zone" from puppet.

## Possible Solution
???

## Steps to Reproduce (for bugs)
1. Assing a variable to a Host
2. Set the value "zone" in hiera/puppet
3. ???
4. profit

## Your Environment
* Module version (`puppet module list`): 2.3.0
* Puppet version (`puppet -V`): 5.5.16
* Operating System and version: Oracle Enterprise Linux 7.6

**Comment by lbetz** [comment]
That is a correct behaviour. The parse of this module print zone without quotes to the icinga config because zone is an attribute.

You have to disable the parse for this value and set quotes by yourself.

infra::profile::icinga::export_host::vars:
  machine_type: "-:\"%{facts.virtual}\""

**Comment by rwaffen** [comment]
"-:" disables the parsing?

**Comment by lbetz** [comment]
Yes. Only for that value or attribute.

**Comment by lbetz** [comment]
Please have a look at the documentation, chapter Parsing Configuration.

**Comment by rwaffen** [comment]
ah okay. sorry.

that helped:
```
machine_type: '-:"%{facts.virtual}"'
```

and if this is desired behavior, than we can close this issue.

**Comment by lbetz** [comment]
You're welcome.
