### ISSUE TITLE
Faulty configuration created if NodeName is service.example.com

### ISSUE THREAD

**Issue by vicinus** [voxpupuli/puppet-icinga2#605]
If a fqdn starts with service., host. or user. then the required quotation marks are not generated, because it is mistaken for an attribute or variable (custom attribute) from the host, service or user context (host.name, service.check_command, user.groups, ...)

Example:

```
class { 'icinga2':
  constants => {
    'NodeName' => 'service.example.com',
  },
}
```
## Expected Behavior
The file /etc/icinga2/constants.conf should contain the following line:
```
const NodeName = "service.example.com"
```
## Current Behavior
The file /etc/icinga2/constants.conf contains the following line:
```
const NodeName = service.example.com
```
## Possible Solution
If there is no way to distinguish automatically between the two variants, then there should be a way to force that a value is quoted.

**Comment by lbetz** [comment]
Thx for your report.
The solution is described 'Parsing Configuration', with -: in front of a string the parser will be disabled for the complete string. But notice now you've to set " on your own like

constants => '-:"service.example.com"'
