### ISSUE TITLE
This module doesn't seem to work properly on machines named "icinga2"

### ISSUE THREAD

**Issue by baldurmen** [voxpupuli/puppet-icinga2#608]
I tried to run this module a long time ago (#268) and for the love of me, I couldn't find what was going on.

Recently, I decided it was time to give it another go, and everything was working perfectly, until I got to provision my icinga2 master, who's hostname is `icinga2`.

On that machine (running the same exact puppet snippets as the other machines), I got all sorts of issues. Default data from hiera wasn't read, variables weren't set, puppet complained I was calling the same class multiple times, etc.

I reinstalled the machine from scratch (keeping the same `icinga2` hostname) and had the same exact problems.

And then, out of desperation, I changed the hostname to `monitoring` and now all is well and everything works as intended.

I doubt the puppet version or libs affect anything (currently running 5.5), since I had those issues in #268 running puppet 3.

I'd be happy to see if others can reproduce this issue : )

**Comment by baldurmen** [comment]
I did a few more tests, and it seems it might actually be a bug in Puppet. I'll keep looking and will update this ticket with more info

**Comment by lbetz** [comment]
Yes, more info is required.
I tried to reproduce your problem on a centos7 platform named icinga2.localdomain with puppet 5.5.19 but everything works fine.

**Comment by baldurmen** [comment]
Sorry, I know this was a bad bug report, the current world situation keeps me very busy :(

I'm currently writing a better bug report on Puppet's Jira, as I've been able to reproduce this issue with another module.

I'll close this for now, as it's not an icinga2 problem :)

Thanks for the work you do.
