### ISSUE TITLE
Tunning of OS for icinga2 application

### ISSUE THREAD

**Issue by dosmanak** [voxpupuli/puppet-icinga2#620]
Provide the options to tune system settings for the icinga2 application.

It would be beneficiary to be able to setup the system settings for Icinga, limits in particular.

## Expected Behavior
The icinga2 module offers the posibility to setup the system limits for the application.

## Current Behavior
The icinga2 is installed with default systemd limits.

## Possible Solution
For systemd it can be done using systemd config `/etc/systemd/system/icinga2.service.d/limits.conf`. Something like:
```
[Service]
LimitNOFILE=50000
LimitNPROC=50000
TasksMax=infinity
```
It could be generated in the file `manifests/service.pp` using some new globals variables and with notification to `systemctl daemon-reload`.

## Steps to Reproduce (for bugs)
In some special environment (probably many checks on many monitored hosts)

## Context
Icinga ends with the following log.
```
[2020-06-10 06:25:09 +0200] critical/ApiListener: Cannot accept new connection: Too many open files
```

## Your Environment
* Module version (`puppet module list`): icinga-icinga2 (v2.0.2)
* Puppet version (`puppet -V`): 6.16.0
* Operating System and version (`lsb_release -d`): Debian GNU/Linux 9.12 (stretch)

**Comment by lbetz** [comment]
Pretty idea, thx. But it works only on systemd based systems, of course. That mean we've to classify the supported plattforms, again. Shit.  But it's a sensible feature request.

**Comment by lbetz** [comment]
At Icinga the limits can be set in a sysconfig file, see
https://icinga.com/docs/icinga2/latest/doc/17-language-reference/#constants
but we don't manage these setting in this module.

And maybe it's better to use a module like
https://github.com/camptocamp/puppet-systemd
for this problem.

**Comment by lbetz** [comment]
@dosmanak you described a possible solution but that does not work. Did you try that?

**Comment by dosmanak** [comment]
Well, I took working example from Debian Jessie, where I can see it works.
But as I check now, it does not work on Debian Stretch. I am confused and I am sorry I misslead you.

```
# lsb_release -d; for pid in $(pidof icinga2); do grep "Max open files" /proc/$pid/limits; done
Description:	Debian GNU/Linux 8.11 (jessie)
Max open files            50000                50000                files     
Max open files            50000                50000                files     
Max open files            50000                50000                files
```
```
# lsb_release -d; for pid in $(pidof icinga2); do grep "Max open files" /proc/$pid/limits; done
Description:	Debian GNU/Linux 9.12 (stretch)
Max open files            16384                16384                files     
Max open files            16384                16384                files     
Max open files            16384                16384                files
```
O both versions, the systemctl claims it should be 50000:
```
# systemctl show icinga2 |grep LimitNOFILE
LimitNOFILE=50000
LimitNOFILESoft=50000
```

**Comment by lbetz** [comment]
Hm, not problem you#re welcome and thx for the report. I tested it on CentOS 7 only and it also does not work.

**Comment by dosmanak** [comment]
> At Icinga the limits can be set in a sysconfig file, see
> https://icinga.com/docs/icinga2/latest/doc/17-language-reference/#constants
> but we don't manage these setting in this module.

I did not expect the value defined in /etc/default/icinga2 still works using systemd. But I see it does.
So setting:
`ICINGA2_RLIMIT_FILES=50000` in /etc/default/icinga2 works and I expect it works even using sysV init.

**Comment by lbetz** [comment]
Unfortunately, no. I did it on centos 6 and sysconfig does not work. I'm working on it.

**Comment by lbetz** [comment]
Still a problem is, we need a restart and not a reload if we change these parameters.

**Comment by lbetz** [comment]
We discussed this and this configuration is not necessary in any known environment. If so, then a bug in the core may be to blame.
