### ISSUE TITLE
Question: import db schema: custom prefix not used.

### ISSUE THREAD

**Issue by PedroMSantosD** [voxpupuli/puppet-icinga2#621]
Hi,

This is a question on development environment - not production - just guidance needed.

when using the module to setup a different table prefix,
i.e. testing2113, the prefix used on the database still is "icinga_"; and 
the query from icinga, using the custom prefix, keeps failing

puppet module current code

```
class icinga2::feature::idomysql(
...
  $table_prefix           = undef,
  $import_schema          = false,
...
  # import db schema
  if $import_schema {
    if $ido_mysql_package_name and $manage_package {
      Package[$ido_mysql_package_name] -> Exec['idomysql-import-schema']
    }
    exec { 'idomysql-import-schema':
      user    => 'root',
      path    => $::path,
      command => "${_mysql_command} < \"${ido_mysql_schema}\"",
      unless  => "${_mysql_command} -Ns -e 'select version from icinga_dbversion'",
    }
  }
...
```
-->

## Expected Behavior
I expect mysql schema to be imported with the proper prefix.

## Current Behavior
schema is imported with default table prefix: icinga.
no matter what.

## Possible Solution
WorkAround:
I can avoid using a custom prefix. Defaults DO work without issues (icinga_ prefix set and understood by database).

Required:
import exec should dynamically build the prefix (not a mysql expert, not even sure if this is possible without droping and rebuilding mysql dump) or be specific about the prefix being hardcoded

## Steps to Reproduce (for bugs)
get a clean database where user has required permissions
```
mysql> drop database icinga2020;
Query OK, 61 rows affected (0.39 sec)

mysql> create database icinga2020                                                   -> ;
Query OK, 1 row affected (0.01 sec)

mysql> show grants for myIcinga                                                     -> ;
+----------------------------------------------------------+
| Grants for myIcinga@%                                    |
+----------------------------------------------------------+
| GRANT USAGE ON *.* TO `myIcinga`@`%`                     |
| GRANT ALL PRIVILEGES ON `icinga2020`.* TO `myIcinga`@`%` |
+----------------------------------------------------------+
2 rows in set (0.00 sec)
```
set hieradata for mysql:
```
icinga2::feature::idomysql::password: Hello.2345_A
icinga2::feature::idomysql::host: 172.16.30.1
icinga2::feature::idomysql::port: 3306
icinga2::feature::idomysql::user: myIcinga
icinga2::feature::idomysql::database: icinga2020
icinga2::feature::idomysql::enable_ssl: false
icinga2::feature::idomysql::enable_ha: true
icinga2::feature::idomysql::table_prefix: testing2113
icinga2::feature::idomysql::import_schema: true
```
Run puppet, This will execute the import script.
Table is NOT prefixed:
```
mysql> use icinga2020;
Database changed
mysql> show tables;
+----------------------------------------+
| Tables_in_icinga2020                   |
+----------------------------------------+
| icinga_acknowledgements                |
| icinga_commands                        |
| icinga_commenthistory                  |
| icinga_comments                        |
| icinga_configfiles                     |
| icinga_configfilevariables             |
...
```

icinga config file is using the prefix:
```
# cat ido-mysql.conf
# This file is managed by Puppet. DO NOT EDIT.
library "db_ido_mysql"

object IdoMysqlConnection "ido-mysql" {
  host = "172.16.30.1"
  port = 3306
  user = "myIcinga"
  password = "Hello.2345_A"
  database = "icinga2020"
  table_prefix = "testing2113"
  enable_ha = true
  enable_ssl = false
}
```

Icinga is now NOT able to interact with the database, due to the wrong import. from /var/log/icinga2/icinga2.log 
```
[2020-06-18 11:18:28 -0400] critical/IdoMysqlConnection: Error "Table 'icinga2020.testing2113dbversion' doesn't exist" when executing query "SELECT version FROM testing2113dbversion WHERE name='idoutils'"
Context:
	(0) Reconnecting to MySQL IDO database 'ido-mysql'
```

## Context

I'm migrating installation /  configuration / upgrade of icinga2 from custom scripts to puppet.
As per my development tests, I currently can not manage table prefix  using puppet, only the icinga configuration part.

## Your Environment

* Module version (`puppet module list`):
# puppet module list
/etc/puppet/modules (no modules installed)
/usr/share/puppet/modules (no modules installed)
* Puppet version (`puppet -V`):
# puppet -V
3.8.7
* Operating System and version:
Icinga:
# cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
# uname -a
Linux monitoring-icinga-master-2.mdev.internal 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
# rpm -qa | grep icinga2
icinga2-2.11.3-1.el7.icinga.x86_64
icinga2-ido-mysql-2.11.3-1.el7.icinga.x86_64
icinga2-common-2.11.3-1.el7.icinga.x86_64
icinga2-bin-2.11.3-1.el7.icinga.x86_64

Mysql docker image
$ docker images | grep mysql
mysql                                        latest                    b8fd9553f1f0        9 months ago        445MB

```
mysql> status
--------------
mysql  Ver 8.0.17 for Linux on x86_64 (MySQL Community Server - GPL)

Connection id:		48
Current database:	icinga2020
Current user:		root@localhost
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		8.0.17 MySQL Community Server - GPL
Protocol version:	10
Connection:		Localhost via UNIX socket
Server characterset:	utf8mb4
Db     characterset:	utf8mb4
Client characterset:	latin1
Conn.  characterset:	latin1
UNIX socket:		/var/run/mysqld/mysqld.sock
Uptime:			46 min 0 sec

Threads: 2  Questions: 24308  Slow queries: 0  Opens: 909  Flush tables: 3  Open tables: 406  Queries per second avg: 8.807
--------------
```

Note, although my puppet is way too deprecated, and I have to tweak the module for it to work; I'm under the impression that the  import instruction needs the prefix substitution (i don't know if this is possible thought)...  
Maybe we should only use the default prefix ? ; 
Does this work on current puppet 5+ (you may close it if it does!, And I'll adjust myself) ?
Am I missing any other configuration steps/hiera variables required to trigger the prefix during import?

 

Thanks in advance,

**Comment by lbetz** [comment]
We keep an eye on it, I thing it's possible.

**Comment by lbetz** [comment]
But why you don't use a different database?

**Comment by PedroMSantosD** [comment]
Hi @lbetz , Thanks for replying.

just playing with the prefix, as said, workaround is leave defaults/ change DB, etc.

Just commenting the issue I found, in case it might be useful for anyone.

**Comment by lbetz** [comment]
We discussed that but the possible use is  to special.
