### ISSUE TITLE
Change all TLS certificates and keys to datatype Stdlib::Base64

### ISSUE THREAD

**Issue by lbetz** [voxpupuli/puppet-icinga2#623]

**Comment by DeadHunter** [comment]
Has this ever been tested? Stdlib::Base64 does not include all chars for a cert file.

https://github.com/puppetlabs/puppetlabs-stdlib/blob/v7.1.0/types/base64.pp

```
parameter 'ssl_key' expects a match for Stdlib::Base64 = Pattern[/\A[a-zA-Z0-9\/\+]+={,2}\z/], got '-----BEGIN RSA PRIVATE KEY----- ....
```

**Comment by lbetz** [comment]
Your right. Icinga isn't really interested in puppet, so it has probably not been tested and obviously no one has used TLS this way since for almost 2 years. I will open an issue and fix it.
