### ISSUE TITLE
number with 'm' suffix is assumed to be a duration literal, converted to numeric literal

### ISSUE THREAD

**Issue by cwseys** [voxpupuli/puppet-icinga2#624]
Hi,
  I'm trying to use a custom variable 1000m in a service (icinga2::object::service.
[...]
$currmbps=1000
[...]
            vars => {
               maxbw     => "${currmbps}m"
            },
[...]

This creates a service config file with the following:
vars.maxbw = 1000m

Note, there are no quotes on this number.
When icinga2 executes the check command, it converts this to 60000 and executes the check command with 60000 instead of 1000m .  Looks like 1000m is interpreted as a duration literal, and converted to numeric literal.  (1000m is 1000 minutes is 60000 seconds).  The check command fails with unexpected input.

If quotes are manually added to 1000m ala
vars.maxbw = "1000m"
then 1000m is sent to check command.  Check command is happy.

I don't see documented how to quote the custom variable and prevent it from being converted.  My various tricks to sneak the quotes in have failed. It would be great if there were some workaround.

The puppet server is Debian 10 with puppet 5.5.10 (debian package) and icinga2 puppet module version v2.3.2.
Icinga2 version 2.10.3 (debian package).

Thanks for the great software!
C.

**Comment by lbetz** [comment]
Hi,

Tanks for reporting. I don't understand the Problem, 1000 minutes are 60000 seconds. The module as well as Icinga itself works correct, Icinga always convert an interval to a floating point.

Quoting 1000m leads to an syntax error in Icinga:
2020-07-21 21:30:43 -0700] critical/config: Error: Error while evaluating expression: Can't convert '1000m' to a floating point number.
Location: in /etc/icinga2/conf.d/templates.conf: 16:3-16:26
/etc/icinga2/conf.d/templates.conf(14): template Host "generic-host" {
/etc/icinga2/conf.d/templates.conf(15):   max_check_attempts = 3
/etc/icinga2/conf.d/templates.conf(16):   check_interval = "1000m"
                                          ^^^^^^^^^^^^^^^^^^^^^^^^
/etc/icinga2/conf.d/templates.conf(17):   retry_interval = 30s
/etc/icinga2/conf.d/templates.conf(18): 

But if it's working for you try to disable the parser:
vars => {
  maxbw => "-:\"${currmbps}m\""
},

Bye
Lennart

**Comment by cwseys** [comment]
> I don't understand the Problem, 1000 minutes are 60000 seconds.

The custom var 'maxbw' is not a time. The check command interprets the 
string "1000m" as 1000 Mbps.

" The  module as well as Icinga itself works correct, Icinga always 
convert an
> interval to a floating point.
> 
> Quoting 1000m leads to an syntax error in Icinga:
> 2020-07-21 21:30:43 -0700] critical/config: Error: Error while 
> evaluating expression: Can't convert '1000m' to a floating point number.
> Location: in /etc/icinga2/conf.d/templates.conf: 16:3-16:26
> /etc/icinga2/conf.d/templates.conf(14): template Host "generic-host" {
> /etc/icinga2/conf.d/templates.conf(15): max_check_attempts = 3
> /etc/icinga2/conf.d/templates.conf(16): check_interval = "1000m"
> ^^^^^^^^^^^^^^^^^^^^^^^^
> /etc/icinga2/conf.d/templates.conf(17): retry_interval = 30s
> /etc/icinga2/conf.d/templates.conf(18):

Well, this is for a custom variable, not an interval, so I apparently 
icinga doesn't explode in that case.

> But if it's working for you try to disable the parser:
> vars => {
> maxbw => "-:"${currmbps}m""
> },

That works almost perfectly! The config file now contains "1000m" and 
icinga passes that string to the check command:
[2020-07-22 11:58:48 -0500] notice/Process: Running command 
'/usr/lib64/nagios/plugins-local/check_eth' '-b' '1000m' '-c' '95' '-i' 
'eno2' '-p' '-w' '90':
So far so good!

However, the icinga web interface shows the custom variable without the 'm':
Custom Variables
Maxmbps 	1000

A little mismatching/misleading.

Thanks so much for your help!
C.

**Comment by lbetz** [comment]
You're welcome. Ah. Sorry my mistake. Then the described way with -: to disable the parser is the right and only way. Because the parser has no change to know what kind of type you wanna use.

**Comment by cwseys** [comment]
Perhaps scattering around this "escape code" in a few places in the 
documentation would help?  Especially in the Duration Literal section?

https://icinga.com/docs/icinga2/latest/doc/17-language-reference/#duration-literals

Not sure that is the correct place though:  If one is writing the 
icinga2 config by hand, one would just put "" around the string.

So I guess it would have to be in the puppet module documentation somewhere?

Probably doesn't come up very often....

Thanks again!
C.

**Comment by lbetz** [comment]
https://github.com/Icinga/puppet-icinga2#how-configuration-is-parsed
