### ISSUE TITLE
Mention Icinga2 package version. 

### ISSUE THREAD

**Issue by remy1991** [voxpupuli/puppet-icinga2#625]
There is no way to mention which icinga2 package version should be installed. 

I can only find the following code snippet in install.pp under manifests and this will try to install the latest version present in the repository which can break installation due to some dependencies not being present. Also due to this there is no way to keep the icinga2 version unanimous across the infrastructure since we are dependent on icinga2 repositories which keeps updated list of packages. 

```
    package { $package_name:
      ensure => installed,
      before => File[$cert_dir, $conf_dir],
    }

```

If there is way to bypass this and mention a version of icinga2 package, please let me know. 

## Your Environment

* Module version (`1.3.4 (tag)`): (but i can see same behaviour in recent versions as well) 
* Puppet version (`4.10`):
* Operating System and version:
Working on Debian buster (10.5)

**Comment by lbetz** [comment]
Checkout the documentation 'Usage - Installation' in README.md to use this module to install a specific version. But keep in mind, if you also manage other packages like icinga2-idomysql or iciga2-idopgsql, you have to manage these packages and the icinga2 package yourself

**Comment by lbetz** [comment]
Please update to the current version 2.4.1.

**Comment by remy1991** [comment]
@lbetz Thank you for the info
I ended up implementing the same way but was just wondering if there a different way to do it hence this post. 

>But keep in mind, if you also manage other packages like icinga2-idomysql or iciga2-idopgsql, you have to manage these packages and the icinga2 package yourself

Yes, this bit is the necessary. 

Closing this, thanks.

**Comment by lbetz** [comment]
There is purposely no other way. The package managers are too different in behaviour. And with the IDO and schema updates, it may not be used anyway.

We follow the concept that Puppet is not software management.
