### ISSUE TITLE
Unable to pass literal as var due to hash parsing

### ISSUE THREAD

**Issue by jensalmer** [voxpupuli/puppet-icinga2#644]
Due to the hash parsing introduced in e9d964311a9705fb093662ce75fac2b2de29e05a, string literals that look like a hash can no longer be rendered correctly.

Example case:

```
    @@icinga2::object::service { "http-service-check":
      import        => ['generic-service'],
      service_name  => 'myhttpservice',
      host_name     => $::fqdn,
      check_command => 'http',
      target        => "/etc/icinga2/zones.d/main/services.conf",
      vars          => {
        'http_vhost'  => 'service.foo',
        'http_uri'    => '/status',
        'http_string' => '{"state":"RUNNING"}',
        'http_ssl'    => true,
        'http_port'   => 443,
        'http_sni'    => true,
      },
    }

```
-->

## Expected Behavior
This should result in this generated config:
```
object Service "http-service-check" {
  import "generic-service"

  host_name = "host.foo"
  check_command = "http"
  vars.http_sni = true
  vars.http_ssl = true
  vars.http_uri = "/status"
  vars.http_port = 443
  vars.http_vhost = "service.foo"
  vars.http_string = "{\"state\":\"RUNNING\"}"
}

```

## Current Behavior
Results in invalid configuration:
```
object Service "http-service-check" {
  import "generic-service"

  host_name = "host.foo"
  check_command = "http"
  vars.http_sni = true
  vars.http_ssl = true
  vars.http_uri = "/status"
  vars.http_port = 443
  vars.http_vhost = "service.foo"
  vars.http_string = {
  ""state":"RUNNING"" = ""
}
}

```

**Comment by lbetz** [comment]
Hi,

thx for your report. The parser is very simple and is not designed for this one. But you can use '-:' as prefix to disable parsing this string, e.g.

'http_string' => '-:"{\\"state\\":\\"RUNNING\\"}"',

you see, you've to add quotes yourself. If you have a puppet string with variables you've to escape the beginning and ending quotes too.

There's a short description in the README under 'How Configuration is parsed'.

Bye
Lennart
