### ISSUE TITLE
Application of the module fails on Windows Server 2019

### ISSUE THREAD

**Issue by mattiasgiese-giz** [voxpupuli/puppet-icinga2#645]
Applying the module on a freshly provisioned system leads to a complete failure on the puppet side. Puppet complains that it cannot open a handle to a service:

```
PS C:\Windows\system32> puppet agent -tv
Info: Using configured environment 'icinga'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Failed to apply catalog: Failed to open a handle to the service:  The specified service does not exist as an installed service.
```

The only service resource in this specific catalog is the on coming from this module. After installing the `icinga2` package manually through chocolatey resolves the issue and the puppet run completes succesfully

## Expected Behavior

Application of the catalog should leave me with a preconfigured icinga2 instance on the server.

## Current Behavior

Without manual installation of the `icinga2` package puppet fails completely.

## Possible Solution

No solution, but workaround: Install the `icinga2` package before-hand

## Steps to Reproduce (for bugs)

Use the module in any way, shape or form.

## Context
 I am trying to configure the `icinga2` client on a new system. The same code worked on previously deployed systems (all Windows Server 2019) just fine.

## Your Environment

* Module version (`puppet module list`): icinga2 3.0.0
* Puppet version (`puppet -V`): 6.19.1
* Operating System and version: Windows Server 2019 Standard 1809

**Comment by lbetz** [comment]
Hi,

Windows Server 2019 isn't supported, but I tried it and it works fine. The error message also doesn't indicate a problem with the module. Is your puppet agent working correctly, maybe without any manifest?

Bye
Lennart

**Comment by mattiasgiese-giz** [comment]
Please excuse my very late update on this. After banging my head against the wall for a good while i finally found the culprit.
With a recent Puppet 6.x release you are able to directly set the user context for a service on Windows. I was 'misusing' resource overrides to change the context of the Icinga service resource like this:

```
if $::facts['os']['name'] == 'windows' {
  Service <| title == 'icinga2' |> {
    logonaccount => 'LocalSystem',
  }
}
```

It would be nice if one could change the account directly through the agent configuration part of this module.
I could give creating a PR a try if this is something you guys also deem useful.

**Comment by lbetz** [comment]
You're welcome. Fine and a PR would be fine. Windows is always the last one on our list because the handling for test and our low knowledge about Windows...
