### ISSUE TITLE
Support conditional blocks inside objects

### ISSUE THREAD

**Issue by jcharaoui** [voxpupuli/puppet-icinga2#652]
One of the great features of Icinga2 is the ability to include code blocks within host and service definitions.

For example:
````
apply Service "eventlog_" for (eventlog => config in host.vars.eventlog) {
  import "generic-service"
  check_command = "eventlog-windows"
  max_check_attempts = 1 
  volatile = true
  command_endpoint = host.name
  vars += config
  assign where true
  ignore where host.vars.noagent

  if (config.check_interval) {
    check_interval = config.check_interval
  } else {
    check_interval = 1h
  }
}
````
Currently, it's not possible to define the `if` / `else` blocks using the Puppet module, the only alternative is to drop an extra config file.

**Comment by jcharaoui** [comment]
This could be solved in the same manner as the Puppetlabs Apache module, using a `custom_fragment` [parameter](https://github.com/puppetlabs/puppetlabs-apache/blob/main/manifests/vhost.pp#L171-L173).

**Comment by lbetz** [comment]
We discussed it years ago and decided against it. In contrast to Apache, the order is decisive and "only" at the end makes very few users happy. But you can use a fragment for an entire object, see icinga2::config::fragment.

**Comment by jcharaoui** [comment]
Fair enough, thanks for taking the time to reply.
