### ISSUE TITLE
Event Commands - visudo - Permissions for icinga user   

### ISSUE THREAD

**Issue by Gninieb** [voxpupuli/puppet-icinga2#665]
FEATURE Request: May it be possible to add a array parameter for roll out permission for the icinga user on the agent to trigger event commands like start/stop/restart service xyz

```
class icinga2::globals(
  [...]
 Array[String]          $visudo_authorization, 
# (note: spaces must be TAB)
 [...]
}
```
-->

## Expected Behavior
At the moment it's time wasting to use event commands because you have to add authorisation for the icinga user in visudo to start/stop/restart a service by hand.

In my case I want to use a event command to stop ntp and use ntpdate to trigger a sync and start ntp afterwords if my NTP Deviation Check is in critical hard state. 

If the module prevent an array parameter which extend the visudo it whould be very helpful!

## Current Behavior
no way to enrich the visudo

## Possible Solution
echo $visudo_authorization >> /etc/sudoers  

echo 'icinga  ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop ntp' >> /etc/sudoers

**Comment by lbetz** [comment]
Sorry, but managing sudo config isn't a job for a module like icinga2. Such a module is used only to configure the icinga2 software and not sudo, logrotate, apache, etc. Please use another module e.g. saz/sudo. And bring it together in your own profile class.

**Comment by lbetz** [comment]
And the most important thing is, this module doesn't manage an user that's done by the packages.
