### ISSUE TITLE
Unable to set package version.

### ISSUE THREAD

**Issue by madelaney** [voxpupuli/puppet-icinga2#670]
## Expected Behavior

I'd like to be able to set the package version.

## Current Behavior

I can only set the package to be installed, but I cannot mange the package version itself.

## Possible Solution

If we look at [install.pp (lines 24 - 27)](https://github.com/Icinga/puppet-icinga2/blob/master/manifests/install.pp#L24-L27), we could replace the value of `ensure` with a variable (which defaults to `installed`) in which users can override the value if they do so desire.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Module version (`puppet module list`): 3.1.3
* Puppet version (`puppet -V`): 4.17
* Operating System and version: Ubuntu 18.04/16.04 LTS

**Comment by lbetz** [comment]
Hi,

please set 'manage_packages => false' and manage the packages on your own as described in the documentation:

# class of extra module icinga/icinga
include ::icinga::repos

package { 'icinga2':
  ensure => latest,
  notify => Class['icinga2'],
}

class { '::icinga2':
  manage_packages => false,
}
