### ISSUE TITLE
"Clever" escaping of variables ruins configuration

### ISSUE THREAD

**Issue by joernott** [voxpupuli/puppet-icinga2#688]
When setting a host variable containing special characters, the puppet module tries to do some "clever" escaping of that string. So, I have a password for accessing the health check API and I am trying to set the host variable "health_check_password" to "password_containing_an_unbalanced_bracket)". That results in an entry   vars.health_check_password = "password_containing_an_unbalanced_bracket") with the bracket outside of the quotes. Of course, this results in a broken configuration file.

```
host{ 'dev-mon1-tst-v05.company.com':
  ... (various other stuff and many other vars left out)
  vars => {
    health_check_password = $health_check_password,
  },
}
```
-->

## Expected Behavior
The string should be placed inside the config as I specified it. If I want the module to do some clever escaping for me, there should be
a) a way to turn it on and off or
b) a function I can call to do the escaping or
c) both of the above

## Current Behavior
The module believes, it is smarter than me and screws up the config, because it can't handle some cases in the forced automatic escaping

## Steps to Reproduce (for bugs)
setup up a host, where a variable contains some unbalanced brackets, some umlauts or special characters
```
host{ 'dev-mon1-tst-v05.company.com':
  ... (various other stuff and many other vars left out)
  vars => {
    health_check_password = 'password_containing_an_unbalanced_bracket)',
  },
}
```
## Context
Creating a host with a host variable containing something the module didn't expect.

## Your Environment

* Module version 3.1.3
* Puppet version (`puppet -V`): 6.23.0
* Operating System and version: RHEL7.9

**Comment by lbetz** [comment]
Hi Joern,

nice to hear something from you... please disable the parser for all passwords.

    health_check_password = "-:\"${health_check_password}\"",

**Comment by joernott** [comment]
Hi Lennart,
thanks for the quick reply. The "-:" somehow escaped me before.

It just took me a while to figure out the edge case for a monitored server which is not managed by puppet and thus defined "manually" in hiera (and the password in an eyaml. But for that case, I simply ended up with 

'dev-bas1-pos-v02.coimpany.com':
      vars:
        pos_dev_01_tst_password: "-:\"%{lookup('health_dev_bas1_password')}\""

resulting in the password being stored in the eyaml and having the escape working.
