### ISSUE TITLE
Please do not force-push in HEAD branch

### ISSUE THREAD

**Issue by thomas-merz** [voxpupuli/puppet-icinga2#690]
Lieber @lbetz ,  
es gibt Leute/Firmen, die eure Repos regelmäßig und automatisch lokal syncen und jedes Mal (das ist IMHO nicht das erste Mal!?) damit unnötige Arbeit haben, wenn Du `git push -f` direkt im `HEAD` Branch ausführst.

Unsere lokale commit-Historie bis heute:
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/22958542/138705204-f6759866-4c9d-4e47-b82f-06af4cf5557e.png">

Eure upstream commit-Historie seit heute:
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/22958542/138705256-9a0ce87a-3f9d-4f09-a40d-e3614e5f9c4c.png">

Man sieht, dass 55d706dac237c0c1ef6eadfa7afbb2fb66a92af2 vom 22.10.2021 durch 7ac569a9a452e39e17d0e1bffda656a3a1f3997c vom 25.10.2021 ersetzt wurde.

## Expected Behavior
Repo lässt sich ohne manuelle Intervention immer und jederzeit und automatisch syncen.

## Current Behavior
Repo lässt sich seit 23.10.2021 NICHT MEHR ohne manuelle Intervention immer und jederzeit und automatisch syncen.

## Possible Solution
Bitte niemals `git push -f` im `HEAD`!

## Context
Nun müssen unbekannt viele "Kunden" das lokal selber fixen, was in jedem einzelnen Fall sicher nicht viel Aufwand ist, aber in Summe doch unnötig viel.

Vielen Dank für die Aufmerksamkeit und bitte macht ansonsten weiterhin einen super tollen Job 👍  (Lob muss schliesslich auch mal sein 🎁 🙇‍♂️ )

**Comment by thomas-merz** [comment]
Lokaler Fix:
* unprotect repo (if protected "Allowed to force push")
* `git reset --hard HEAD^1 && git push -f origin HEAD`
* protect repo again
* sync again

**Comment by lbetz** [comment]
Check. Please note that the language here is English.

**Comment by thomas-merz** [comment]
Check, too 😄
