### ISSUE TITLE
Chocolatey missing in dependencies

### ISSUE THREAD

**Issue by zilchms** [voxpupuli/puppet-icinga2#691]
When applied on a windows agent, chocolatey as a package provider is used. Chocolatey however is not in the dependencies of the module.

## Expected Behavior

The module should tell the user that it has a dependency on chocolatey if it is used in the code.

## Current Behavior

Without the chocolatey module it fails with:

Failed to apply catalog: Parameter provider failed on Package[icinga2]: Invalid package provider 'chocolatey'

## Possible Solution

Either a hard dependency on puppetlabs-chocolatey in the metadata.json is used. Or since this is not necessary for all OS systems, a "soft" dependency like icinga/icinga in the README.md would be nice to have.

## Context

Minor improvement, nothing serious.

Edit: According to the puppet style guide https://puppet.com/docs/puppet/7/style_guide.html#dependencies, the chocolatey dependency should be in the README.md and definitely not in the metadata.json

**Comment by lbetz** [comment]
thx
