### ISSUE TITLE
Passwords being replaced by "Sensitive[redacted]" in files

### ISSUE THREAD

**Issue by joernott** [voxpupuli/puppet-icinga2#699]
## Expected Behavior

The passwords should be redacted in the reports and in Puppetdb but I prefer the config files to actually contain the passwords and not "Sensitive[redacted]".

## Current Behavior
My ido-pgsql.conf looks like this:
```
# This file is managed by Puppet. DO NOT EDIT.
library "db_ido_pgsql"

object IdoPgsqlConnection "ido-pgsql" {
  host = "manually.redacted"
  port = 5432
  user = "icinga"
  password = "Sensitive [value redacted]"
  database = "icinga"
  enable_ha = true
}
```
There are currently 3 files showing this behaviour:
./features-available/api.conf:  ticket_salt = "Sensitive [value redacted]"
./features-available/ido-pgsql.conf:  password = "Sensitive [value redacted]"
./zones.d/master/api-users.conf:  password = "Sensitive [value redacted]"

As a result, icinga won't connect to the DB and complains about it.

## Possible Solution
I hadn't time to dig through the code yet, but it looks like the resource responsible for writing the ido config was forgotten when switching to sensitive types

## Steps to Reproduce (for bugs)
1. Use Icinga with v3.2.0 of the module
2. Validate, that icinga works
3. Update the module to 3.2.1 or 3.2.2
4. Run puppet
5.  grep -r "Sensitive" /etc/icinga2
```
./features-available/api.conf:  ticket_salt = "Sensitive [value redacted]"
./features-available/ido-pgsql.conf:  password = "Sensitive [value redacted]"
./zones.d/master/api-users.conf:  password = "Sensitive [value redacted]"
./zones.d/master/api-users.conf:  password = "Sensitive [value redacted]"
```

## Your Environment

* Module version (`puppet module list`): 3.2.1 and 3.2.2
* Puppet version (`puppet -V`): 6.25.1
* Operating System and version: RHEL7.9

**Comment by lbetz** [comment]
Hi Jörn,

after updating the modul in all your environments you have to restart all puppetserver processes. Please take notice of https://github.com/Icinga/puppet-icinga2#environment-bleed.

Bye
Lennart

**Comment by joernott** [comment]
Hi Lennart,
updating the module on our dev puppetserver is fairly trivial. But in production, we have around 40 environments. We bundle and tag "releases" containing specific versions of puppet modules and our software. These are deployed automatically in our automated test pipeline environments and manually in maintenance windows on preproduction/production or customer environments. We have to do this in fixed maintenance windows which are spread through a release cycle. So, for a few months, we will have different versions of the icinga module in those environments and having our monitoring broken for such a long time is not really an option. And sadly, a puppet module update does not warrant emergency hotfix maintenance the same way the log-shell bug did. So I can't force the environment owners to accept a maintenance window and hotfixes all at the same time.

**Comment by lbetz** [comment]
It wasn't the plan for that to happen. By the time it was noticed, the 3.2.0 release had been out for a few days and it was too late to undo it. See #689

**Comment by lbetz** [comment]
Hi Jörn,

Is there anything else I can do for you?

Bye
Lennart

**Comment by joernott** [comment]
We'll try to figure this out, @bastelfreak is currently working on the topic and we'll comment here our way of handling it in staged environments. So, at the moment, there is nothing, you can do there.

**Comment by lbetz** [comment]
@joernott, can this ticket be closed?

**Comment by joernott** [comment]
@lbetz, the problem is not gone but we worked around it by disabling puppet on our icinga masters for several weeks until all environments were updated with newer icinga2 modules. Whenever we needed to run puppet, we manually corrected the screwed up passwords after disabling puppet again.

The issue can be closed, as we still have our bug report towards puppetlabs.
