### ISSUE TITLE
Object#=~ is called on TrueClass

### ISSUE THREAD

**Issue by deric** [voxpupuli/puppet-icinga2#711]
I have many warnings in `puppetserver` logs that looks like this:
```
lib/puppet_x/icinga2/utils.rb:351: warning: deprecated Object#=~ is called on TrueClass; it always returns nil
lib/puppet_x/icinga2/utils.rb:186: warning: deprecated Object#=~ is called on TrueClass; it always returns nil
lib/puppet_x/icinga2/utils.rb:190: warning: deprecated Object#=~ is called on TrueClass; it always returns nil
lib/puppet_x/icinga2/utils.rb:193: warning: deprecated Object#=~ is called on TrueClass; it always returns nil
lib/puppet_x/icinga2/utils.rb:196: warning: deprecated Object#=~ is called on TrueClass; it always returns nil
lib/puppet_x/icinga2/utils.rb:199: warning: deprecated Object#=~ is called on TrueClass; it always returns nil
lib/puppet_x/icinga2/utils.rb:201: warning: deprecated Object#=~ is called on TrueClass; it always returns nil
lib/puppet_x/icinga2/utils.rb:204: warning: deprecated Object#=~ is called on TrueClass; it always returns nil
```
`puppet-icinga2` version `3.3.1`. 

Is it possible to fix this?

One of the [affected lines](https://github.com/Icinga/puppet-icinga2/blob/master/lib/puppet_x/icinga2/utils.rb#L186)

```ruby
      if row =~ %r{^-:(.*)$}m
        return Regexp.last_match(1)
      end
```
Probably we could check the `row` type at the beginning of the `parse(row)` function? It might slightly speed up parsing.

**Comment by lbetz** [comment]
Thx. I will look at it.

**Comment by caniwi** [comment]
I am getting this message as well.  I am running icinga2 v3.4.0

**Comment by lbetz** [comment]
What kind of puppet version you're running on the server? My 7.13.1 doesn't report that in puppetserver.log with severity INFO.

**Comment by deric** [comment]
`puppetserver` in version `7.9.1-1bullseye`

```
$ /opt/puppetlabs/puppet/bin/ruby -v
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
```
@lbetz You're right it's not logged in `puppetserver.log` but systemd's journal: `journalctl -e -u puppetserver`

**Comment by lbetz** [comment]
Ok, I don't have these messages on my puppetserver 7.5.0 with ruby 2.7.3p183... mybe I have to update first.
... gotcha.

**Comment by lbetz** [comment]
Ok, either I have no idea how to fix it, or the cache is interfering.

**Comment by lbetz** [comment]
fixed in branch bug/711, please restart your puppetserver before testing it.

**Comment by deric** [comment]
@lbetz So far it looks good. Thanks for the quick fix!

**Comment by lbetz** [comment]
thx. 9 days ago, not sooo quick.

**Comment by lbetz** [comment]
Release will come at the weekend.
