### ISSUE TITLE
Using export and query_objects leads to hostgroup objects being defined multiple times

### ISSUE THREAD

**Issue by gmwubs** [voxpupuli/puppet-icinga2#727]
In issue #392 a solution to achieve a substantial gain in performance was suggested when using exported resources to create several objects i.e. host and hostgroup objects in large environments.

## Expected Behavior
 Our base manifest for icinga2 defines actions that span all three types of Icinga2 nodes, i.e. adding subscriptions and repositories supplied by a RH Satellite / Capsule setup, before installing packages. We then configure a node either as icinga2 client node, satellite node and a master node based on the role assigned to it.
 
Given our strong DRYS implementation we also define hostgroups from the base manifest, which are created based on things like physical location, network-zone, puppet-role etc. 

Only if the node in question isn't assigned the role icinga2_master or icinga2_satelite, we configure it as an icinga2 client node in the same manifest accordingly.

On the node that's collecting the resources using the query_objects class, the hostgroups should be defined only once, since icinga2 will otherwise refuse to reload or fail to restart. We expected the module to support this.

## Current Behavior
For hosts, the method currently implemented will undoubtedly work just fine, since hosts should be unique objects at all times (and most of the times, they are). But given our findings, we wonder if anyone ever tried using the export / query_objects functionality to create hostgroups dynamically?

We were testing this in development environment, because we want to dynamically create hostgroups based on puppet role, network zone and datacenter (amongst others) of any node. We find that the icinga2 master (running top-down config sync) creates hostgroups in the target file(s) just as many times as the resources are exported by hosts. For instance: if there are 4 nodes exporting the same hostgroup, the node collecting them using the query_object class will define the hostgroup 4 times in the target file. 

## Possible Solution
Our solution was to slightly alter the puppetdb query to sort by title alone (since the certificate doesn't really matter at this stage):

```
$pql_query =  puppetdb_query("resources[parameters] { ${_environments} type = 'Icinga2::Object' and exported = true and tag = 'icinga2::instance::${destination}' and nodes { deactivated is null and expired is null } order by title }")
```

Then to ensure we get a unique list of objects to create by adding the unique() statement around $pql_query :

```
37   unique($file_list).each |$target| {
38     $objects = unique($pql_query).filter |$object| { $target == $object['parameters']['target'] }
```

## Steps to Reproduce (for bugs)
1. Setup Icinga2 Master with distributed monitoring and top-down config sync with HA satellite nodes in each network zone and several client nodes per zone.
2. Have each node define and export hostgroups based on a number of facts (satellite zone, network zone, puppet role, etc.)
3. Monitor the target file on the target node that will use the class query_objects
4. Watch puppet create the mentioned groups multiple times.

## Context
We were trying to utilize the export + query_objects functionality to manage hostgroups dynamically, since we consider managing them manually to be toil and prone to error.

## Your Environment
* 3.6.1
* 7.23
* RHEL 7.9 / 8.7

**Comment by lbetz** [comment]
I'm not sure flooding PuppetDB with duplicate and triplicate objects is a good idea. Have you ever check how the additional unique affects the runtime behavior? Also, the order was meant to keep the objects belonging to a host together in the config file.

**Comment by gmwubs** [comment]
> I'm not sure flooding PuppetDB with duplicate and triplicate objects is a good idea.

I wasn't too keen on that either :-) But I know of setups where hosts export which service(s) they run (i.e. nginx, apache, mysql, postgresql, redis, etc.) so a service check is automatically defined and assigned. In those cases, you will also get duplicate, triplicate (and so on) objects?

The nodes we manage and monitor are actually the only entities (I think) that are really "aware" of their own location, puppet role, etc. So I thought exporting hostgroup resources based on those facts, collecting them on the master and making sure they were unique was the best way to create hostgroups on the master in a top-down config sync setup. 

Perhaps I've been looking at this the wrong way around. I have yet to find a better solution without hammering the puppetdb even more. The only solution (I think) is to have the Icinga2 master query the puppetdb for all the necessary information and then create hostgroups based on a unique list.

The additional unique appears to have little or no impact: 
- puppet run without the additional unique: 33,89 seconds (this created the additional hostgroup definitions)
- puppet run with the addiotional unique: 34,87 seconds (this run includes removing the additional hostgroup definitions created in the run before, the next run after this was 33,55 seconds)

> Also, the order was meant to keep the objects belonging to a host together in the config file.

We are also exporting the objects belonging to a host and collect them on the master. First we set a var: 
$target = `/etc/icinga2/zones.d/${zone}/$facts['networking']['hostname'].conf` 

And then set the target for the Endpoint, Zone and Host objects to reference that var. Since the export feature as introduced in module version 3.6.0, I was keen on using the query_objects, rather than collecting the resources.

**Comment by gmwubs** [comment]
We've opted for a different approach

**Comment by lbetz** [comment]
@gmwubs Perhaps you might briefly outline this other approach here?

**Comment by gmwubs** [comment]
We've slightly adjusted the query_objects class to suit our needs and included it in the profile we use to configure the icinga2_master and enable us to collect unique objects. This way we can manage it ourselves and no changes to the module are required (which may or may not ruin other users´ days).

**Comment by gmwubs** [comment]
Hi, I felt that I had to come back and share my findings.

We've change our approach from the one described above. We've been running into major issues while using the export attribute for host, zone and endpoint objects. After using puppet to install and configure each puppet managed node (approx. 2500) to be monitored using icinga2, the puppet runs on the icinga2 master increased to about 1500 seconds every time.

While I was still pondering on that issue, I went to work on adding a piece of information to each host to be displayed. It was then that we ran into another problem: we wanted to use a puppet fact to add the description to each host. The problem was: the description may or may not contain one or more ' - ' delimiter(s), which the parser in the icinga2 puppet module would interpret as an operator. And since it makes no sense to try and subtract two strings the icinga2 config check would fail.

After giving it some thought, I've decided to change the approach. I defined a file template (epp) to be used to create one tagged exported file resource for each host. This file resource contains the 3 necessary object definitions for the icinga2 clients to be monitored. The icinga2 master would then collect the file resource based on the tag. This reduced the number of exported resources per host to just one.

But, much to my surprise, this also fixed the issue of the puppet runs taking so long: the average puppet run on the icinga2 master dropped from 1500 s per run to about 45 - 50 s per run. Doing the math reduced my surprise a bit, but I decided to share this nevertheless

**Comment by lbetz** [comment]
You can disable parsing for values, see
https://github.com/Icinga/puppet-icinga2#how-configuration-is-parsed

**Comment by lbetz** [comment]
Can you share your code snippets?

**Comment by gmwubs** [comment]
> Can you share your code snippets?

Of course, I will look into this. It might take me some time, because I have to be absolutely certain the snippets won't reveal anything about the clients infrastructure :-)

**Comment by lbetz** [comment]
I pushed my changes to branch feature/tuning. I replaced the export resources from icinga2::object to icinga2::config::fragment. So the rendering of the icinga config will be done in the agent run and no longer in the run for the icinga config server.
To achieve a further gain in speed, all exported config can be written to one destination file.

**Comment by gmwubs** [comment]
> You can disable parsing for values, see https://github.com/Icinga/puppet-icinga2#how-configuration-is-parsed

I did try that, but found that in this particular case it didn't prevent the parser from doing it's thing :-)

The command `puppet facts show hostgroup` would result in output like this:
```
{ 
  "Icinga2 Master - Development"
}
```
Which would result in a custom var like this: 
`vars.description = "Icinga2 Master" - "Development"`

But since we need the description of every individual host we used a variable, $description (which made sense to me ;-) ) However, that would result in: 
$description = "$description"      :  `vars.description = "Icinga2 Master" - "Development"`
$description = "-:$description"    :  `vars.description = Icinga2 Master - Development`

I tried any variation, but that would either result in a message like "This variable has no effect. A value was produced and then forgotten" or send the name of the variable as the content of vars.description :-)

Which is why we opted to implement a file resource based on an embedded puppet template.

**Comment by lbetz** [comment]
The parser make the decision what to quote, that mean in your case you have to use

vars.description = '-:"Icinga2 Master - Development"'

for variable interpolation
vars.description = "-:\\"something like ${puppet-var} ... \\""
