### ISSUE TITLE
Resource-like declaration of icinga2::feature::api apparently not possible

### ISSUE THREAD

**Issue by christian-2** [voxpupuli/puppet-icinga2#744]
I have tried defining a Puppet class that includes resource-like declarations of classes `::icinga2` and `::icinga2::feature::api` as well as resource type `icinga2::object::zone` almost literally like in the example you provide in [section Agent ](https://github.com/Icinga/puppet-icinga2#agent) of the documentation. Such a class would be convenient, because it could e.g. assign constant attribute values of for `::icinga2::feature::api` that apply in my case (e.g. `$accept_config = true`) and calculate others (e.g. `$bind_host = $ip`).

However this fails: Puppet complains about a duplicate declaration of `Icinga2::Feature::Api`. I suspect this is because the definition of `::icinga2` states [`include prefix($features, 'icinga2::feature::')`](https://github.com/Icinga/puppet-icinga2/blob/f38a485f9c00e451f5cb42fa90bf354b9986909d/manifests/init.pp#L159-L159), i.e. it also declares `::icinga2::feature::api`. Reversing the order between `::icinga2` and `::icinga2::feature::api` also fails and is presumably prohibited by design: "you must include the icinga2 base class before using any icinga2 feature class".

I conclude from this that `::icinga2::feture::api` must be declared [include-like](https://www.puppet.com/docs/puppet/7/lang_classes.html#include-like-declarations) and that a resource-like declaration as in the provided example won't actually work. (This would be somewhat of a pity because I would have to provide all arguments verbatim in Hiera instead of having, say, three different classes that could serve for the master, for satellites, and agents more concisely. For many hosts that difference seems of concern.) Could you please clarify and perhaps change the manifest in the documentation, if applicable.

**Comment by lbetz** [comment]
Hi Christian,

the example [https://github.com/icinga/puppet-icinga2#agent](https://github.com/icinga/puppet-icinga2#agent) works like describe. You don't have to put the api feature to the features parameter (by default a list of mainlog, checker and notification).

It's also used so in [https://github.com/Icinga/puppet-icinga/blob/main/manifests/init.pp](https://github.com/Icinga/puppet-icinga/blob/main/manifests/init.pp), maybe classes you are looking for?

Bye
Lennart

**Comment by christian-2** [comment]
@lbetz Thanks for your quick response! Yes, that makes good sense. I've now removed `'api'` from `features => ['api','checker','mainlog']` in my declaration of `::icinga2` and this makes a subsequent resource-like declaration of `::icinga2::feature::api` possible exactly as described in the documentation.
